### ISSUE TITLE
libc.so crash

### ISSUE THREAD

**Issue by zhichaoLii** [cocos2d/cocos2d-x#17447] opened 2017-03-06 08:02 UTC
- cocos2d-x version: c++ 3.10
- devices test on: android
- developing environments
   - NDK version: r10e

Steps to Reproduce:

1. 
2. 

Crash info from fabric :

#0. Crashed: olitaire:remote
0  libc.so                        0xf6e93070 tgkill
1  libc.so                        0xf6e6e861 pthread_kill
2  libc.so                        0xf6e6f477 raise
3  libc.so                        0xf6e6bcbd (Missing)
4  libc.so                        0xf6e6a010 abort
5  libart.so                      0xf41a917b art::LogMessage::~LogMessage()
6  libart.so                      0xf416dd9b (Missing)
7  libart.so                      0xf4233015 art::gc::Heap::RequestConcurrentGCAndSaveObject(art::Thread*, art::mirror::Object**)
8  libart.so                      0xf41fb307 (Missing)
9  libart.so                      0xf42eee8f art::mirror::String::Alloc(art::Thread*, int)
10 libart.so                      0xf42ef40d art::mirror::String::AllocFromModifiedUtf8(art::Thread*, char const*)
11 libart.so                      0xf43310f9 art::Thread::InternalStackTraceToStackTraceElementArray(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobjectArray*, int*)
12 libart.so                      0xf4305185 (Missing)
13 system@framework@boot.oat      0x71bf5cc9 (Missing)

**Comment by dumganhar** [comment] 2017-03-07 03:35
How did you reproduce this problem?

**Comment by zhichaoLii** [comment] 2017-03-10 07:07
i don't know, it's only happen in the os 5.x.

**Comment by dumganhar** [comment] 2017-03-10 07:30
The information you provided is limited, we can't find out what's going wrong according this since all the functions in crash stack are system API.

**Comment by dumganhar** [comment] 2017-03-21 03:37
Closed this issue since it have been long time for response. If you still get this issue and could reproduce it. Feel free to re-open it.

**Closed as completed by dumganhar** 2017-03-21 03:37 UTC
Labels: platform:android
