### ISSUE TITLE
[v3.6-universal-wp8.1-cpptests]Node: Clipping-->Scroll View Demo:Crash

### ISSUE THREAD

**Issue by WenhaiLin** [cocos2d/cocos2d-x#11606] opened 2015-04-27 06:58 UTC
Device:Nokia Lumia 625
OS: Window Phone 8.1

**Comment by minggo** [comment] 2015-04-27 07:00
@andyque 
@stammen
Could you please take a look?

**Comment by stammen** [comment] 2015-04-28 02:52
@WenhaiLin  @minggo I am not able to reproduce this issue on my phones or in the emulator. I do not have a Lumia 625. Would you please send me more information.

**Comment by stammen** [comment] 2015-04-29 17:40
Fixed in pull request https://github.com/cocos2d/cocos2d-x/pull/11652

**Closed as completed** 2015-04-30 01:54 UTC
Labels: type:bug
