### ISSUE TITLE
[Win 7] cpp-test crash when clicking the next button in the clipping example

### ISSUE THREAD

**Issue by meiry** [cocos2d/cocos2d-x#10054] opened 2015-01-18 09:03 UTC
windows 7 32 bit visual studio 2012 crash when entering the clipping test and pressing the next button
error:

```
Unhandled exception at 0x007DFCA4 in cpp-tests.exe: 0xC0000005: Access violation reading location 0x00000000. 
```

**Comment by minggo** [comment] 2015-01-19 01:45
What's the engine version?

**Comment by meiry** [comment] 2015-01-19 06:05
Latest 3.4 rc1

**Comment by ghost** [comment] 2015-01-19 06:31
We have test v3.4rc1 on our PC but we can't reproduce the crash(issue 10054-56) you said. Our test environment is win8.1 64bit vs2013update3 and win7 64bit vs2012. So can you please clean your rep and project and test again? Thank you!

**Comment by meiry** [comment] 2015-01-19 07:33
sure i will do it , 
i by the way testing in 32bit  not 64bit  bit with 2012 express version.

**Comment by ghost** [comment] 2015-01-19 07:36
Yes, I know that, but now we don't have the test environment as yours.If the crash still happens, we will try to setup the same environment to figure it out.

**Comment by ghost** [comment] 2015-01-19 08:06
What I mean 64bit and 32bit is about the system, not the cocos2d-x project.

**Comment by meiry** [comment] 2015-01-20 13:05
Ok i did little debugging , the problem remain by the way .
in function : 

```
void BaseClippingNodeTest::nextCallback(Ref* sender)
{
    Scene *s = new (std::nothrow) ClippingNodeTestScene();
    s->addChild(nextAction());
    Director::getInstance()->replaceScene(s);
    s->release();
}

when steeping into  s->release();

in :
```

void Ref::release()
{
    CCASSERT(_referenceCount > 0, "reference count should greater than 0");

the _referenceCount  is 2 
but when it out of the scop of this function things get messed up 

something strange is going on here :

```
static Layer* nextAction()
{
    sceneIdx++;
    sceneIdx = sceneIdx % MAX_LAYER;

    auto layer = (createFunctions[sceneIdx])();

    return layer;
}

where sceneIdx is always -1  so createFunctions doesn't return something 
```

**Comment by dabingnn** [comment] 2015-01-21 07:51
It was fixed in pull request #10115

**Closed as completed** 2015-01-21 07:51 UTC

**Comment by meiry** [comment] 2015-01-21 13:02
@minggo 
you can close it also its working great
