### ISSUE TITLE
Sprites with alpha look darker when being animated

### ISSUE THREAD

**Issue by pablorealini** [cocos2d/cocos2d-x#16732] opened 2016-10-23 00:37 UTC
We noticed that in our game sprites with alpha looked darker and ended up finding out that it was an issue with premultiplied alpha.

cocos2d-x will by default premultiply every RGBA8888 texture, in our case we saw that the darker sprites problem appeared only on sprites that were being animated with the Animate action.

In the issue https://github.com/cocos2d/cocos2d-x/issues/93673 was added two lines to CCAnimate

```
 auto blend = static_cast<Sprite*>(_target)->getBlendFunc(); //THIS LINE
 _currFrameIndex = i;
 AnimationFrame* frame = frames.at(_currFrameIndex);
 frameToDisplay = frame->getSpriteFrame();
 static_cast<Sprite*>(_target)->setSpriteFrame(frameToDisplay);
 static_cast<Sprite*>(_target)->setBlendFunc(blend);  //THIS LINE
```

what those lines do is force the blendfunc to the one configured in the sprite ignoring the proper blendfunc determined by the current sprite frame texture.

In the test project you can see one case where the effect is rendered correctly, and one when the effect is rendered darker.

The difference between those two cases is that in the one that renders correctly the sprite is initialised with the first frame of the animation, so the blend func is consistent while the animation is running.

In the case that renders incorrectly the sprite is first created empty without referencing the animation sprites, and after that an Animate action is executed. In this case the sprite has ALPHA_NON_PREMULTIPLIED but the texture needs ALPHA_PREMULTIPLIED to be rendered correctly, and the Animate action will force ALPHA_NON_PREMULTIPLIED to be used.

We think this change is a big change in how cocos2d-x used to work and in our case, we almost always create an empty sprite and afterwards we set it up with an animation if needed.
If this remains we will need to either disable premultiplication, comment the lines in CCAnimate or change everywhere we create sprites to use the first sprite which is a worse match for how our engine works.

We created a small test project with this so you can test.
https://drive.google.com/open?id=0B88Hp_AZaft0QW8xYjhrZGN4aWc

![045f6c71888088fee8238da5be1271f159d5dd06](https://cloud.githubusercontent.com/assets/12350808/19623450/b8879924-989f-11e6-833f-966510f0b2cd.png)

**Comment by dumganhar** [comment] 2016-10-25 08:15
The code was updated in https://github.com/cocos2d/cocos2d-x/issues/9367
I will try to check it out.

**Comment by dumganhar** [comment] 2016-10-25 10:12
It's a boring issue. :(
`Sprite::setTexture` and `setBlendFunc` will both modify the `_blendfunc`.
IMO, setTexture should not modify blendfunc, its default value must be non-pre-multiply-alpha.
If developers wanna use a pre-multiply-alpha texture or custom blend func, he has the responsibility to set the correct blend func.

I mean setTexture & setBlendFunc should be decoupled. Otherwise, how to use the correct blend func ?

I have no idea for this now since any changes of blend func in cocos2d-x will break the compatibility.

@ricardoquesada , @minggo , what do you think?

**Comment by minggo** [comment] 2016-10-26 10:16
@dumganhar i agree with you. But if we change the `setTexture` behavior, it will break the compatibility. For example, @pablorealini relays on the feature.

@pablorealini i think you can work around it by revert #9367 currently.

**Comment by pablorealini** [comment] 2016-10-26 17:16
Thanks for the help, we will revert that commit and maybe if we wanna use what that commit fix we can create a custom Animate action?

Right now our new game "Kingdom Rush 4" don't have any custom blend but maybe in the future it could be cool to have some fx using that so we will need to find a way to use that feature.

**Comment by minggo** [comment] 2016-10-27 03:02
@pablorealini the issue is because `Sprite::setTexture()` will modify blend mode based on image feature(premultiplied or not). So currently, if developer don't what to the blend mode set by `Sprite::setTexture()`, he should re-set it after invoking `Sprite::setTexture()`.

**Comment by dumganhar** [comment] 2017-02-15 03:51
@minggo , since we could not break compatibility in v3, we could not resolve this issue right now.
Could we close this issue?

**Closed as completed** 2017-02-15 03:57 UTC
