### ISSUE TITLE
Failed to play background music on Android

### ISSUE THREAD

**Issue by pwang08** [cocos2d/cocos2d-x#15193] opened 2016-03-07 09:57 UTC
I found a bug of Playing backgroudn music on Android. Please check the attachment.
![63db5578-3b41-4457-b7b4-a823c070e55f](https://cloud.githubusercontent.com/assets/5799825/13565939/05d500fc-e48e-11e5-8399-e8da7783671f.png)

**Comment by minggo** [comment] 2016-04-26 07:03
Yep, i think it is a mistake.

**Comment by minggo** [comment] 2016-04-26 07:23
@pwang08 Thought it looks like a bug, but could you tell me how to reproduce it since it is not an issue all the time. Thanks.

**Comment by pwang08** [comment] 2016-04-26 07:40
It's easy to reproduce, if cc.loader.resPath has been set to a nonempty path.

**Comment by pwang08** [comment] 2016-04-26 07:41
In that case, relative path isn't equal with the full path.

**Comment by minggo** [comment] 2016-04-26 07:49
Got it. Thanks.

**Comment by minggo** [comment] 2016-04-26 08:00
It is fixed in #15512

**Closed as completed** 2016-04-26 08:05 UTC
Labels: type:bug, platform:android

**Comment by a493547253** [comment] 2019-02-12 06:46
I use quick cocos2dx ,cannot find this file ,how can I fix this problem

**Comment by minggo** [comment] 2019-02-13 02:08
This issue system is for cocos2d-x, not for quick. You should ask quick cocos2dx's owner.

**Comment by a493547253** [comment] 2019-03-05 05:29
> This issue system is for cocos2d-x, not for quick. You should ask quick cocos2dx's owner.

I think I kind find the problem ,it caused by android code. thank you
