### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [cocos2d/cocos2d-x#2339] opened 2013-04-09 15:35 UTC
I would like to point out that identifiers like "[`__CCDIRECTOR_H__`](https://github.com/cocos2d/cocos2d-x/blob/626f6286f3713ae776b7d5a8f9543edec130c5c7/cocos2dx/CCDirector.h#L27)" and "[`__CCINSTANT_ACTION_H__`](https://github.com/cocos2d/cocos2d-x/blob/e5baceb06b4f9933f0bdff02d0d017cd0aa40136/cocos2dx/actions/CCActionInstant.h#L27)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPPDonotdeclareordefineareservedidentifier-NoncompliantCodeExampleHeaderGuard) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by minggo** [comment] 2013-04-10 07:36
Thank you.
Any suggestion?

**Comment by elfring** [comment] 2013-04-10 13:51
Would you like to delete [double underscores](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#228797) from affected identifiers in your software library?

How do you think about to make [your include guards](http://en.wikipedia.org/wiki/Include_guard#Difficulties) not only standard-compliant but also really unique by appending [a kind of UUID](http://en.wikipedia.org/wiki/Universally_unique_identifier)?

**Comment by minggo** [comment] 2013-04-11 03:12
we can change everything to make it unique.

**Comment by elfring** [comment] 2013-07-01 14:05
I do not see that this commit "refactor checkParams()" fixed affected include guards.

**Comment by dumganhar** [comment] 2013-07-01 14:14
I Don't know why github close it by the keyword "2339' .

**Comment by elfring** [comment] 2013-07-01 14:20
Do you expect that your number "2339" should be connected with a different issue?

**Comment by dumganhar** [comment] 2013-07-01 14:27
It's our issue id on redmine system of our official site. www.cocos2d-x.org

**Comment by elfring** [comment] 2013-07-01 14:38
Does this GitHub issue need also a corresponding ticket in [the Redmine system](http://www.cocos2d-x.org/projects/cocos2d-x/issues)?

**Comment by dumganhar** [comment] 2013-07-01 14:46
No, Github issue doesn't need to related to the Redmine system.

**Comment by godyZ** [comment] 2013-08-21 03:36
@elfring Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2626

**Closed as completed** 2013-08-21 03:51 UTC
