### ISSUE TITLE
[Android] PcmAudioService::pause crash

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#18188] opened 2017-08-24 01:26 UTC
Reported at http://forum.cocos.com/t/bug/50296
![6cef365e8a69f924dfff1c4e4b4d36060a427e17](https://user-images.githubusercontent.com/493372/29611656-e4ef24a6-8830-11e7-9343-2eaa45eddc1d.png)

cocos creator 1.6.1.beta2
Device: 乐视 LE X620
System Version: Android 6.0,level 23

**Comment by umair6** [comment] 2017-09-19 05:12
@dumganhar I am facing this issue in my android app. Any update on fix?

**Comment by rizwangaminations** [comment] 2017-09-19 07:07
@dumganhar i am facing similar issue as well.
![screen shot 2017-09-19 at 12 03 23 pm](https://user-images.githubusercontent.com/31472835/30579581-bdb92488-9d32-11e7-8e7e-cd96113c41da.png)

**Comment by dumganhar** [comment] 2017-09-20 07:25
@rizwangaminations , any way to reproduce this problem?

**Comment by rizwangaminations** [comment] 2017-09-20 07:52
@dumganhar
I don't have any way to reproduce this bug, Only Crashlytics logs.
Logs indicate that App crashes while entering background.

I am are using
- cocos2d-x version:3.15.1
- NDK version: r13b
- file format: .ogg

**Comment by dumganhar** [comment] 2017-09-20 08:00
But the crash stack looks weird. It has to be 

PcmAudioService::pause
AudioPlayerProvider::pause
AudioEngineImpl::onEnterBackground

I mean the AudioPlayerProvider::pause is missing.

**Comment by rizwangaminations** [comment] 2017-09-20 08:45
@dumganhar 
I don't know why **AudioPlayerProvider::resume** is missing.
I am having same crash on my other apps as well with similar logs.

**Comment by G17hao** [comment] 2017-10-04 03:43
@dumganhar 
this stack information is the release version, the call may be optimized by the compiler.

**Comment by qinning** [comment] 2018-01-12 04:39
We have same crash, hope for help.

`_ZN7cocos2d12experimental15PcmAudioService5pauseEv+3
_ZN7cocos2d12experimental19AudioPlayerProvider5pauseEv+20
ZN7cocos2d12experimental15AudioEngineImpl17onEnterBackgroundEPNS11EventCustomE+22
ZNSt17Function_handlerIFvPN7cocos2d11EventCustomEESt5_BindIFSt7_Mem_fnIMNS0_12experimental15AudioEngineImplEFvS2_EEPS7_St12_PlaceholderILi1EEEEE9_M_invokeERKSt9_Any_dataS2_+22
ZN7cocos2d15EventDispatcher24dispatchEventToListenersEPNS019EventListenerVectorERKSt8functionIFbPNS_13EventListenerEEE+432
ZN7cocos2d15EventDispatcher13dispatchEventEPNS5EventE+252
Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeOnPause+74`

**Comment by shaniamjad** [comment] 2018-01-29 07:05
Hello guys, I am also getting this crash on my released game. I am not able to reproduce it on my end though but i am sharing crashlytics crashlogs with you guys so it can help you guys to investigate.
Please help as the crash is effecting our LIVE users. 
<img width="1333" alt="screen shot 2018-01-29 at 12 04 02 pm" src="https://user-images.githubusercontent.com/6037560/35497598-9a385444-04ec-11e8-8250-718a1a21518d.png">
http://crashes.to/s/112ff8c9d5a
@dumganhar @minggo

**Comment by hg-trv** [comment] 2018-06-27 12:09
same crash. same log
cocos 3.17
ndk r17
ogg files

**Comment by umair6** [comment] 2018-07-12 05:39
@dumganhar 
This resolved issue for me.
https://github.com/cocos2d/cocos2d-x/pull/18934

**Comment by drelaptop** [comment] 2018-07-13 08:37
PR have merged, it avoid crash issue when pcm audio service init failed. so that all will be silent when audio init filed, better than crash happened.

as I considered, the reason of init fail is the __OpenSL ES__ donesn't works well on some special android device. more discuss at https://discuss.cocos2d-x.org/t/audio-issue-in-3-17/42962

**Closed as completed** 2018-11-16 03:49 UTC
Labels: platform:android
