### ISSUE TITLE
TMX and FastTMX breakage

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8524] opened 2014-09-30 09:17 UTC
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5753). It was created at 2014/07/25 14:21:17 +0000
# Description

Notes and reproducible example: http://discuss.cocos2d-x.org/t/tile-map-sprite-rendering-is-broken-in-version-3-at-least-3-2/15757/6
# Comments
- lyubomirv added comment:
  Uploading the patch file that was pasted in the forum.

**Comment by minggo** [comment] 2014-10-08 07:45
@dabingnn 
Could you please take a look?

**Comment by lyubomirv** [comment] 2015-03-17 15:55
What is the status of of this issue? Is it fixed or are there plans to fix it? This is a real showstopper for moving to version 3, at least for me.

**Comment by yangws** [comment] 2015-07-24 09:46
I try to reproduct this issue, adding test code in both TMXIsoVertexZ test and TMXIsoVertexZNew test. TMXIsoVertexZNew as sample below:

```
TMXIsoVertexZNew::TMXIsoVertexZNew()
{
    auto map = cocos2d::experimental::TMXTiledMap::create("TileMaps/iso-test-vertexz.tmx");
    addChild(map, 0, kTagTileMap);

    auto s = map->getContentSize();
    map->setPosition( Vec2(-s.width/2,0) );
    CCLOG("ContentSize: %f, %f", s.width,s.height);

    // because I'm lazy, I'm reusing a tile as an sprite, but since this method uses vertexZ, you
    // can use any Sprite and it will work OK.
    _tamara = Sprite::create("TileMaps/iso.png");  // <----- Add a sprite which uses another texture different with TMX map.
    map->addChild(_tamara);
    _tamara->setAnchorPoint(Vec2(0.5f, 0));
    _tamara->setPosition(map->getLayer("Trees")->getTileAt(Vec2(29,29))->getPosition());
    _tamara->retain();

    auto move = MoveBy::create(10, Vec2(300,250) * (1/CC_CONTENT_SCALE_FACTOR()));
    auto back = move->reverse();
    auto seq = Sequence::create(move, back,nullptr);
    _tamara->runAction( RepeatForever::create(seq) );

    schedule( CC_SCHEDULE_SELECTOR(TMXIsoVertexZNew::repositionSprite));

}
```

The tests render results:
- TMXIsoVertexZ
  ![tmxisovertexz_render](https://cloud.githubusercontent.com/assets/488183/8871863/30960112-322b-11e5-91c6-dd2cc5f67fa7.gif)
- TMXIsoVertexZNew_Render
  ![tmxisovertexznew_render](https://cloud.githubusercontent.com/assets/488183/8871875/3cb1dda4-322b-11e5-87e5-0eb161513ac8.gif)

It seems that the TMXIsoVertexZ is incorrect, but TMXIsoVertexZNew is not, isn't it?

The TMXIsoVertexZ test case using cocos2d::TMXTiledMap which implement with BatchNode, the TMXIsoVertexZNew one using cocos2d::experimental::TMXTiledMap which implement with new Renderer.

Because the limitation of BatchNode, only one texture could be used, the TMXIsoVertexZ's effect is wrong.

How about your opinions about this issue?
@dabingnn  @ricardoquesada

**Comment by lyubomirv** [comment] 2015-07-24 10:01
From what I see in the `gif` animation, it looks like TMXIsoVertexZNew_Render is working correctly.

You've basically made it render the map elements line by line, right? I mean map line.

If this gets approved as a possible solution, is it possible to make the render mode configurable? Like, add a boolean parameter in the `TMXTiledMap::init()` method, that sets the render mode to either 1-call (current, fast) or by-line (new, slower). Like:

```
TMXTiledMap::init(<current parameters here>, bool renderModeSequentialZ = false);
```

Thus the current client code will not be broken, and new users can choose to enable the "New_Render" if they want, knowing that it will be a bit slower. So the users of the tmx map class can choose the slower mode if they, like me, need it, and if not, have the benefit of the faster rendering code.

**Comment by yangws** [comment] 2015-07-24 10:33
@lyubomirv 
Currently, there are two TMXTiledMap in engine, one in cocos2d namespace, another in cocos2d::experimental namespace.
The  TMXIsoVertexZ is test case for cocos2d::TMXTiledMap, the TMXIsoVertexZNew is same test case for cocos2d::experimental::TMXTiledMap.
It should be easily that using exprimental::TMXTiledMap instead cocos2d::TMXTiledMap in codes.

I don't know when cocos2d::TMXTiledMap will be replaced by exprimental::TMXTiledMap.

**Comment by lyubomirv** [comment] 2015-07-24 10:51
@yangws 
Maybe I didn't express myself correctly.

II understand that the classes from `experimental` eventually replace the same ones in the main `cocos2d` namespace. However, you expressed concern about that, because the new rendering method is slower than the current one.

So, what I suggested, is: Instead of completely replacing the old `TMXTiledMap` with the experimental one, why not merge only the new rendering code in the main class but keep the old one too, and make it possible for the user to select which rendering method he/she wants, when he/she creates the class? That way the rendering will be slow only for the people, that really need the correct way of rendering (the new one). The others will still benefit from the faster (current) rendering method.

I'd personally just replace the current with the correct one but that might make some users angry, and I'm not a maintainer of the project, so this is just my opinion.

**Comment by yangws** [comment] 2015-07-27 06:13
The cocos2d::TMXTiledMap and experimental::TMXTiledMap use different technology, if wan't insert another transparent sprite in to tile map, should use experimental::TMXTiledMap implementation. Due to the batch node limitation, cocos2d::TMXTiledMap only works fine with one texture.

**Comment by dabingnn** [comment] 2015-07-31 03:18
@yangws Could you please give a conclusion of this issue?

**Comment by yangws** [comment] 2015-07-31 03:37
The cocos2d::TMXTiledMap implement by BatchNode,
and experimental::TMXTiledMap implement by Renderer auto batch.
All representation mentioned above are match there design, the incorrect image of TMXIsoVertexZ test case is due to BatchNode limitation.
So, this issue nothing need to fix.

fI run the tilemap test and fast tilemap test in cpp-tests on ipad2, all test run at 60fps.
I think we can arrange it to schedule that remove the old TMXTiledMap, and change  experimental::TMXTiledMap's namespace to cocos2d.
@dabingnn

**Comment by dabingnn** [comment] 2015-07-31 06:44
Thanks, it seems that there is some limitation on TileMap based on `BatchNode`. My proposal is:
- Close this issue.
- Add a new ticket to refine TileMap.

**Comment by lyubomirv** [comment] 2015-07-31 10:19
@dabingnn @pandamicro So will this be fixed? And will it still be planned for 3.8? Could you please link to the new ticket about "refining" the `TileMap`? The ticket, that @yangws has made related does not seem related to this one at all (I saw the commit). Or am I missing something?

**Comment by pandamicro** [comment] 2015-07-31 10:41
I think what @yangws means is that you can safely use `experimental::TMXTiledMap`, and in the future we will replace `cocos2d::TMXTiledMap` with `experimental::TMXTiledMap`

**Comment by lyubomirv** [comment] 2015-07-31 10:45
@pandamicro Got it!

**Closed as completed** 2015-08-04 08:22 UTC
