### ISSUE TITLE
HttpClient crash on App Quit （windows)

### ISSUE THREAD

**Issue by c3076802** [cocos2d/cocos2d-x#13045] opened 2015-07-27 10:25 UTC
```
HttpClient::~HttpClient()
{
    CC_SAFE_DELETE(_requestSentinel);
    CCLOG("HttpClient destructor");
}
```

_requestSentinel might have ref > 1 when _responseQueue is not empty,
CC_SAFE_RELEASE_NULL should be called instead.

**Comment by WenhaiLin** [comment] 2015-08-13 07:46
@c3076802  I can't reproduce this issue. How to reproduce this issue easier?

**Comment by zilongshanren** [comment] 2015-08-18 04:05
can't reproduce, so I just close it here. If anyone have this issue again, feel free to reopen it .

**Closed as completed by zilongshanren** 2015-08-18 04:05 UTC
Labels: platform:win32
