### ISSUE TITLE
SimpleAudioEngine::sharedEngine()->playBackgroundMusic() will stop suddenly with no error

### ISSUE THREAD

**Issue by Gofive** [cocos2d/cocos2d-x#16975] opened 2016-12-09 03:19 UTC
cocos2d-x V2.6 when i play a mp3 about 1min long, SimpleAudioEngine::sharedEngine()->playBackgroundMusic() will stop suddenly with no error. I test that in Demo TestCpp, meet that again. just meet that on Android .

**Comment by dumganhar** [comment] 2016-12-09 06:14
Would this issue exist in v3.x?

**Comment by Gofive** [comment] 2016-12-09 06:37
@dumganhar  i haven't tested in v3.x

**Comment by dumganhar** [comment] 2016-12-09 06:40
Currently, we don't maintain v2.x, so please check whether this issue exist in v3.x. If it does exist, we will fix it in v3.x.

**Comment by Gofive** [comment] 2016-12-12 06:39
@dumganhar i have tested in v 3.13.1 , it also exist, show my mp3 file. [http://video.tunbaobao.com/test_music.mp3](url). Test by 'Audio-CocosDenshion' item in the 'CocosDenshionTest', SimpleAudioEngine::getInstance()->playBackgroundMusic(MUSIC_FILE);

**Comment by dumganhar** [comment] 2016-12-12 06:52
I tested it with
```c++
SimpleAudioEngine::getInstance()->playBackgroundMusic("fonts/test_music.mp3");
```
And the music file could be played entirely. I could not reproduce the issue. :(

Does this issue only happen on some specific devices?

**Comment by Gofive** [comment] 2016-12-12 07:08
@dumganhar show you the video . It only stop in the first time when i play the music , it's ok in the after playing. I have test in 3 devices .[http://video.tunbaobao.com/test_video.MP4](url)

**Comment by dumganhar** [comment] 2016-12-12 07:31
@longmian , I tested it with cpp-tests. It still worked without any problems.

**Comment by dumganhar** [comment] 2016-12-12 07:37
[doudoulong.mp4.zip](https://github.com/cocos2d/cocos2d-x/files/645302/doudoulong.mp4.zip)

@longmian ,you could check this video.

**Comment by Gofive** [comment] 2016-12-15 02:59
@dumganhar hey,what's device version you test on ? I have tested on two device, Android 4.1.2 is ok, but 5.0 is bad

**Comment by dumganhar** [comment] 2016-12-15 03:56
@longmian , I tested it on Meizu MX3, Android 5.0.1

**Comment by dumganhar** [comment] 2017-03-21 08:52
I closed this issue since we didn't get response from the reporter  for a long time.
@longmian, If you still meet this issue, feel free to open it again. Thanks.

**Closed as completed by dumganhar** 2017-03-21 08:52 UTC
