### ISSUE TITLE
3.14 linux linker failed on glfw

### ISSUE THREAD

**Issue by MrCapone** [cocos2d/cocos2d-x#17150] opened 2017-01-10 13:22 UTC
- cocos2d-x version: 3.14
- devices test on: Linux Mint 18

Steps to Reproduce:

1. create blank cpp project
2. run `cocos run -p linux`
3. you will get errors like

```
[100%] Linking CXX executable bin/MyGame
lib/libcocos2dInternal.a(CCGLViewImpl-desktop.cpp.o): In function `cocos2d::GLViewImpl::setFullscreen(GLFWvidmode const&, GLFWmonitor*)':
~/test/cocos2d/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:600: undefined reference to `glfwSetWindowMonitor'
lib/libcocos2dInternal.a(CCGLViewImpl-desktop.cpp.o): In function `cocos2d::GLViewImpl::setWindowed(int, int)':
~/test/cocos2d/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:613: undefined reference to `glfwSetWindowMonitor'
collect2: error: ld returned 1 exit status
```

**Comment by slackmoehrle** [comment] 2017-01-10 17:33
We don't test on Linux Mint. I will fire up an Ubuntu 16.01 instance and see if I can reproduce this too.

**Comment by MrCapone** [comment] 2017-01-10 18:15
@slackmoehrle Linux Mint 18 based on Ubuntu 16.04, so it must be similar.

**Comment by slackmoehrle** [comment] 2017-01-10 19:29
So far, I 
* cloned the `cocos2d-x-3.14` branch
* ran `git submodule ...`
* ran `download-deps.py`
* ran `setup.py`
* ran `./build/install-deps-linux.sh` - this failed saying I was missing packages.
* I then ran `sudo apt-get install sqlite3 libsqlite3-dev libglew-dev, libglfw3` and the packages `install-linux-deps.sh` told me to.
* I re-ran `./build/install-deps-linux.sh`, completed successfully.
* ran `sudo apt-get install cmake`. 
* ran `cocos new LinuxTest -p com.com.com -l cpp -d .`
* `cd LinuxTest`
* ran `cocos run -p linux` and you are correct. __I get the same errors__.

This also happens on `v3` branch and `cocos2d-x-v3.14`

@MrCapone thanks. I didn't realize they were cousins. I'll snag a copy and try there also.

**Comment by minggo** [comment] 2017-01-11 02:47
I just tested in ubuntu 16.04 in v3.14, no problem met.

**Comment by minggo** [comment] 2017-01-11 09:12
From the [doc](http://www.glfw.org/docs/latest/group__window.html#ga81c76c418af80a1cce7055bccb0ae0a7) we know `glfwSetWindowMonitor` is added  since GLFW v3.2. And [install_glfw.sh](https://github.com/cocos2d/cocos2d-x/blob/v3/tools/travis-scripts/install_glfw.sh#L3) require 3.2 version. So please make sure you installed correct glfw version.

**Comment by MrCapone** [comment] 2017-01-11 15:51
I have projects with older cocos version on same machine (3.12 and 3.13.1). And both projects build and run fine, so it's not deps problem. I also try build cpp-empty-test 3.14 and get same error.

**Comment by slackmoehrle** [comment] 2017-01-11 16:23
![screen shot 2017-01-11 at 11 10 51 am](https://cloud.githubusercontent.com/assets/7491758/21856511/4a6536be-d7f0-11e6-8929-9ff0969357d9.png)

**Comment by MrCapone** [comment] 2017-01-11 16:50
problem appear after add `glfwSetWindowMonitor` method. Maybe this method require some specific linker flags?

**Comment by MrCapone** [comment] 2017-01-11 17:13
I found the problem. I have `libglfw3` and `libglfw3-dev` installed in my system by apt package manager from ubuntu repos. And ubuntu repos have version 3.1. So linker uses system version of glfw (3.1) instead of cocos2d-x version (3.2). After uninstalling `libglfw3` and `libglfw3-dev` by `sudo apt-get purge libglfw3 libglfw3-dev` build runs fine.

Maybe you should modify `install-deps-linux.sh` to avoid this problem in future.

**Comment by slackmoehrle** [comment] 2017-01-11 18:22
@MrCapone  good find. I purged those 2 and now it builds for me as well.

**Comment by minggo** [comment] 2017-01-12 01:26
`install-deps-linux.sh` will uninstall libglfw, but it seems outdated, it just tries to uninstall libglfw2. I will update it.

**Comment by minggo** [comment] 2017-01-12 02:08
fixed in https://github.com/cocos2d/cocos2d-x/pull/17165

**Comment by minggo** [comment] 2017-01-12 02:12
and send to v3.14.1 too https://github.com/cocos2d/cocos2d-x/pull/17166

**Closed as completed** 2017-01-12 03:43 UTC
Labels: platform:linux

**Comment by cirosantilli** [comment] 2017-10-20 22:16
I wish we wouldn't require such edge libglfw. Removing distro packages from the user is invasive :-(

**Comment by minggo** [comment] 2017-10-23 02:21
yep, do you have any better suggestions?

**Comment by MrCapone** [comment] 2017-10-23 05:12
Disable Findglfw.cmake, put glfw library to cocos/external and link static.

**Comment by minggo** [comment] 2017-10-23 06:12
If so, then should we do for other libs, such as png, jpeg and so on. I think it is better if we don't have to store external lib as possible.

**Comment by cirosantilli** [comment] 2017-10-23 06:31
I think the problem is that glfw is a new library with constantly changing interfaces, while png and jpeg are much more solid.

Maybe we should keep things as shared as possible (also a debian package requirement and makes binaries smaller), until it starts causing us problems, then we build static.

Or alternatively, limit the GLFW features to a given GLFW version present in most distros.

**Comment by minggo** [comment] 2017-10-23 07:03
> Or alternatively, limit the GLFW features to a given GLFW version present in most distros.

We may update it as GLFW updates, and it is hard to limit it in a given version because we provide prebuilt lib on other platforms. So i think it is reasonable to provide prebuilt GLFW lib as @MrCapone  suggested.
