### ISSUE TITLE
rendertexture's savetoFile problem

### ISSUE THREAD

**Issue by reasonMix** [cocos2d/cocos2d-x#16113] opened 2016-07-13 12:49 UTC
when draw a label to the render texture and call the savetoFile to create the png file.the png file have white border on ios platform. because the label use ALPHA_NON_PREMULTIPLIED blend mode. and on ios platform the image-ios.mm savetoFile only use the kCGImageAlphaPremultipliedLast flag

**Comment by ricardoquesada** [comment] 2016-07-14 23:54
thanks. could you post the code to reproduce it? thanks.

**Comment by reasonMix** [comment] 2016-07-15 13:48
@ricardoquesada 
  local text = cc.Label:createWithTTF('hello world','font/yours.ttf',40)

  local target = cc.RenderTexture:create(winSize.width, winSize.height, 2)
  target:beginWithClear(0,0,0,0)
  text:setPosition(winSize.width / 2,winSize.height/2)
  text:visit()
  target:endToLua()
  target:saveToFile('aaa.png',1)

**Comment by ricardoquesada** [comment] 2016-07-21 01:53
Thanks. But I couldn't reproduce it. The image that I got on an iPhone is the following, and it seems to be Ok. is that right? I'm using C++ code instead of Lua though.

**UPDATE:** Image had the letters in white... generating a new one in red (see below)

**Comment by reasonMix** [comment] 2016-07-21 02:02
@ricardoquesada where is the png file,i can't seen it

**Comment by ricardoquesada** [comment] 2016-07-21 02:38
@reasonMix Uploading it again... In case it doesn't work, this is the test case that I created:
https://github.com/cocos2d/cocos2d-x/pull/16180

![issue16113](https://cloud.githubusercontent.com/assets/232330/17009687/1b2ad9d4-4eb2-11e6-9c83-fabdaf14ee19.png)

I couldn't find any white border in this image.

**Comment by reasonMix** [comment] 2016-07-21 04:08
@ricardoquesada please paste your code,do you create the label with ttf?

**Comment by ricardoquesada** [comment] 2016-07-21 05:37
@reasonMix:  the code is here, in this Pull Request: https://github.com/cocos2d/cocos2d-x/pull/16180

**Comment by reasonMix** [comment] 2016-07-21 07:35
@ricardoquesada i am wrong,in mac platform,the png file will have a black border

**Comment by ricardoquesada** [comment] 2016-07-21 18:26
@reasonMix this is the image from the Mac:
![issue16113](https://cloud.githubusercontent.com/assets/232330/17034093/fb52e60e-4f35-11e6-8e55-f1906f65940e.png)

**Comment by reasonMix** [comment] 2016-07-22 00:02
@ricardoquesada use the white color，will see the black border
![issue16113](https://cloud.githubusercontent.com/assets/5474177/17042712/a5e3b5c4-4fe2-11e6-9b12-80bb2f465353.png)

**Comment by ricardoquesada** [comment] 2016-07-22 19:13
@reasonMix thanks. I was able to reproduce it.
I think this is happening because the `RenderTexture`'s texture is using premultiplied alpha internally, but when we save the PNG, we save it the data (premultiplied) as if it were unpremultiplied. So, you open the PNG... the editor thinks it is pure RGBA, but it is RGBA-premultiplied.

This does not happen on iOS because iOS is using its own function to save to PNG, and it is passing the parameter `kCGImageAlphaPremultipliedLast` to the bitmap info.

I think I have to unpremultiplied it manually before saving it.

**Comment by reasonMix** [comment] 2016-07-23 01:54
@ricardoquesada yes,but if use a sprite to render to target,the PNG file is fine no border,so maybe this is not easy solve this problem

**Comment by ricardoquesada** [comment] 2016-07-23 03:15
@reasonMix makes sense what you are saying... I've been trying to fix this bug doing different stuff and I couldn't fix it. I tried to unpremultiplied alpha and other stuff and didn't work.
perhaps I should take a look at how the ttfs are being created.

I'll take a look at this again this monday with fresh eyes.

**Comment by drelaptop** [comment] 2019-05-21 08:29
> https://github.com/cocos2d/cocos2d-x/pull/9393 looks like a workaround to fix this `alpha` issues.

so the defect is we treat the data (premultiplied) as if it were unpremultiplied. 

as I confirmed one way to fix it is force set the internal texture of RenderTexture premultiplied value to `true` in this situation.

**Comment by rh101** [comment] 2019-07-22 14:21
@minggo This issue can probably be closed given that #19782 was merged in to allow saving non-premultiplied images.

**Closed as completed** 2019-09-20 07:49 UTC
