### ISSUE TITLE
[ScriptingCore] Require cached js script lead to app crash after GC

### ISSUE THREAD

**Issue by wangxingfred** [cocos2d/cocos2d-x#13912] opened 2015-09-18 03:13 UTC
In cocos2dx-3.7 and cocos2dx-3.8:

Cached js scripts in ScriptingCore.cpp as filename_scripts are not Rooted, which means they are not GC-reachable.
After reclaimed by GC, anthoer JS_ExecuteScript call using the dangling pointer cause app crash.

**Comment by pandamicro** [comment] 2015-09-18 05:10
How can I reproduce the crash ?

**Comment by wangxingfred** [comment] 2015-09-18 05:17
1.require("xx.js")
2.forceGC()
3.require("xx.js")

**Comment by wangxingfred** [comment] 2015-09-18 06:22
It's easier to reproduce with vs2012 debug mode.

**Comment by pandamicro** [comment] 2015-09-19 09:30
It's irrelevant with GC, in fact you are not really suppose to do such thing. While requiring a script, the consequence is related with its content, you may load many objects into the current context, GC will release some of the local objects, but not global ones. Re-requiring it will not succeed because previous require have already saved a cache of the compiled script. Anyway, you won't be able to predict the consequence.

You can try this : 

```
require("xx.js");
cc.sys.cleanScript("xx.js");
require("xx.js");
```

**Comment by wangxingfred** [comment] 2015-09-21 01:57
In fact, I try the 3 steps asynchronously:
Step1 - click button1 for require("xx.js")
Step2 - click button2 for forceGC()
Step3 - click button1 for require("xx.js")

So, I think the require consequence is not the reason.

Besides, what's the meaning of compiled scripts cache if a cleanScript call is need everytime re-require a script ?

**Comment by drelaptop** [comment] 2018-05-23 06:10
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@wangxingfred

**Closed as completed by drelaptop** 2018-05-23 06:10 UTC
