### ISSUE TITLE
new android project crash in android 5.0.2 device (Nexus 7) when use 3.12

### ISSUE THREAD

**Issue by boyjunqiang** [cocos2d/cocos2d-x#16169] opened 2016-07-20 08:13 UTC
This is the process to see this bug:

```
1. cocos new test_project -p com.test.test -l cpp
2. cd test_project
3. python /Users/jun/Code/cocos2d-x-3.12/tools/cocos2d-console/bin/cocos.py  compile -p android --android-studio --ap android-15 --ndk-mode release --mode release  --output-dir .
4. adb install test_project-release-signed.apk
```

When run this test app in android 5.0.2 device (Nexus 7) , it will crash!  but in android 4.4 and android 6.0, it was no problem.

The ndk version is r11c

**Comment by minggo** [comment] 2016-07-21 05:56
Is there any crash log?

**Comment by phutc** [comment] 2016-07-21 06:48
Me too, i'm using android 5.0

**Comment by Bilalmirza** [comment] 2016-07-21 08:14
i have the same crash on multiple devices

**Comment by minggo** [comment] 2016-07-21 08:18
@phutc @Bilalmirza what's the devices you tested on?

**Comment by phutc** [comment] 2016-07-21 09:00
@minggo I tested on Sony Eperia M4 Android 5.0, Please help me. Thanks you !

**Comment by minggo** [comment] 2016-07-21 10:18
@dumganhar please take a look

**Comment by Bilalmirza** [comment] 2016-07-21 11:43
Crash on Samsung S5 android v5.0

Works fine on HTC One M9 android v5.0.2
LG G3 android v 4.4.2
Nexus 4 androidv 4.4

I'll test on more devices and report.
Thanks

**Comment by Bilalmirza** [comment] 2016-07-21 11:51
Crashes on    S4 android v 5.0.1

Does NOT crash on s3 android v4.3
S6 edge plus v6.0.1

**Comment by cmzx3444** [comment] 2016-07-21 12:08
It's better to test on platform like http://testin.cn/

**Comment by alfogrillo** [comment] 2016-07-21 12:38
Crash on Samsung Galaxy S4 with Android 5.0.1
See here for details (and crash dump):
http://discuss.cocos2d-x.org/t/cocos2d-x-3-12-crash-on-android-when-game-starts/30889

The HelloWorld project crashes on the line
`auto sprite = Sprite::create("HelloWorld.png");`
If the `sprite`code is commented, the project works for me.

**Comment by dumganhar** [comment] 2016-07-22 03:23
@cmzx3444, yep, I will submit a test task at `testin` today. 

@Drakon-Cocos , the crash stack looks really strange, it crashed at AAssetManager_open.
Currently, no idea about that. 

Could you guys also test `cpp-empty-test` on the previous version (v3.11.1)?

**Comment by alfogrillo** [comment] 2016-07-22 06:47
@dumganhar
I tested `cpp-empty-test` with Android 5.0.1 and v3.11.1.
It works correctly, no crash.

**Comment by rh101** [comment] 2016-07-22 06:55
My game worked fine on Android 5.0.2 when built with 3.11.1, yet as soon as I moved it to 3.12, it crashes on open, and the call stack doesn't make sense at all within the context of what is going on within my game.

cpp-empty-test on 3.11.1 works fine on Android 5.0.2. 
cpp-empty-test on 3.12 crashes on Android 5.0.2.
cpp-empty-test on 3.12 with all references to cocos2d::Label commented out in HelloWorldScene.cpp does NOT crash on Android 5.0.2:

```
//auto label = Label::createWithTTF("Hello World", "fonts/arial.ttf", TITLE_FONT_SIZE);
//label->setPosition(origin.x + visibleSize.width/2,
//                        origin.y + visibleSize.height - label->getContentSize().height);
//this->addChild(label, 1);
```

I hope this helps in some way to narrow it down.

**Comment by dumganhar** [comment] 2016-07-22 07:05
@Drakon-Cocos ,@rh101
Could you please apply this patch (https://github.com/cocos2d/cocos2d-x/pull/16101) and test it again on your device which crashed in cpp-empty-test?

**Comment by dumganhar** [comment] 2016-07-22 07:13
@rh101 , good finding. So it maybe some issues related to Label.

**Comment by rh101** [comment] 2016-07-22 07:56
> @Drakon-Cocos ,@rh101
> Could you please apply this patch (#16101) and test it again on your device which crashed in cpp-empty-test?

The specific line in bool GLProgram::updateUniformLocation in v3.12 is the same as the patch you linked, so I'm not sure what it is you want me to test (the rest of the code in that method is different though, since you've linked v2 of the Cocos2d codebase).

**Comment by dumganhar** [comment] 2016-07-22 08:39
@rh101 , but the patch is merged recently. It's not in v3.12.
Please see the change:
<img width="702" alt="screen shot 2016-07-22 at 16 35 27" src="https://cloud.githubusercontent.com/assets/493372/17051277/6cb922a0-502a-11e6-9089-5c2bd3b43480.png">

**Comment by rh101** [comment] 2016-07-22 09:15
@dumganhar , I patched the code, but no luck, it still crashes if it contains any cocos2d::Label.

**Comment by dumganhar** [comment] 2016-07-22 09:37
Could you try to use `android-ndk-r12b` to test?
Please add `--app-abi=armeabi` to `cocos` command otherwise it will trigger errors while compiling.

**Comment by dumganhar** [comment] 2016-07-22 09:52
Also, please try with `--app-abi=armeabi-v7a` to test.

**Comment by dumganhar** [comment] 2016-07-22 09:56
Could you also help to test by modifying the stl configuration in Application.mk?

```
APP_STL := gnustl_static
```

to

```
APP_STL := c++_static
```

Please give us feedback after you test. thanks.

**Comment by Bilalmirza** [comment] 2016-07-22 10:01
it doesnt crash with --app-abi=armeabi-v7a

**Comment by rh101** [comment] 2016-07-22 10:07
@dumganhar , using android-ndk-r12b and --app-abi=armeabi did not work, since it still gave compilation errors (the same error for many files):

error: relocation overflow in R_ARM_THM_CALL

Using --app-abi=armeabi-v7a with android-ndk-r12b compiles fine, the application does not crash, and the label is displayed fine on the screen.

I tested it with with crystax-ndk-10.3.1 as well, which is what I use for my projects since it supports certain c++ items that are not available in the standard SDK, but unfortunately it crashes with that.  I haven't tried the --app-abi=armeabi-v7a switch with it though, so I'll give that a go as well.

**Comment by zilongshanren** [comment] 2016-07-22 10:29
@Bilalmirza  @rh101  Change `APP_STL := gnustl_static` to `APP_STL := c++_staic` in  `Application.mk` could solve the problem.

**Comment by rh101** [comment] 2016-07-22 11:06
@zilongshanren , the only thing that prevents the crash from happening is using --app-abi=armeabi-v7a in the compile command.  APP_STL := c++_static had no real effect on it, and still has a compilation issue with --app-abi=armeabi, being "error: relocation overflow in R_ARM_THM_CALL".

The problem now is that the compiled application will be incompatible with ARMv5 & v6 devices.

**Comment by alfogrillo** [comment] 2016-07-22 19:49
Also for me cpp-empty-test does not crash with:
`--app-abi=armeabi-v7a`

**Comment by zilongshanren** [comment] 2016-07-23 01:38
@rh101  For NDK r12b, you must use `--app-abi=armeabi-v7a`, but with the NDK version below r12, you could compile with `armeabi`. And now the `APP_STL := c++_staic` option indeed solve the problem.

**Comment by rh101** [comment] 2016-07-23 02:33
@zilongshanren , you're right about NDK12b and --app-abi=armeabi-v7a, but for anything below r12 (including crystax-ndk-10.3.1) I'm still getting compilation errors when using APP_STL := c++_static and --app-abi=armeabi.  I'll test it out a bit more.  

What works:
cocos2d 3.12, crystax-ndk-10.3.1, --app-abi=armeabi-v7a and APP_STL := c++_static
cocos2d 3.12, ndk-11c, --app-abi=armeabi-v7a and APP_STL := c++_static
cocos2d 3.12, ndk-12b, --app-abi=armeabi-v7a and APP_STL := c++_static

What doesn't work:
cocos2d 3.12, crystax-ndk-10.3.1, --app-abi=armeabi and APP_STL := c++_static (app crashes on loading)
cocos2d 3.12, ndk-11c, --app-abi=armeabi and APP_STL := c++_static (app crashes on loading)

**Comment by alfogrillo** [comment] 2016-07-23 07:45
@zilongshanren 
For me the `cpp_empty_test` works with `APP_STL := c++_static` and Android NDK 11c without `--app-abi=armeabi-v7a`.
Anyway I get this Android NDK warning:
`LOCAL_LDLIBS is always ignored for static libraries`

**Comment by ricardoquesada** [comment] 2016-07-26 01:05
@minggo @zilongshanren @dumganhar 
could we try to identify the commit that broke it? Perhaps by doing `git bisect` ?
it is important to try to identify the commit that broke it so that we learn from it, and we can fix it.

**Comment by dumganhar** [comment] 2016-07-26 01:43
@ricardoquesada , I use `git bisect` to find out which commit broke it yesterday.
The result is: 

```
3fb45f28f59709f1d7e95025ec07f3aca5e2ba5b  good
e11f261dc89f64ca1eed4d8dce4aa7ad6328a0a4  bad
a9b811fee48ef46819f972d8cc0628fa01b16119  bad
7a6664ab1fb9892f089ba0a460cb02f02d2081e1  bad
8e883f9956bc528b6aa0a9076e23273748479e98  good
81842417c47d014d40b9d9f7d4b087679bc706e1  good
a46c4be91208e8b4ced5a36b5d53a905e214a9fd  good
c4112e1ce50ba754cc83156bf81c5b3c70888fb1  bad
9edd66d4a7e1b395a3ffba27e1b086d41233fe02  bad

9edd66d4a7e1b395a3ffba27e1b086d41233fe02 is the first bad commit
commit 9edd66d4a7e1b395a3ffba27e1b086d41233fe02
Author: WenhaiLin <wenhai.lin@chukong-inc.com>
Date:   Tue Jul 28 16:28:32 2015 +0800

    Label:support font that contains GB2312 char map.

:040000 040000 133f0b1211cd2c8727faf4085512a4ad1f4d889b 337c9f1225d9a4a2a10b2e0cf7c3c922048bf11d M  cocos
```

It means that this Pull Request (https://github.com/cocos2d/cocos2d-x/pull/13076) broke it.
But I still can't get the reason. :(

Anyway, I'll try to catch it today.

**Comment by dumganhar** [comment] 2016-07-26 02:50
FIXED: https://github.com/cocos2d/cocos2d-x/pull/16214

@boyjunqiang, @Bilalmirza, @rh101, @Drakon-Cocos, @phutc 
Please test.

@ricardoquesada , @minggo , @zilongshanren ,

Any thoughts,  why is the assignment operator of `std::u16string` broken? This Pull Request did fix the problem. But I still don't know the reason.

**Comment by dumganhar** [comment] 2016-07-26 03:52
All my tests are based on debug mode. And after applying my patch, every thing works perfectly.

But there seems to be some different in release mode... I mean it seems to continue crash in release mode. :( And the crash place is different, I commented all nodes in HelloWorldLayer. Still crash got.

**Comment by mtak-** [comment] 2016-07-26 05:40
It definitely sounds like an ABI issue.

I wonder if it is related to this bug: https://github.com/android-ndk/ndk/issues/151

**Comment by minggo** [comment] 2016-07-26 06:12
@mtak- i don't think it is related with https://github.com/android-ndk/ndk/issues/151 because it is not crash if building with armeabi-v7a.

@dumganhar i have not idea why it can fix the issue. I wonder if we should move back to use gcc until c++_static is stable.

**Comment by alfogrillo** [comment] 2016-07-26 07:57
@dumganhar 
Fix #16214 worked.
I created a new project, applied the patch, compiled with:
`cocos run -p android --android-studio`
And it worked! :-)

**Comment by dumganhar** [comment] 2016-07-26 08:15
@Drakon-Cocos, thanks for testing.
Yep, it did work in **debug** mode, but it's broken in **release** mode. :(

**Comment by dumganhar** [comment] 2016-07-26 09:15
This is the result in `git bisect` release mode:

```
git bisect start
# good: [76c89c939831ed2fb177a9aa4a915aca73196ef6] Merge pull request #13331 from minggo/v3.7.1
git bisect good 76c89c939831ed2fb177a9aa4a915aca73196ef6
# bad: [1e415a0b5ba1b65e5809651e014f08195e6f7cea] Merge pull request #13364 from WenhaiLin/v3-Scheduler-eloopfix
git bisect bad 1e415a0b5ba1b65e5809651e014f08195e6f7cea
# good: [3fb45f28f59709f1d7e95025ec07f3aca5e2ba5b] Merge pull request #13033 from CocosRobot/update_cocosfiles_1437975533
git bisect good 3fb45f28f59709f1d7e95025ec07f3aca5e2ba5b
# bad: [e11f261dc89f64ca1eed4d8dce4aa7ad6328a0a4] Merge pull request #13168 from CocosRobot/update_lua_bindings_1438578238
git bisect bad e11f261dc89f64ca1eed4d8dce4aa7ad6328a0a4
# bad: [a9b811fee48ef46819f972d8cc0628fa01b16119] [ci skip][AUTO]: updating luabinding & jsbinding automatically
git bisect bad a9b811fee48ef46819f972d8cc0628fa01b16119
# bad: [7a6664ab1fb9892f089ba0a460cb02f02d2081e1] [ci skip][AUTO]: updating luabinding & jsbinding automatically
git bisect bad 7a6664ab1fb9892f089ba0a460cb02f02d2081e1
# good: [8e883f9956bc528b6aa0a9076e23273748479e98] Merge pull request #13049 from jianglong0156/constructedWith3D#12404
git bisect good 8e883f9956bc528b6aa0a9076e23273748479e98
# good: [81842417c47d014d40b9d9f7d4b087679bc706e1] Merge pull request #13032 from xiaofeng11/v3
git bisect good 81842417c47d014d40b9d9f7d4b087679bc706e1
# good: [a46c4be91208e8b4ced5a36b5d53a905e214a9fd] Merge pull request #13039 from WenhaiLin/v3.8-audioengine-preload
git bisect good a46c4be91208e8b4ced5a36b5d53a905e214a9fd
# bad: [c4112e1ce50ba754cc83156bf81c5b3c70888fb1] Merge branch 'v3' of https://github.com/cocos2d/cocos2d-x into v3.8-label-gb2312
git bisect bad c4112e1ce50ba754cc83156bf81c5b3c70888fb1

Bisecting: 0 revisions left to test after this (roughly 0 steps)
[9edd66d4a7e1b395a3ffba27e1b086d41233fe02] Label:support font that contains GB2312 char map.

```

It seems that it's the same commit made the broken.

**Comment by dumganhar** [comment] 2016-07-26 09:21
@Drakon-Cocos,  did that patch work for you while building game in  release mode?

**Comment by rh101** [comment] 2016-07-26 10:56
@dumganhar, after fix #16214, debug and release version do not crash when building for armeabi with gnustl_static.

Edit: NDK = crystax-ndk-10.3.1

**Comment by alfogrillo** [comment] 2016-07-26 11:15
@dumganhar 
As @rh101  for me the patch works both in debug and release mode (armeabi, gnustl_static)

**Comment by dumganhar** [comment] 2016-07-26 15:50
@rh101 @Drakon-Cocos , thanks for testing.
It seems that my patch did resolve the problem.
But the latest code on v3 branch broke it again in release mode.
This is the `git bisect` result:

```
git bisect start
# good: [9edd66d4a7e1b395a3ffba27e1b086d41233fe02] Label:support font that contains GB2312 char map.
git bisect good 9edd66d4a7e1b395a3ffba27e1b086d41233fe02
# bad: [81ecc529f1a9dbc83db590f119fff09d971ccf8d] fixed #16169: Adds comments for why we should not use `assignment operator` of `std::u16string`.
git bisect bad 81ecc529f1a9dbc83db590f119fff09d971ccf8d
# good: [a804c67a12bf08e1ee121207ef9b98949d8152ca] Merge branch 'v3' of https://github.com/cocos2d/cocos2d-x into v3_combine_2d
git bisect good a804c67a12bf08e1ee121207ef9b98949d8152ca
# good: [a804c67a12bf08e1ee121207ef9b98949d8152ca] Merge branch 'v3' of https://github.com/cocos2d/cocos2d-x into v3_combine_2d
git bisect good a804c67a12bf08e1ee121207ef9b98949d8152ca
# good: [4bee2c4e791f1b721eafabb496446cd4974a5a44] Merge pull request #15361 from stevetranby/iterator-erase
git bisect good 4bee2c4e791f1b721eafabb496446cd4974a5a44
# good: [103bdb3d378554260e8324ac633b5c1fa1d30357] fix conflict
git bisect good 103bdb3d378554260e8324ac633b5c1fa1d30357
# good: [bbd837aefa17bb0a08722f1140119f8561a67f7d] merge v3.12 back to v3
git bisect good bbd837aefa17bb0a08722f1140119f8561a67f7d
# bad: [d4bd1d0c9afd0b5ef617ef78b4c65db62f2974f4] fix conflict
git bisect bad d4bd1d0c9afd0b5ef617ef78b4c65db62f2974f4
# good: [0b222da93e5e4aed268f8316d7046de1a7031e50] Merge pull request #16041 from mogemimi/fix-various-typos
git bisect good 0b222da93e5e4aed268f8316d7046de1a7031e50
# good: [e632f99d4803a4e19c08727be0506ec7165ce366] Merge pull request #16052 from pandamicro/v3.12
git bisect good e632f99d4803a4e19c08727be0506ec7165ce366
# good: [836acff6d0a5bdeb8ecc80ad7b865dd7207dd59d] Merge pull request #16060 from minggo/merge-v312
git bisect good 836acff6d0a5bdeb8ecc80ad7b865dd7207dd59d
# good: [9f2f794cac2dad6f5325566ac07e03fc7aa7c07e] Merge pull request #16065 from mogemimi/fix-readme-and-other-docs
git bisect good 9f2f794cac2dad6f5325566ac07e03fc7aa7c07e
# bad: [c267167d07bfb93b12e21d6b90d170a085fe832e] Merge pull request #16069 from minggo/ndkr12b-issue
git bisect bad c267167d07bfb93b12e21d6b90d170a085fe832e
# good: [8d8c295ff047832cff657e18d9632d5429907ebb] Merge pull request #16062 from minggo/fileutils-issue
git bisect good 8d8c295ff047832cff657e18d9632d5429907ebb
# bad: [a1440069319541f5f97290d743850f15ebcaae34] use arm mode
git bisect bad a1440069319541f5f97290d743850f15ebcaae34
# bad: [4e125d84a44650e65f837697a65ebe12acb9882f] fix compiling and linking error with ndk r12b
git bisect bad 4e125d84a44650e65f837697a65ebe12acb9882f
# first bad commit: [4e125d84a44650e65f837697a65ebe12acb9882f] fix compiling and linking error with ndk r12b
```

@minggo , this commit was submitted by you. Any ideas about why it broke again?

**Comment by minggo** [comment] 2016-07-27 01:47
@dumganhar it is to fix the link error `error: relocation overflow in R_ARM_THM_CALL`. Can refer to #16033 for detail information.

**Comment by dumganhar** [comment] 2016-07-27 02:23
The result report:

| compiler | stl library | build mode | apply PR #16069 (James) | apply PR #16214 (Minggo) | result |
| --- | --- | --- | --- | --- | --- |
| clang | gnustl_static | release | no | yes | crash while launch |
| clang | gnustl_static | release | yes | yes | crash while launch |
| clang | gnustl_static | release | yes | no | ok |
| clang | gnustl_static | release | no | no | crash while rendering Label |
| clang | gnustl_static | debug | yes | yes | ok |
| clang | gnustl_static | debug | no | yes | crash while rendering Label |

The table only shows the situations of `clang` compiler with `gnustl_static` library.
Other cases of matching compiler with stl library (gcc + gnustl_static or clang + c++_static) will work perfectly.

Consequently, it's reasonable to continue to use `gcc + gnustl_static` until google removes it from NDK or until google says `c++_static` is stable for use.

Any thoughts, everybody?

**Comment by minggo** [comment] 2016-07-27 02:35
@dumganhar yep, i agree with you that we should switch to gcc + gnul_static. @ricardoquesada what's your opinion?

**Comment by ricardoquesada** [comment] 2016-07-27 03:24
@minggo @dumganhar agreed.
Yes, let's keep using it. it would be great if we can create a small tests that reproduces this crash (without cocos, just one .cpp) and submit it to google.

**Comment by dumganhar** [comment] 2016-07-28 02:09
@ricardoquesada , ok, I'll try to reproduce it with a simple demo.
Hopefully, it could be reproduced.

**Closed as completed** 2016-07-28 03:19 UTC
Labels: type:bug, critical, platform:android

**Comment by tungnt11** [comment] 2016-11-02 08:53
Hi @dumganhar , I fixed as https://github.com/cocos2d/cocos2d-x/commit/66fac82f007514e9ec4021515e325c49d129a45b but my app still crash in Android 5.0.
Both NDK: r10e and r11c are crashes. 
My device:  Sony Eperia M4 Android 5.0.
If i edit Application.mk: APP_ABI := armeabi-v7a, app doesn't crash but armeabi-v7a Incompatible with ARMv5, v6 devices. 
Help me. Thanks!

**Comment by dumganhar** [comment] 2016-11-02 08:56
@dimaria11, Could you try to use gcc4.9 to build project instead of clang.

**Comment by tungnt11** [comment] 2016-11-02 09:24
@dumganhar , what can i config to switch "clang" to "gcc4.9"  in my project?

**Comment by dumganhar** [comment] 2016-11-02 09:26
Look for `get_toolchain_version` function in tools/cocos2d-console/plugins/plugin_compile/build_android.py, return '4.9' like this:

```
    def get_toolchain_version(self, ndk_root, compile_obj):
        return '4.9'
```

**Comment by tungnt11** [comment] 2016-11-02 10:09
Ok @dumganhar , thanks very much. My problem was resolved!
