### ISSUE TITLE
glReadPixels crash after VideoPlayer:stop ios 13

### ISSUE THREAD

**Issue by semgilo** [cocos2d/cocos2d-x#20270] opened 2019-10-30 06:41 UTC
- cocos2d-x version:3.17
- devices test on:iphone xr ios13.1

I upgraded VideoPlayer-ios from v3 for fixxing the issue crashed in ios13.

Steps to Reproduce:

1. Play a mp4 by VideoPlayer and stop it.
2. Call glReadPixels
log:
`_validateGetBytes:29: failed assertion 'CPU access for textures with MTLResourceStorageModePrivate storage mode is disallowed.'`

**Comment by minggo** [comment] 2019-10-30 08:26
Why has `MTLResourceStorageModePrivate`, v3 doesn't use metal.

**Comment by minggo** [comment] 2019-10-30 08:37
@semgilo could you please provide some codes to reproduce it?

**Comment by minggo** [comment] 2019-10-30 09:01
May be i know the reason. VideoPlayer adds a `AVPlayerController.view` as its subview. So when you use VideoPlayer, it has two views now:
- one is UIView, engine renders contents into it
- another one is `AVPlayerController.view`, which is used to play video

And i think `AVPlayerController.view` uses metal to renderer the video. That's why the error log includes `MTLResourceStorageModePrivate`. `glReadPixels` wants to access the video content, so it has problem.

When using VideoPlayer, AVPlayerController.view will be added. Why you want to read pixels when VideoPlayer exists? Did you want to capture the screen including the contents of the Video? If not, i think you can remove VideoPlayer before using glReadPixels.

There is another option is that, `VideoPlayer::stop()` removes the subview. Then the video content will disappear, the effect will be different from previous.

**Comment by minggo** [comment] 2019-10-30 09:06
> There is another option is that, VideoPlayer::stop() removes the subview. Then the video content will disappear, the effect will be different from previous.

It is not a good idea, because:
- read pixels after pausing the video will crash
- read pixels when playing the video will crash

And we can not remove subview in these situations.

**Comment by semgilo** [comment] 2019-10-30 14:06
Thanks for reply, I used glReadpixels after VideoPlayer:stop, it had disappeared yet.
I will make sure VideoPlayer  removed tomorrow and use it again.

**Comment by semgilo** [comment] 2019-11-01 06:26
@minggo I made sure videoplayer stopped and cleaned by Xcode debug, and it crashed after glReadPixels.  
<img width="770" alt="Screenshot 2019-11-01 at 14 23 37" src="https://user-images.githubusercontent.com/7121873/68006470-98896f00-fcb3-11e9-911d-305adaa16a2f.png">

**Comment by minggo** [comment] 2019-11-04 02:03
Is it the same log? Could you please provide a test case?

**Comment by semgilo** [comment] 2019-11-04 02:29
Yes, I didn't do anything, I just made sure it called after VideoPlayer had stopped.  I try to provide later.

**Comment by semgilo** [comment] 2019-11-04 08:17
@minggo 

```c++
 // 1.Create a new project using v3 branch.
 // 2.Play a mp4 video using VideoPlayer

   _vp = VideoPlayer::create();
    _vp->setPosition(Vec2(visibleSize.width/2 + origin.x, visibleSize.height/2 + origin.y));
    _vp->setContentSize(Size(300, 180));
    _vp->setFileName(FileUtils::getInstance()->fullPathForFilename("res/openvideo.mp4"));
    _vp->setKeepAspectRatioEnabled(true);
//    vp->setFullScreenEnabled();
    _vp->setFullScreenEnabled(false);
    _vp->setFullScreenEnabled(false);
    _vp->play();

// 3.Stop video 

 _vp->stop();

// 4.Call glReadPixels
       auto glView = Director::getInstance()->getOpenGLView();
        auto frameSize = glView->getFrameSize();
        int width = static_cast<int>(frameSize.width);
        int height = static_cast<int>(frameSize.height);
        std::shared_ptr<GLubyte> buffer(new GLubyte[width * height * 4], [](GLubyte* p){ CC_SAFE_DELETE_ARRAY(p); });
        if (!buffer)
        {
            return;
        }
        glPixelStorei(GL_PACK_ALIGNMENT, 1);
        glReadPixels(0, 0, width, height, GL_RGBA, GL_UNSIGNED_BYTE, buffer.get());
```

**Comment by semgilo** [comment] 2019-11-06 02:36
@minggo Has the issue progressed?

**Comment by minggo** [comment] 2019-11-06 06:26
Sorry, i am busy with other things. I will take a look ASAP.

**Comment by minggo** [comment] 2019-11-06 06:58
@semgilo as i said you should remove the video player. `_vp->stop()` doesn't remove it. The video player's view is released in its destructor, not in `stop()`.

**Comment by semgilo** [comment] 2019-11-06 07:39
@minggo I had remove it by removeFromParent() yet.
<img width="697" alt="Screenshot 2019-11-06 at 15 37 38" src="https://user-images.githubusercontent.com/7121873/68278098-a1ab7f00-00ab-11ea-87a7-dfb8df179962.png">

**Comment by semgilo** [comment] 2019-11-06 07:41
https://discuss.cocos2d-x.org/t/utils-capturescreen-failed-assertion-on-ios-13-1-3/48140 Another people got it.

**Comment by minggo** [comment] 2019-11-06 07:59
But your demo doesn't remove it, and if i add `_demo->release()`, `glReadPixels` will not crash, it will crash at `release()` as it is an autorelease object.

**Comment by semgilo** [comment] 2019-11-06 08:22
"_demo"  means  videoplayer?

**Comment by minggo** [comment] 2019-11-06 08:24
Yep, it is `_vp`. Sorry for the mistake.

**Comment by semgilo** [comment] 2019-11-06 09:26
I replaced _vp->stop() with _vp->removeFromParent() and the result didn't change. Is there a videoplayer lib can replace it? Our company want to submit it for reviewing ASAP. May be I remove glReadPixels reference is a good idea for now?

**Comment by minggo** [comment] 2019-11-06 10:03
I don't know how you invoke `removeFromParent `, it is not part of VideoPlayer. May be you change the engine codes, but i don't know how you did. So it is better you share a complete demo.

I don't know if there are any other component can replace it, but it will take times to adapt too. And it may also have problem. May be you can search if there is a 3rd library to do it.

**Comment by semgilo** [comment] 2019-11-06 10:19
I don't change any engine codes and 3rd libs, I created  new project from cocos2dx/v3, and changed HelloWorldScene which add a VideoPlayer, these is the code.
[helloworld.zip](https://github.com/cocos2d/cocos2d-x/files/3813861/helloworld.zip)

 I don't upload mp4 file, because it is too large.

**Comment by ghost** [comment] 2019-11-06 16:47
test mp4 https://ia800106.us.archive.org/25/items/archive-video-files/test.mp4

**Comment by minggo** [comment] 2019-11-07 02:15
Ok, i will use the demo to test.

**Comment by minggo** [comment] 2019-11-07 03:13
I can reproduce the issue. I have not idea how to fix it. I will continue to fix it.

**Comment by semgilo** [comment] 2019-11-07 06:40
@minggo  I found a setting about switching metal API, it works when I lauch app by Run.
<img width="810" alt="image" src="https://user-images.githubusercontent.com/7121873/68365769-89e7ff80-016c-11ea-9d8e-c14e3dd1d304.png">

**Comment by minggo** [comment] 2019-11-07 07:06
It just disables validation, but can you read the pixels?

**Comment by semgilo** [comment] 2019-11-07 07:08
It don't crash now, Only by Running.

**Comment by minggo** [comment] 2019-11-07 07:11
It is like that you comment `assert`, but the error still exists. You can check the data read to see if it is correct or not.

**Comment by semgilo** [comment] 2019-11-07 07:32
I could get shotscreen successfully, and the buffer wasn't "\0".

<img width="845" alt="image" src="https://user-images.githubusercontent.com/7121873/68368749-ab001e80-0173-11ea-977d-30456d4f6ca8.png">

**Comment by minggo** [comment] 2019-11-07 07:41
Sounds good. And i found if i use  presentViewController to play video like this:
```
[self presentViewController:playerViewController animated:YES completion:^{
  [playerViewController.player play];
}];
```
It will not crash. But using this method, then can not set the view position, and it is just a fullscreen presentation.

**Comment by minggo** [comment] 2019-11-07 08:04
My fault, it seems it will crash too.

**Comment by minggo** [comment] 2019-11-07 08:07
I found that, it only crashes if using Xcode to run the application. If you click the icon in iOS device to run the application, it will not crash. So i think it is a bug of Xcode?

**Closed as completed** 2019-11-26 02:57 UTC
