### ISSUE TITLE
(iOS) Crash after receive applicationDidReceiveMemoryWarning 

### ISSUE THREAD

**Issue by letrungtrung** [cocos2d/cocos2d-x#16719] opened 2016-10-18 14:12 UTC
The reason caused crash is "on applicationDidReceiveMemoryWarning  function exist code calling cocos2d::Director::getInstance()->purgeCachedData();"

Steps to Reproduce:
1. add texturePack with 3 sprite frames: A,B, C
2. create sprite with sprite-frame A, B
3. cocos2d::Director::getInstance()->purgeCachedData(); (simulate like function applicationDidReceiveMemoryWarning )
4. create sprite with sprite frame C
   ==> sprite frame C won't exist  ==> crash from "Assert Failed! spriteFrame can't be nullptr!"

**Comment by toreinkun** [comment] 2016-10-19 03:00
there is not a map to record A,B,C for a plist in memory, it will clear all sprite frames if it is not unused.
before using createSpriteFrame, you must to addSpriteFrames.

**Comment by letrungtrung** [comment] 2016-10-19 03:26
@panzhihao That is a sample to show you how to reproduce crash. 
According to you, if i have 100 spriteframes in pack, you need call 100 times to add spriteFramePack before use it?
Always start game, the user will create needed spriteframes to spriteframeCache, But on applicationDidReceiveMemoryWarning comes, how to control it to  re-create spriteframes? 

I think this is logic problem for releasing unused sprite frames. Engine need to check texture of spriteframe be refCount==1 to remove it

**Comment by dumganhar** [comment] 2016-10-19 03:39
@letrungtrung , which version of cocos2d-x are you using?
I tested it on v3 branch, it works without crash. This is my test code:

``` c++
    SpriteFrameCache::getInstance()->addSpriteFramesWithFile("fonts/ui.plist");

    auto a = Sprite::createWithSpriteFrameName("button_actived.png");
    auto b = Sprite::createWithSpriteFrameName("button_normal.png");

    a->setPosition(100, 100);
    a->setScale(10);
    addChild(a);
    b->setPosition(200, 200);
    b->setScale(10);
    addChild(b);

    Director::getInstance()->purgeCachedData();

    auto c = Sprite::createWithSpriteFrameName("coin.png");

    c->setPosition(300, 300);
    c->setScale(10);
    addChild(c);
```

**Comment by toreinkun** [comment] 2016-10-19 03:44
@dumganhar @letrungtrung new version use Texture2D::_ninePatchInfo to fix this.

**Comment by dumganhar** [comment] 2016-10-19 03:50
@panzhihao , i debugged it and found _ninePatchInfo was never used.
I set this break point in xcode to debug:
![screen shot 2016-10-19 at 11 49 29](https://cloud.githubusercontent.com/assets/493372/19505102/3f5e1118-95f2-11e6-80ad-634521757d8c.png)

**Comment by letrungtrung** [comment] 2016-10-19 04:09
@dumganhar I'm using version: 3.8 and 3.13
The problem caused crash is the unused SpriteFrames were removed after calling pureDataCache, and then you use spriteframe that removed.

**Comment by toreinkun** [comment] 2016-10-19 04:17
@dumganhar  Oh, i am wrong , the problem has not fixed.
`
cc.SpriteFrameCache:getInstance():addSpriteFrames("texture.plist");
    local a = cc.Sprite:createWithSpriteFrameName("a.png");
    self:addChild(a);
    a:setPosition(100, 100)

```
local scheduler = nil;
scheduler = cc.Director:getInstance():getScheduler():scheduleScriptFunc( function(dt)
    cc.Director:getInstance():getScheduler():unscheduleScriptEntry(scheduler);
    cc.Director:getInstance():purgeCachedData();

    local b = cc.Sprite:createWithSpriteFrameName("b.png");
    self:addChild(b);
    b:setPosition(500, 500)
end ,  0, false);
```

`

**Comment by dumganhar** [comment] 2016-10-19 05:58
@letrungtrung @panzhihao , I think it's not a bug. 
After you purgeCachedData, all SpriteFrames in SpriteFrameCache will be released.
It will be a new environment after purge. So you need to re-add the `plist` file to sprite frame cache before create a sprite from SpriteFrameCache.
For instance,

``` c++
    SpriteFrameCache::getInstance()->addSpriteFramesWithFile("fonts/ui.plist");

    auto a = Sprite::createWithSpriteFrameName("button_actived.png");
    auto b = Sprite::createWithSpriteFrameName("button_normal.png");

    a->setPosition(100, 100);
    a->setScale(10);
    addChild(a); 
    b->setPosition(200, 200);
    b->setScale(10);
    addChild(b);

    scheduleOnce([this](float dt){
        Director::getInstance()->purgeCachedData();

        SpriteFrameCache::getInstance()->addSpriteFramesWithFile("fonts/ui.plist"); // Add this line to re-add sprite frames to cache.

        auto c = Sprite::createWithSpriteFrameName("coin.png");

        c->setPosition(300, 300);
        c->setScale(10);
        addChild(c);
    }, 1.0f, "test");
```

**Comment by toreinkun** [comment] 2016-10-19 06:14
@dumganhar  I think so. The texture for plist still in the memory, so re-add the plist will not use long time.

**Comment by letrungtrung** [comment] 2016-10-19 07:36
@dumganhar 
- Your sample is perfect case, you active call  Director::getInstance()->purgeCachedData(); and you know you need to re-add spriteFrames. But in my case, this function was passive call (the low memory triggers anytime, anywhere), how to re-add spriteframes. Or you want to call add spriteframes before using a frame in them? 
- My solution is check texture of spriteframe before deciding it is unused spriteframe or no

``` c++
void SpriteFrameCache::removeUnusedSpriteFrames()
{
    bool removed = false;
    std::vector<std::string> toRemoveFrames;

    for (auto iter = _spriteFrames.begin(); iter != _spriteFrames.end(); ++iter)
    {
        SpriteFrame* spriteFrame = iter->second;
        if( spriteFrame->getReferenceCount() == 1  && spriteFrame->getTexture()->getReferenceCount() == 1) // code changed here
        {
            toRemoveFrames.push_back(iter->first);
            spriteFrame->getTexture()->removeSpriteFrameCapInset(spriteFrame);
            CCLOG("cocos2d: SpriteFrameCache: removing unused frame: %s", iter->first.c_str());
            removed = true;
        }
    }

    _spriteFrames.erase(toRemoveFrames);

    // FIXME:. Since we don't know the .plist file that originated the frame, we must remove all .plist from the cache
    if( removed )
    {
        _loadedFileNames->clear();
    }
}
```

**Comment by toreinkun** [comment] 2016-10-19 10:38
@letrungtrung  SpriteFrame will retain the texture, so the texture's referenceCount is 2.

**Comment by thangenius** [comment] 2016-10-20 02:37
The problem occurs in case we create 3 SpriteFrames from one Texture and only use 2 of them at the beginning of the game, the 3rd SpriteFrame is used sometimes later during the gameplay. Unfortunately, before the 3rd SpriteFrame is used, iOS device trigger memory warning event, SpriteFrameCache::removeUnusedFrameSprite() is called and it will remove the 3rd SpriteFrame, so the game will crash when the game need to use the 3rd SpriteFrame to init a Sprite.

If we have to check for existence of the 3rd SpriteFrame before using, I think it's a costly operation, especially during a realtime gameplay . Moreover, the 3rd SpriteFrame is only for example, in the real games, there will be a lot more SpriteFrames need to be pre-initialized.

**Comment by dumganhar** [comment] 2016-10-20 03:02
@thangenius ,

I don't know whether the hack of @letrungtrung 's is reasonable.

Could it be more reasonable while re-adding necessary sprite frames to cache after `Director::getInstance()->purgeCachedData();` in `applicationDidReceiveMemoryWarning`

I mean:

``` objective-c

- (void)applicationDidReceiveMemoryWarning:(UIApplication *)application {
    /*
     Free up as much memory as possible by purging cached data objects that can be recreated (or reloaded from disk) later.
     */
     cocos2d::Director::getInstance()->purgeCachedData();

    // Re-add sprite frames which are needed.
    SpriteFrameCache::getInstance()->addSpriteFramesWithFile("fonts/ui1.plist");
    SpriteFrameCache::getInstance()->addSpriteFramesWithFile("fonts/ui2.plist");
    // If you're using lua or jsb, you could bind a new method to script to addSpriteFrames in script.
}

```

**Comment by thangenius** [comment] 2016-10-20 03:12
@dumganhar the hack of @letrungtrung is not a good fix, it will not remove any spriteFrame and make the method removeUnsedSpriteFrame() useless. I have no idea right now, I workaround the crash by commenting the removeUnsedSpriteFrame() call in purgeCacheData() method. 

About your idea of re-adding sprite frames after purge, I'm not sure if there's a chance, in multi-threaded environment,  a sprite is initialized before the re-adding operations is called or not.

**Comment by toreinkun** [comment] 2016-10-20 05:01
@thangenius  I don't think it need to be fixed.  Before using Sprite::createWithSpriteFrameName,  we must     use SpriteFrameCache::addSpriteFramesWithFile. Because we can't sure the texture of plist if it is in memory, such as this case.
`
SpriteFrameCache::getInstance()->addSpriteFramesWithFile("fonts/ui.plist");

```
auto a = Sprite::createWithSpriteFrameName("button_actived.png");
auto b = Sprite::createWithSpriteFrameName("button_normal.png");

a->setPosition(100, 100);
a->setScale(10);
addChild(a); 
b->setPosition(200, 200);
b->setScale(10);
addChild(b);

scheduleOnce([this](float dt){
    a->removeFromParent();
    b->removeFromParent();
    Director::getInstance()->purgeCachedData();

    SpriteFrameCache::getInstance()->addSpriteFramesWithFile("fonts/ui.plist"); // Add this line to re-add sprite frames to cache.

    auto c = Sprite::createWithSpriteFrameName("coin.png");

    c->setPosition(300, 300);
    c->setScale(10);
    addChild(c);
}, 1.0f, "test");
```

`

We can optimize addSpriteFramesWithFile, but we can not use Sprite::createWithSpriteFrameName without it.

**Comment by dumganhar** [comment] 2016-10-20 06:18
Agree with @panzhihao , developers should ensure that sprite frames are added into cache before invoking `Sprite::createWithSpriteFrameName` .

`addSpriteFramesWithFile`  should be in high performance now since it checks whether sprite frames are in cache.

**Closed as completed** 2016-10-21 02:07 UTC
