### ISSUE TITLE
[Cocos2d-x 3.12] extensions::ControlSwitch::create() bug

### ISSUE THREAD

**Issue by alfogrillo** [cocos2d/cocos2d-x#16158] opened 2016-07-19 21:13 UTC
The function 
`ControlSwitch* create(Sprite *maskSprite, Sprite * onSprite, Sprite * offSprite, Sprite * thumbSprite)` makes the game to crash because calls `addChild` on `nullptr` object.
The function tries to add a null `Label` that user can specify using this other function:
`ControlSwitch* create(Sprite *maskSprite, Sprite * onSprite, Sprite * offSprite, Sprite * thumbSprite, Label* onLabel, Label* offLabel)`

**Comment by dumganhar** [comment] 2016-07-20 01:43
Does this issue appear from v3.12?

**Comment by minggo** [comment] 2016-07-20 06:33
@Drakon-Cocos how can i reproduce it?

**Comment by alfogrillo** [comment] 2016-07-20 07:47
@dumganhar : I don't know, it is the first time I use `extensions::ControlSwitch` class.
@minggo : here there is a simple test project (iOS tested).

[ControlSwitchTest.zip](https://github.com/cocos2d/cocos2d-x/files/373067/ControlSwitchTest.zip)

Anyway I think that `ControlSwitch::create` is not consistent with cocos2d-x style.
It should be something like that:
ControlSwitch\* create(const string& maskSprite, const string& onSprite, const string& offSprite, const string& thumbSprite)
Parameters of type`const string&` instead of `Sprite*`

**Comment by minggo** [comment] 2016-07-20 08:21
@Drakon-Cocos these features are added by cocosbuilder author to support cocosbuilder, and we port it in C++ to support cocosbuilder. It is not part of cocos2d-x core, it is a long time unmaintained.

**Comment by minggo** [comment] 2016-11-10 01:01
close this issue since the PR is merged, please reopen it if it still has the issue

**Closed as completed by minggo** 2016-11-10 01:01 UTC
