### ISSUE TITLE
OpenGL error 0x0502

### ISSUE THREAD

**Issue by waiter** [cocos2d/cocos2d-x#3217] opened 2013-07-23 02:10 UTC
In TestCpp , ClippingNodeTest, Hole Demo
then you will see this error
OpenGL error 0x0502 in d:\cocos2d-x-2.1.4\cocos2dx\sprite_nodes\ccsprite.cpp cocos2d::CCSprite::draw 591

I use win7 and cocos2d-x 2.1.4 in debug mode.
And cocos2d-x 2.1.3 also have this issue.
On Android, you will see:
E/Adreno200-ES20(29536): <__load_uniform_float:531>: GL_INVALID_OPERATION

Please HELP!

**Comment by minggo** [comment] 2013-07-23 04:44
It is fixed with latest codes in github.

**Comment by waiter** [comment] 2013-07-23 05:02
@minggo could you tell me more information? thank you.

**Comment by minggo** [comment] 2013-07-23 08:49
It is because `ControlSwitchSprite::needsLayout` will invoke `Sprite::setTexture` which changes gl program.
Then it will cause error when set uniform in `ControlSwitchSprite::draw()`.
Because `ControlSwitchSprite::draw()` doesn't check opengl error code, so the error happens in `Sprite::draw`.

Now we change the logic of `Sprite::setTexture`.

**Comment by minggo** [comment] 2013-07-23 09:24
@waiter 
I am sorry, i misunderstood the error.
What i said is another error.

**Comment by dabingnn** [comment] 2013-07-23 09:33
@waiter , I tested in two different android phones with the Hole Demo test, meizu MX2 and htc g14. 
The test ran with no error info log in meizu MX2, however in HTC G14, I confronted with the error!
E/Adreno200-ES20(29209): <__load_uniform_float:510>: GL_INVALID_OPERATION

It seems that different gles implementation has different shader capacity. We will confirm the reason why it happened!
Thanks for your proposal!

**Comment by dabingnn** [comment] 2013-07-23 09:42
@waiter , can you tell us what phone model your were using when you confronted the error？

**Comment by gelldur** [comment] 2013-07-23 10:22
PR on master it isn't fixed or i am wrong https://github.com/cocos2d/cocos2d-x/pull/3213

**Comment by gelldur** [comment] 2013-07-23 10:29
This also exist in CCControlSwitch example whole app works bad after it.

**Comment by waiter** [comment] 2013-07-23 12:19
@minggo Thank you for reply. I find this https://github.com/cocos2d/cocos2d-x/issues/3093 that is about CCControlSwitch. And I haven't try it.
@dabingnn Thank you for reply.My phone is LG LU6200. And on windows the error is:
OpenGL error 0x0502 in d:\cocos2d-x-2.1.4\cocos2dx\sprite_nodes\ccsprite.cpp cocos2d::CCSprite::draw 591
@gelldur Thank you for reply. I haven't try it.

**Comment by minggo** [comment] 2013-07-24 02:59
@gelldur
I think you are talking about another issue. 
Right?

If so, could you please create another thread?

@waiter
We have ask Qualcomm guys to help to checkout this issue.

**Comment by minggo** [comment] 2013-07-24 03:59
And there is an issue for it http://www.cocos2d-x.org/issues/2425.

**Comment by sosoayaen** [comment] 2013-07-25 08:44
I have wrote a GuidingLayer use CCClippingNode. As long as the GuidingLayer was existing in the Scene, whatever at Win32 or Android, debug output will warning error 0x0502 nonstop:
"07-25 16:37:37.805: D/cocos2d-x debug info(29307): OpenGL error 0x0502 in D:/work/cocos2dx/cocos2d-2.1rc0-x-2.1.3/projects/Demo/proj.android/../../../cocos2dx/sprite_nodes/CCSprite.cpp draw 589"
In WINDOWS: "OpenGL error 0x0502 in d:\work\cocos2dx\cocos2d-2.1rc0-x-2.1.3\cocos2dx\sprite_nodes\ccsprite.cpp cocos2d::CCSprite::draw 589"

My Device: SAMSUNG GALAXY 3

**Comment by dabingnn** [comment] 2013-08-09 03:20
@waiter @minggo I have found the reason by add some profile code, and  when we got the error message, I find that we are in an `GLProgram` object, that the `_program` member is 4, and the `gl program` object I got from `gl state machine` is 19. you can add some code in **CCGLProgram.cpp** behind line **glUniform1f( (GLint)location, f1);**.

And the reason is because the user used `GLProgram` wrongly. Normally we call `GLProgram::use()` and then `GLProgram::setUniformXXX()`. If we call `GLProgram::setUniformXXX()` directly, we are setting uniforms to an unknown `gl program`. Some errors may be raised by openGL.

Currently, our GLProgram designe is not flexible. We will make efforts to improve our GLProram design to make it more flexible. Thank you!

**Comment by dabingnn** [comment] 2013-08-09 03:23
I am sorry!  I forget to attach the snapshot.
![f5586c56-ed5a-481d-b649-121bd33ce7ee](https://f.cloud.github.com/assets/4794489/936193/1a0f694e-00a3-11e3-8bfc-477a97bf60c3.png)

**Comment by godyZ** [comment] 2013-08-19 07:29
@waiter Please, could you open a bug in redmine in future? We are in process of migrating all the issues to redmine and github issue won't be available after August. The issue is migrated to http://www.cocos2d-x.org/issues/2565

**Closed as completed** 2013-08-19 07:49 UTC
