### ISSUE TITLE
New audio engine - Bug

### ISSUE THREAD

**Issue by elr0nd** [cocos2d/cocos2d-x#9852] opened 2015-01-07 14:24 UTC
Using cocos2d-x v3.3 and NDK-r10d(64bits) when sound effects are played several times, Android's logcat shows the following error "243 message:create player for 'sound file name here' fail" and no more sounds are played anymore...

For Android, this error is thrown in the file "AudioEngine-inl.cpp" in the number line 243.

Thanks for your help.

**Comment by WenhaiLin** [comment] 2015-01-21 09:31
@elr0nd I can't reproduce this issue. Do you know how to reproduce this issue easier ?

Engine version: the latest code on github
Device to test: Nexus 9
Android version: 5.0

**Comment by elr0nd** [comment] 2015-01-21 10:43
Hi, i will try to do, in the next couple of days, an example project which produces this behaviour, ok?

Thanks for your time

**Comment by elr0nd** [comment] 2015-01-25 13:11
Hi @Dhilan007, I have created an example project which causes this bug, you can find it here: https://github.com/elr0nd/TestNewAudioEngine.

It has two buttons, one for background music and another for sound effects. If you click on the sound effects button, it launches a scheduler which plays a sound each 0.05 seconds, after some time (in my Galaxy S is about one minute), the bug shows in the android log cat.

It is my first time using github, so if you have any problem with it, just tell me.

Thank you!!

**Comment by WenhaiLin** [comment] 2015-01-26 01:46
@elr0nd Thanks,i will test it today.

**Comment by WenhaiLin** [comment] 2015-01-26 06:45
@elr0nd I test your example project  on nexus7,mx 3 and nexus 9,there is no error message as you say.It's work normal on mx3,but not getting any volume on nexus7.   

I then replace the count-points.ogg file with the other mp3 file,it's work normal on all devices.

**Comment by WenhaiLin** [comment] 2015-01-26 06:59
@elr0nd I converts the count-points.ogg file to mp3 format and test again, it work noamal on all devices. I think this issue have a direct relationship with device.

**Comment by elr0nd** [comment] 2015-01-26 07:27
Yes, I think the same, it depends on the device as you have checked... but it is strange, it happens in my three devices... let it go and I will continue testing. @Dhilan007, do you recommend the use of mp3 above ogg?

**Comment by WenhaiLin** [comment] 2015-01-26 07:34
@elr0nd I think it's need test on more devices,but i only have a few devices.

**Comment by WenhaiLin** [comment] 2015-01-26 07:39
@elr0nd I test again with other ogg file from cpp-tests, it's work normal on all my devices.

**Comment by FlagellumDei** [comment] 2015-02-15 06:32
Samsung Galaxy Tab 2 has this bug.

**Comment by zilongshanren** [comment] 2015-08-18 04:04
can't reproduce, so I just close it here. If anyone have this issue again, feel free to reopen it .

**Closed as completed by zilongshanren** 2015-08-18 04:04 UTC
