### ISSUE TITLE
Bug for convert std::string between C++ and Lua, the binaray string will be cut off.

### ISSUE THREAD

**Issue by youlanhai** [cocos2d/cocos2d-x#14738] opened 2015-12-19 04:08 UTC
**BUG**
`tolua_pushcppstring` just convert the `str.c_str()` to function `lua_pushstring`,  and the `lua_pushstring` use function `strlen` to get the length of the string. Consider that the `str` is a binary string and contains '\0', the whole string will be cut off during the conversion. The behaviour of `tolua_tocppstring` is same as `tolua_pushcpptring`.

**SOLUTION**
Modify `tools/bindings-generator/targets/lua/conversions.yaml`, use function `stdstring_to_luaval` to replace `tolua_pushcpptring`.
 Function `luaval_to_std_string` should use `lua_tolstring` to do conversion , and `stdstring_to_luaval` should use  `lua_pushlstring` to do conversion.

**Comment by minggo** [comment] 2016-08-05 10:07
@youlanhai how to reproduce it?

**Comment by youlanhai** [comment] 2016-08-16 09:27
@minggo 
我英语不好，中文解释吧：

## 举个简单的例子：

``` lua
local name = "ab\0cd"
local node = cc.Node:create()
node:setName(name)
print(#name, #(node:getName())) --输出：5 2
assert(node:getName() == name) --结果不相等，这个assert会被触发。
```

C++跟lua交互的过程中，字符串中从'\0'以后的数据会被丢弃掉。原因我在楼顶已经解释过了。
当然，我们通常不会这么去使用setName，但是不排除有极少数的API会存在二进制格式的数据交互。

## 类似的情况：

在cocos2d-x中有一个给lua用的http类`LuaMinXmlHttpRequest`，这个类是手动导出到lua的，且使用了`lua_pushlstring`和`lua_tolstring`来传递数据，所以没有数据截断的问题。
假设这个类是用`bindings-generator`导出到lua，它的方法`inline std::string getDataStr() { return _data; }`就会丢失数据，因为从服务器收到的数据很有可能是二进制的(比如使用了protobuf)，在传递到lua的过程中会从'\0'处被截断。

## 建议：

C++字符串与lua字符串转换的时候，不要忘了长度信息。在两者之间使用char*去转换，是非常危险的操作。

**Comment by minggo** [comment] 2017-02-06 08:30
@youlanhai can not fix this issue, because it is saved as `std::string` in Node. So even can get correct characters from lua, the characters after `\0` will be truncated.

**Comment by youlanhai** [comment] 2017-02-13 08:55
**Suggestion for tools `bindings-generator`**
Convert lua string to std::string should use API `lua_tolstring`, and convert std::string to lua string should use API `lua_pushlstring`. This two API will copy every characters in string(include '\0').

**Comment by minggo** [comment] 2017-02-13 09:05
@youlanhai i know you meaning, but after the string got from lua to c++, it is set to a string in Node too. For example,

1. use lua_tolstring get all characters(let's say it C) from lua
2. Node::setName(C)
3. though C includes all characters, but Node::setName() will truncate characters after `\0`

**Comment by youlanhai** [comment] 2017-02-13 09:58
@minggo  
The C++ std::string is different from C string(char*), only the C API `strxxx` will use '\0' as the terminal symbol. The std::string is safe when assign to another std::string variable, all characters will be copied(include '\0').

An example convert from binary lua string to std::string:
```c++
size_t length;   // store the length of lua string.
const char * data = lua_tolstring(L, -1, &length);
std::string name(data, length); // Now, the 'name' copy all characters(include '\0') from lua string.

node.setName(name); // This assignment is safe. The '\0' will be set to node.name if there exists.
assert(node.getName().length() == length); // This result should be equal.
```

And an example convert from binary std::string to lua string:
```c++
lua_pushlstring(L, str.c_str(), str.length());
```

**Comment by minggo** [comment] 2017-02-13 10:26
```c++
std::string s("ab\0cd");
std::cout << s << std::endl << s.length() << std::endl;
```
The output in Xcode is 
```
ab
2
Program ended with exit code: 0
```

**Comment by youlanhai** [comment] 2017-02-14 03:43
We shouldn't assign a binary `char*` value to std::string directly. It's better to use a buffer  pointer and buffer length to construct a std::string value.
```c++
std::string s("ab\0cd", 5); // Use buffer pointer and buffer length to construct a std::string.
for(size_t i = 0; i < s.length(); ++i)
    std::cout << s[i];
std::cout << std::endl << s.length() << std::endl;
```

The output in Xcode is: ('\0' is not visible on console)
```
abcd
5
```

In your code, `std::string s("ab\0cd");` is equivalent to:
```c++
const char * buffer = "ab\0cd";
std::string s(buffer, strlen(buffer));
``` 

The following is a simple implementation for std::string:
```c++
string
{
char *p;

string(const char *s)
{
  size_t length = strlen(s); // strlen is not friend for binary data.
  p = malloc(length + 1);
  memcpy(p, s, length);
  p[length] = '\0';
}

// binary data should use this constructor
string(const char *s, size_t length)
{
  p = malloc(length + 1);
  memcpy(p, s, length);
  p[length] = '\0';
}
}
```

**Comment by minggo** [comment] 2017-02-14 06:26
Yep, you are right. I will take a look at it.

**Comment by minggo** [comment] 2017-02-14 08:17
fixed in https://github.com/cocos2d/cocos2d-x/pull/17367

**Closed as completed** 2017-02-15 01:27 UTC
Labels: script:lua
