### ISSUE TITLE
Armature::create("xxx") too slow

### ISSUE THREAD

**Issue by chengstory** [cocos2d/cocos2d-x#10193] opened 2015-01-23 08:01 UTC
Armature::create("animation name") is too slow(1ms ~ 10ms), even if Developer have called ArmatureDataManager::getInstance()->addArmatureFileInfo(xxxx)

**Comment by joewan** [comment] 2015-01-24 01:57
we have suffered similar problems a lot.

**Comment by doomsdayer** [comment] 2015-01-29 10:02
@joewan, the key reason for this problem is found, in:

cocostudio::Armature::init
┗ cocostudio::Armature::createBone
    ┗cocostudio::Bone::setBoneData
        ┗cocos2d::Ref::release

When calling cocostudio::Armature::init for 1000 times, if we don't call the release function, cocostudio::Armature::init CPU time is reduced by more than 12s. (13588ms→1108ms).

I think it's not good that the engine release the texture once when create one armature.
The engine could add some parameter for the create function, for programers can manually  release all the texture at once.

**Comment by zhangzhibin** [comment] 2015-01-29 10:39
@doomsdayer, 
Could you pls elaborate your idea? 

I take a quick look at the code, but not sure where it is. 

Do you mean the cause is in below method:

void Bone::setBoneData(BoneData *boneData)
{
    CCASSERT(nullptr != boneData, "_boneData must not be nullptr");

```
if (_boneData != boneData)
{
    CC_SAFE_RETAIN(boneData);
    CC_SAFE_RELEASE(_boneData);   <------------------- this line ? 
    _boneData = boneData;
}

_name = _boneData->name;
_localZOrder = _boneData->zOrder;

_displayManager->initDisplayList(boneData);
```

}

**Comment by doomsdayer** [comment] 2015-01-29 10:51
@zhangzhibin  you are right.
You can delete this sentence, your program will have a better performance.

**Comment by minggo** [comment] 2016-06-30 02:33
since cocos studio is canceled, so close this issue

**Closed as completed by minggo** 2016-06-30 02:33 UTC
