### ISSUE TITLE
Call to unavailable function 'system': not available on iOS

### ISSUE THREAD

**Issue by maksg** [cocos2d/cocos2d-x#17907] opened 2017-06-07 15:18 UTC
cocos2d-x 3.15.1
Xcode 9 and iOS 11

In the newest Xcode this error shows up when compiling for iOS in platform/CCFileUtils.cpp, line 1429:
Call to unavailable function 'system': not available on iOS

**Comment by mars3142** [comment] 2017-06-07 20:07
It's in **FileUtils::removeDirectory(const std::string& path)** and the deprecation text for **system** is -> **Use posix_spawn APIs instead.**

**Comment by minggo** [comment] 2017-06-08 07:14
Xcode 9 is in beta version.

**Comment by minggo** [comment] 2017-06-08 07:18
> Use posix_spawn APIs instead.

@mars3142 could you please describe it in detail?

**Comment by mars3142** [comment] 2017-06-08 07:18
Right, but the **system** call is deprecated for iPhone since long time ago.

**Comment by mars3142** [comment] 2017-06-08 07:25
@minggo I only jumped into the definition of **system** in Xcode 9 (Beta with iOS 11), which is in stdlib.h

    __swift_unavailable_on("Use posix_spawn APIs or NSTask instead.", "Process spawning is unavailable")
    __API_AVAILABLE(macos(10.0)) __IOS_PROHIBITED
    __WATCHOS_PROHIBITED __TVOS_PROHIBITED
    int	 system(const char *) __DARWIN_ALIAS_C(system);

In Xcode 8 (iOS 10.12) showed nearly the same:

`__swift_unavailable_on("Use posix_spawn APIs or NSTask instead.", "Process spawning is unavailable")
__OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_0,__MAC_NA,__IPHONE_2_0,__IPHONE_8_0, "Use posix_spawn APIs instead.")
__WATCHOS_PROHIBITED __TVOS_PROHIBITED
int	 system(const char *) __DARWIN_ALIAS_C(system);`

This is what I see and that way I thought **posix_spawn** will be the solution.

**Comment by minggo** [comment] 2017-06-08 07:41
Ok, but i think we should use [nftw](http://pubs.opengroup.org/onlinepubs/009695399/functions/nftw.html) as mentioned in [the ticket](https://stackoverflow.com/questions/5467725/how-to-delete-a-directory-and-its-contents-in-posix-c).

**Comment by minggo** [comment] 2017-06-12 06:41
fixed in https://github.com/cocos2d/cocos2d-x/pull/17921

**Closed as completed** 2017-06-15 03:07 UTC
Labels: platform:ios

**Comment by erebar** [comment] 2018-07-04 21:45
I don't know why you say FIXED when it's NOT. I just downloaded v17 and the thing is still there.

**Comment by minggo** [comment] 2018-07-05 01:03
Why did you say it is not fixed? How did you test?

**Comment by erebar** [comment] 2018-07-05 23:30
I downloaded from here: http://cocos2d-x.org/download
And got that same "'system': not available on iOS"

**Comment by erebar** [comment] 2018-07-05 23:33
I downloaded v3.17 from here: http://cocos2d-x.org/download
And got that same "'system': not available on iOS" when I tried building a game that was using version v3.10 before.

**Comment by minggo** [comment] 2018-07-06 01:29
Can you reproduce it with `cpp-empty-test`? What device did you test on?

**Comment by slackmoehrle** [comment] 2018-07-06 19:40
@erebar can you post a picture, please.
