### ISSUE TITLE
iOS EditBox crashes if placeholder defined

### ISSUE THREAD

**Issue by gestern** [cocos2d/cocos2d-x#18125] opened 2017-08-04 01:19 UTC
- cocos2d-x version: cocos2d-x-3.15.1
- devices test on: iPhone 6, 7, 6+, 7+
- developing environments
   - Xcode version: 8.3.3

Steps to Reproduce:

1. Run cpp-test on any iOS device; 
2. Select "51: Node: UI" menu item then "GUI Dynamic Create Test" then "3. EditBox Test"
3. Push to 2nd text box with placeholder "Password":
4. Application will crashed on [CCUISingleLineTextField.mm:64](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/ui/UIEditBox/iOS/CCUISingleLineTextField.mm#L64)
```
- (void)drawPlaceholderInRect:(CGRect)rect {
	NSDictionary *attributes = @{
		NSForegroundColorAttributeName:_placeholderTextColor,
		NSFontAttributeName:_placeholderFont
	};
    
    // center vertically
    CGSize textSize = [self.placeholder sizeWithAttributes:attributes];
    CGFloat hdif = rect.size.height - textSize.height;
    hdif = MAX(0, hdif);
    rect.origin.y += ceil(hdif/2.0);

    [[self placeholder] drawInRect:rect withAttributes:attributes];
}
```

**Comment by minggo** [comment] 2017-08-07 07:43
fixed in https://github.com/cocos2d/cocos2d-x/pull/18132. It is not an issue of v3.15.1, just with v3 branch codes after v3.151. And the issue is caused by https://github.com/cocos2d/cocos2d-x/pull/17970 which is merged after v3.15.1.

**Closed as completed** 2017-08-07 09:00 UTC
