### ISSUE TITLE
socket.io 1.3.6 can't create custom namespace

### ISSUE THREAD

**Issue by man2** [cocos2d/cocos2d-x#13929] opened 2015-09-18 09:16 UTC
@himynameschris 
Tried with server code from 
https://github.com/himynameschris/socket.io-testserver

SocketIO::connect("http://localhost:3010/testpoint", *this);

can only connect to default namespace. 

this is the server log
  socket.io:socket socket connected - writing packet +0ms
  socket.io:socket joining room I6LarO9Dg0hqscrpAAAA +12ms
connection
  socket.io:socket joined room I6LarO9Dg0hqscrpAAAA +36ms

and this is the log from cocos2d-x
SocketIOHelper::init called, connecting to url : ws://127.0.0.1:3010/testpoint
SIOClientImpl::init() successful
SIOClientImpl::handshake() called
SIOClientImpl::handshake() waiting
In the constructor of HttpClient!
SIOClientImpl::handshakeResponse() called
handshake completed
response code: 200
SIOClientImpl::handshake() succeeded
SIOClientImpl::handshake() dump data: 97:0{"sid":"S91jNvR2YZpu4ifsAAAI","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}
SIOClientImpl::handshake() Socket.IO 1.x detected
done parsing 1.x
SIOClientImpl::openSocket() called
[WebSocket::init] _host: 127.0.0.1, _port: 3010, _path: /socket.io/1/websocket/?EIO=2&transport=websocket&sid=S91jNvR2YZpu4ifsAAAI
[1442582986:2844] NOTICE: Initial logging level 7
[1442582986:2845] NOTICE: Library version: 1.3 901bc8d
[1442582986:2845] NOTICE: IPV6 compiled in and enabled
[1442582986:2845] NOTICE: libev support not compiled in
[1442582986:2845] NOTICE:  static allocation: 4496 + (16 x 1024 fds) = 20880 bytes
[1442582986:2846] NOTICE:  per-conn mem: 184 + 1594 headers + protocol rx buf
-->SEND:40::/testpoint,:
SIOClientImpl::onOpen socket connected!
SIOClientImpl::onMessage received: 40
Message code: [4]
Socket Connected
SIOClientImpl::onMessage received: 42["message","Simple message test from default namespace"]
Message code: [4]
Event Received (["message","Simple message test from default namespace"])
event name message between 1 and 7
SIOClientImpl::onMessage received: 42["message",{"name":"myname","type":"mytype"}]
Message code: [4]
Event Received (["message",{"name":"myname","type":"mytype"}])
event name message between 1 and 7
SIOClientImpl::onMessage received: 42["testevent",{"name":"myname","type":"mytype"}]
Message code: [4]
Event Received (["testevent",{"name":"myname","type":"mytype"}])
event name testevent between 1 and 9
-->SEND:2:::
Heartbeat sent

**Comment by man2** [comment] 2015-09-19 01:43
It seems like socketio packet toString() doesn't need ":" separator for 1.0

**Comment by himynameschris** [comment] 2015-09-19 23:28
I tested and confirmed that this was an issue, in fact i was having trouble communicating with the default namespace as well as custom namespaces.

@pandamicro @zilongshanren @minggo it looks like somewhere between my commits and the release of 3.8, a bug was introduced to the socket.io extension that prevents it from functioning correctly with socket.io servers version 1.3.x (the same version bundled with cocos2d-html). this can be reproduced with the cpp and js test cases

**Comment by himynameschris** [comment] 2015-09-20 00:34
@man2 nailed it, the separator ":" on line 233 being used for v1.0 packets is incorrect, should be changed to ""

**Comment by ZeroHackeR** [comment] 2015-09-20 00:40
@himynameschris Please kindly let us know if you get that work... :+1:

**Comment by himynameschris** [comment] 2015-09-20 00:55
fixed in #13953 

change line 233 of SocketIO.cpp from _endpointseperator = ":" to _endpointseperator = "", credit to @man2 for figuring it out first

**Comment by man2** [comment] 2015-09-20 07:56
also thanks to @toothpaste-and-bubblegum for their working code of socket.io 1.0 implementation
https://github.com/toothpaste-and-bubblegum/cocos2d-x/blob/e7537e49330d9edd2283807651fb502404bd065c/cocos/network/SocketIO.cpp

**Closed as completed** 2015-09-20 15:15 UTC
Labels: type:bug
