### ISSUE TITLE
[cocos2d-js]Editbox Works weird in Mac

### ISSUE THREAD

**Issue by Monisha123Ramesh** [cocos2d/cocos2d-x#18595] opened 2017-12-28 10:02 UTC
hello @zilongshanren , @dumganhar , @minggo
I am doing a game for Mac store using cocos2d-js. I am in need of help with edit box issue.
Edit box works weird in Mac. When the window size is changed (i.e.,maximised or minimised) the edit box position changes and it comes back to its original position until its been clicked. I am sharing the screenshots. Can you please have a check on it and provide me a solution as I'm stuck on this issue for long..

Mac version is 10.13.2

Initial:

<img width="791" alt="screen shot 2017-12-28 at 3 07 51 pm" src="https://user-images.githubusercontent.com/28771417/34431083-cf24532e-ec91-11e7-8779-849eec06890b.png">

After maximising

<img width="1096" alt="screen shot 2017-12-28 at 3 08 18 pm" src="https://user-images.githubusercontent.com/28771417/34431087-d2a7779c-ec91-11e7-9a71-64563e0acf0b.png">

Thank you.

**Comment by drelaptop** [comment] 2017-12-29 03:19
I found the window on project `cpp-tests` and `js-tests` can't maximising, could you have a try to reproduce this issue by new a simple project, and then provide the code. It will be better for us to look into this issue and find bug.

**Comment by Monisha123Ramesh** [comment] 2017-12-29 06:03
Thank you for your response.

Yes, as u said in js-tests we can't maximise the window. I have added a code in app delegate in order to maximise the window.

**Comment by Monisha123Ramesh** [comment] 2017-12-29 06:29
Thank you for the response.

I tired to reproduce the issue in a new simple project. I am getting the same issue. Edit box keeps moving when we drag the  window to maximise or minimise.

screen shots:
 initial
<img width="1199" alt="screen shot 2017-12-29 at 11 46 27 am" src="https://user-images.githubusercontent.com/28771417/34430729-10889342-ec8e-11e7-81f5-650f3dd3be68.png">

Input is given to edit box : 

<img width="1204" alt="screen shot 2017-12-29 at 11 46 49 am" src="https://user-images.githubusercontent.com/28771417/34430733-218ed868-ec8e-11e7-9e71-e3ce8767c86f.png">


after minimising the window the edit box position is changed:

<img width="901" alt="screen shot 2017-12-29 at 11 47 03 am" src="https://user-images.githubusercontent.com/28771417/34430737-38ed4e22-ec8e-11e7-9183-dda0482baf20.png">

In order to maximise the window I added below code in AppDelegate:

 `glview = cocos2d::GLViewImpl::createWithRect("totest", Rect(0,0,1200,675),1.0f, true);`

This is the code I am using:

[app.js.zip](https://github.com/cocos2d/cocos2d-x/files/1592657/app.js.zip)

**Comment by Monisha123Ramesh** [comment] 2017-12-29 06:41
I am sharing a video in the below link to make it more clear. Please have a check on it

http://icsoft.in/editboxbug/editboxbug.mov

**Comment by drelaptop** [comment] 2017-12-29 08:23
thanks for detail description. I have view your code and video, and reproduce it on the `cpp-tests` project by adding `glview = GLViewImpl::create("Cpp Tests",true);`.

The issue is cased by the different implement of EditBox. the EditBox you saw is a macOS native widget when input, and is a label when losing focus. I have a idea to avoid that for now. you could try to listen `Windows Resize Event`, make EditBox lose focus when windows resize.

**Comment by Monisha123Ramesh** [comment] 2017-12-29 09:27
Thank you for your time.
Can you please tell me how to do this in cocos2d-js?
I couldn't find `Windows Resize Event` for js.

**Comment by drelaptop** [comment] 2018-01-02 02:47
It seem like cocos2d-x didn't consider `Windows Resize Event` ever before, because `Windows Resize` would never occur on mobile platforms, we always consider mobile first. if you decide to do windows resize event, I am afraid you need to custom it by yourself. 
> [event_dispatcher/custom](http://cocos2d-x.org/docs/cocos2d-x/en/event_dispatcher/custom.html) do some help for you.

**Comment by drelaptop** [comment] 2018-01-08 02:42
please close this issue @minggo

**Closed as completed** 2018-01-08 03:34 UTC
