### ISSUE TITLE
etc1 with alpha in android

### ISSUE THREAD

**Issue by sxxdjj** [cocos2d/cocos2d-x#16301] opened 2016-08-03 07:50 UTC
I used etc1 with alpha in android.Game client enter background,then active game client.ETC1 shader can't work in game.
code:

``` c++
GLProgramState* pState = GLProgramState::create(GLProgramCache::getInstance()->getGLProgram(GLProgram::SHADER_NAME_POSITION_TEXTURE_COLOR_ETC1_NO_MVP));
pState->setUniformTexture("u_texture", texture->getName());
pState->setUniformTexture("alpha_texture", texture->getAlphaTexture()->getName());
 pState->getGLProgram()->updateUniforms();
 setGLProgramState(pState);
```

shader:

``` c++
varying vec4 v_fragmentColor;
varying vec2 v_texCoord;
uniform sampler2D u_texture;
uniform sampler2D alpha_texture;
void main()
{
    vec4 normalColor = texture2D(u_texture, v_texCoord);
    vec4 alphaColor =  texture2D(alpha_texture, v_texCoord);
    vec4 mergeColor =  vec4(normalColor.r, normalColor.g, normalColor.b, alphaColor.r);
    gl_FragColor = v_fragmentColor * mergeColor;
}
```

**Comment by minggo** [comment] 2016-08-04 03:15
@sxxdjj i found you used builtin shader like this

``` c++
GLProgramState* pState = GLProgramState::create(GLProgramCache::getInstance()->getGLProgram(GLProgram::SHADER_NAME_POSITION_TEXTURE_COLOR_ETC1_NO_MVP));
```

But you also said you use your own shader. I am confused. Could you please share the test case?

**Comment by sxxdjj** [comment] 2016-08-06 06:55
I created my shader stored in GLProgramCache with key SHADER_NAME_POSITION_TEXTURE_COLOR_ETC1_NO_MVP
This bug appeared when game entered background, android os had no enough memory, clear the game memory.Then active game.My shader can't work.
Later, i shared the test case.

**Comment by sxxdjj** [comment] 2016-08-06 08:13
test case:https://github.com/sxxdjj/shadertest.git
android used android studio
used build_native.py in proj.android-studio folder to build client

**Comment by UKDeveloper99** [comment] 2016-08-06 14:49
@sxxdjj There's nothing broken with ETC1 files in Cocos2D-x engine. I managed to get it working myself some time ago. Although I will admit it took a lot of trial and error. It was very difficult. The problem is probably with your shader code or the way you're creating the shader. Go and research the best way to create a shader in Cocos2D-x and close this issue.

**Comment by minggo** [comment] 2016-08-08 01:42
ect1 support is added in v3.13 which will be released on Aug.22. You can fetch the v3.13 branch to have a try.

**Closed as completed by minggo** 2016-08-08 01:42 UTC
Labels: platform:android
