### ISSUE TITLE
CCMenuItem doesn’t work (Xcode 7.3~)

### ISSUE THREAD

**Issue by SeanIchikawa** [cocos2d/cocos2d-x#15830] opened 2016-06-13 05:08 UTC
Hi, I’m a Japanese game developer. I develop some games with cocos2d-x.
I’m confused by the following problem. So, if you any idea, please help me.

When tap the button put on a cocos2d-x layer, the button doesn’t work.
If the button be tapped, the call-back function of the button doesn’t be called.
I have found some workarounds of the problem. However, I have no idea why the problem occurs. And, I want  the most suitable way, how to fix it.

The following are develop environment and mobile devices that the problem occurs.

[Develop environment]
- Operating system : Mac OS X El capitan(10.11.5)
- Xcode version : 7.3 - 7.3.1(7D1014) 
- cocos2d-x version : cocos2d-x-3.2
- build config. : Test / Release

[Mobile devices]
- iPhone4s(iOS 9.3.2), iPhone5(iOS 9.3), iPad mini(iOS 9.3.1)

If mobile device's condition (iOS version etc.) is different, the problem may not occur.
And, the apps built by Xcode 7.2.1 or older version have no problem. it work normally.
The problem doesn’t also occur with the apps built by Debug build mode.

I attach a sample Xcode project file. (the following URL)
https://github.com/SeanIchikawa/SampleProject/tree/master/CCBTest

The button of the layer is made by ccbi (ccbi = cocos builder file).
The call-back function is referenced to the button by "Selector" in the ccbi file.

[About the sample Xcode project]
- Xcode Project name : CCBTest
- ccbi file: Resources/simple.ccbi
- Class file (written about layer) : Classes/SimpleView.h

Because the problem have not been resolved, so I use Xcode 7.2.1 now.

If you any idea, please give me. 
Thank you for reading my question.

**Comment by ricardoquesada** [comment] 2016-06-17 21:57
So, you are saying that it works on Xcode v7.2 but does not work on Xcode 7.3? is that correct?

**Comment by ricardoquesada** [comment] 2016-06-21 00:17
tried your code... tested on Xcode v7.3.1 both in debug and release mode in an iPhone 5S with iOS 8 and it worked Ok.

No idea why it might not be working, but it seems to be an LLVM related bug. My suggestion is that you create the smallest possible code that reproduces it and submit a bug to apple.

closing this bug. reopen it if you think it is a cocos2d-x bug and not an Xcode bug. If so, please add more info. thanks.

**Closed as completed by ricardoquesada** 2016-06-21 00:17 UTC
