### ISSUE TITLE
cpp-empty-test does not compile on OS X

### ISSUE THREAD

**Issue by alfogrillo** [cocos2d/cocos2d-x#16220] opened 2016-07-26 16:49 UTC
The empty project does not compile on OS X (10.11.4).
I see these errors in `CCDevice-apple.mm`:

![xcode-error](https://cloud.githubusercontent.com/assets/19324622/17147041/293d36ee-5361-11e6-94ec-8399a63530fb.png)
- cocos2d-x version: 3.12
- devices test on: Mac book air 2013
- developing environments
  - Xcode version: 6.4

Steps to Reproduce:
1.  cocos new -l cpp TEST
2. Open the Xcode project and run on Mac OS

**Comment by ricardoquesada** [comment] 2016-07-27 00:08
might be an Xcode 6.4 thing?
I tried on "v3" branch which is similar to v3.12 + some fixes and with Xcode 7.3 and worked ok.

**Comment by ricardoquesada** [comment] 2016-07-27 00:41
well... I confirm that the issue is with Xcode 6.4 Any reason why you are still using it?
I have bad news for you :(, besides the bug that you reported,  we are using code in `CCDevice-mac.cpp` that only works on OS X 10.11 and requires Xcode 7.

@minggo @linshun what's the policy here? should we support Xcode 6.4? or only Xcode 7+ ?

**Comment by minggo** [comment] 2016-07-27 01:32
@ricardoquesada i don't think we should support Xcode 6.x unless it is very easy to fix.

**Comment by ricardoquesada** [comment] 2016-07-27 03:32
@minggo I tried to fix it and I couldn't. Although I didn't spend more than 15 minutes on it.
It is not trivial since I have to reimplement a function that apparently was added in v3.12.
But we should know that we are using a function that is only available in OS X 10.11, which might be a problem for some users.
In particular we are using: `boundingRectWithSize`

``` objc
@interface NSAttributedString (NSExtendedStringDrawing)
- (void)drawWithRect:(CGRect)rect options:(NSStringDrawingOptions)options context:(nullable NSStringDrawingContext *)context NS_AVAILABLE(10_11, 6_0);
- (CGRect)boundingRectWithSize:(CGSize)size options:(NSStringDrawingOptions)options context:(nullable NSStringDrawingContext *)context NS_AVAILABLE(10_11, 6_0);
@end
```

and as you can see it says `NS_AVAILABLE(10_11..)`.
We are using it in `CCDevice-mac.cpp`

**Comment by minggo** [comment] 2016-07-27 07:13
Yep, we should aware of it. And is it anything with the compiling issue?

**Comment by minggo** [comment] 2016-07-27 07:15
And i think we should update the README of the requirements.

**Comment by alfogrillo** [comment] 2016-07-27 07:17
@ricardoquesada 
Until cocos 3.11 I remember the project worked well.
I still use Xcode 6.4 because I'm working with iOS 8.4 with Jailbreak because I have not an Apple developer account yet. 
I could try to update Xcode and see if all continue to work for me.
Anyway I agree with you: not a good thing the project is going to work only on OS 10.11+

**Comment by minggo** [comment] 2016-07-27 07:27
@ricardoquesada  he codes are

``` c++
#ifdef __MAC_10_11
    #if __MAC_OS_X_VERSION_MAX_ALLOWED >= __MAC_10_11
    dim = [str boundingRectWithSize:textRect options:(NSStringDrawingOptions)(NSStringDrawingUsesLineFragmentOrigin) context:nil].size;
    #else
    dim = [str boundingRectWithSize:textRect options:(NSStringDrawingOptions)(NSStringDrawingUsesLineFragmentOrigin)].size;
    #endif
#else
    dim = [str boundingRectWithSize:textRect options:(NSStringDrawingOptions)(NSStringDrawingUsesLineFragmentOrigin)].size;
#endif
```

It doesn't only work on Mac OS 10.11.

**Comment by ricardoquesada** [comment] 2016-07-27 14:28
@minggo ah... thanks. sorry for the confusion!

**UPDATE**: See my post below... actually, it will only compile on 10.11

**Comment by alfogrillo** [comment] 2016-07-27 14:33
@minggo @ricardoquesada 
No problems with Xcode 7.3.1

**Comment by ricardoquesada** [comment] 2016-07-27 14:40
@Drakon-Cocos good to know.

@minggo sorry, actually there are two more calls that are not using that guards... I'll fix them using those guards.
they are at lines 163 and 136.

**Comment by ricardoquesada** [comment] 2016-07-27 20:31
compile on OS 10.10 fixed.
Xcode 6.4 won't be supported.

So, closing this bug as fixed. thanks.

**Closed as completed by ricardoquesada** 2016-07-27 20:31 UTC
Labels: platform:mac
