### ISSUE TITLE
Batching the UI and other things in 1 draw call

### ISSUE THREAD

**Issue by KioriSun** [cocos2d/cocos2d-x#9925] opened 2015-01-12 02:42 UTC
This issue is related to https://github.com/cocos2d/cocos2d-x/issues/9905.

Right now UI items are each their own thing, and a fancy UI will lead to a monstrous amount of -wasted- draw call. Cocos needs to change the current implementation of UI elements so they can all be batched into 1 Draw. Unity does that already, and cocos is the better engine.
Also, perhaps the devs should look into a similar solution for multi-sprite animation(bones, as it stands), currently i can only get 1 drawcall with a sprite-sheet. AND its actually 2 considering the BG also counts as 1. Maybe the engine should make texture atlases at runtime.

Alternatively, cocos studio could make these atlases with everything you gave it, before packing the game. Optimizing the organizing and handling of images/fonts,etc regardless of what you used. So developers would just worry about the game making, and the studio would pack/handle the rest for best performance.

Cocos is on a good direction currently.
I'm sure there are more intelligent ways to go about it, and you guys will figure it out.

All of this was done and tested under cocos studio 2.1BETA, great software btw.
Ii took the general shark example, and made a sprite sheet, with the sheet it went from over 20 DCs to 1(2).

**Comment by man2** [comment] 2015-04-23 19:26
is there any updates on this? Can we change the inheritance of CCLabel from SpriteBatchNode to Sprite?

**Comment by man2** [comment] 2015-04-27 03:44
my latest update on this 
![screen shot 2015-04-27 at 11 36 10 am](https://cloud.githubusercontent.com/assets/167375/7341330/bc188370-ecd2-11e4-9ae3-ca964c4443be.png)
Still  having problem on fonts offset, maybe if someone can help, I will share the code

**Comment by walzer** [comment] 2015-04-27 07:53
I asked @andyque to implement UI batching in v3.6, but the problem is that it will break backward compatibility.

**Comment by walzer** [comment] 2015-04-27 08:28
Refer to #9905 , the similar request.

**Comment by man2** [comment] 2015-04-27 10:09
I have successfully batch LabelBMFont, currently it breaks at space and new lines. Any help will be appreciated here

I think performance is much more important than backward compatibility

**Comment by zilongshanren** [comment] 2016-06-08 08:05
@man2  @KioriSun 
It is implemented here: https://github.com/cocos2d/cocos2d-x/pull/13201
Could you test this issue with the latest v3.11 version? 
thanks.

**Comment by minggo** [comment] 2016-06-30 02:30
It is fixed by @zilongshanren , so close it.

**Closed as completed by minggo** 2016-06-30 02:30 UTC
Labels: type:request, highlight
