### ISSUE TITLE
websocket fails in cocos2d-x 3.0rc1 on Android when sending 5+ packets at once

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8528] opened 2014-09-30 09:17 UTC
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5839). It was created at 2014/08/21 11:18:38 +0000
# Description

I noticed upon upgrading from 3.0rc0 to 3.0rc1 that, when using external/websocket websocket.send(), Android crashes at WebSocket.cpp libwebsocket_write() when it accumulates at least 5 packets and sends it simultaneously.

Please reply as to the estimated timeline when a fix would be available.

**Comment by dabingnn** [comment] 2014-12-03 02:47
@Dhilan007 
Could you please take a look at it and check if it exists in 3.3 or not?

**Comment by puspesh** [comment] 2015-02-19 06:30
is this issue fixed? or any patch available for the same.

**Comment by SweetEyesVN** [comment] 2015-06-30 06:41
Is this issue fixed pls? I have the same problem here :(.

**Comment by jarsj** [comment] 2015-09-01 00:29
Still exists. 3.3.

**Comment by jarsj** [comment] 2015-09-01 01:59
I managed to fix it. libwebsocket_write returns -1 which is misinterpreted in the code as buffer run. A re-attempt is made and it crashes.  The recommended behavior according to the libwebsocket API is to close the connection. 
In function onSocketCallback around lines 570 Change

```
if (bytesWrite < 0) {
    break;
}
```

to

```
if (bytesWrite < 0) {
       CC_SAFE_DELETE_ARRAY(buf);
        _wsHelper->quitSubThread();
       if (_readyState != State::CLOSED) {
                WsMessage* msg = new (std::nothrow) WsMessage();
                _readyState = State::CLOSED;
                msg->what = WS_MSG_TO_UITHREAD_CLOSE;
                _wsHelper->sendMessageToUIThread(msg);
         }
         return 0;
  }
```

**Comment by rinlac** [comment] 2015-10-22 06:39
I have the same problem, and I hope the problem is resolved. 
cocos2d-x V3.7.1

**Comment by jarsj** [comment] 2015-10-22 06:48
The code still seems to be doing the same thing (3.8.1). You can try my change above. It has been working without problems for me.

**Comment by rinlac** [comment] 2015-10-22 07:41
I tried to fix it like you did but the same problem occured.

CC_SAFE_DELETE_ARRAY(data->bytes);
CC_SAFE_DELETE(data);
CC_SAFE_DELETE_ARRAY(buf);
_wsHelper->_subThreadWsMessageQueue->erase(iter++);
CC_SAFE_DELETE(subThreadMsg);

> > add  
> > if (CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID) {
> >         break;
> > }

process in the following threads

I resolved it in the following way, but It is too slow.

**Comment by jarsj** [comment] 2015-10-22 07:48
Can you share your modified WebSocket.cpp ? I am sure I fixed this issue, because my games depend on this behavior. Would love to get to the bottom of this.

**Comment by rinlac** [comment] 2015-10-22 08:29
That's all I modified.

**Comment by iota01** [comment] 2015-10-30 05:45
I same problem
Please quick fix!!

**Comment by binbin8300** [comment] 2016-06-27 18:59
the same problem,
pls try to fix it

**Comment by minggo** [comment] 2016-06-28 01:43
@binbin8300 What's your engine version?

**Comment by binbin8300** [comment] 2016-06-28 06:08
@minggo cocos2d-x-3.3rc2

**Comment by minggo** [comment] 2016-06-29 08:54
I think @dumganhar may know it, since he is more familiar with websocket

**Comment by dumganhar** [comment] 2016-06-29 08:59
@binbin8300 , it probably have been fixed in the latest release. Please try to use the latest release (currently v3.11.1) and give us your feedback.

**Closed as completed** 2017-02-17 08:12 UTC
Labels: type:bug
