### ISSUE TITLE
EditBox not show any character when type on keyboard

### ISSUE THREAD

**Issue by rbermudez** [cocos2d/cocos2d-x#16959] opened 2016-12-04 15:13 UTC
- cocos2d-x version:3.13
- devices test on:android 4.4
- developing environments
   - NDK version: 10
   - Xcode version:Eclipse
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. Run CppTest
2.Select 52:Node:Ui ->1:GUI:Dynamic Create Test ->3:EditBoxTest.
3.The problem is the component ui EditBox not show any character when type on keyboard, but when  the focus is lost the character appears

**Comment by qiwucwb** [comment] 2016-12-05 10:02
me too.
android log: Warning! You can't change Android Hint fontName and fontSize.
testing...

**Comment by fnc12** [comment] 2016-12-18 04:40
probably you pass `Size::ZERO` in `EditBox::create` function as first parameter.

**Comment by minggo** [comment] 2016-12-21 02:43
@zilongshanren have you resolved it? I can't reproduce it in v3.14.

**Comment by artemtarassov** [comment] 2017-02-20 17:48
i still see this behavior in v3.14.1 on my mac sierra

**Comment by zilongshanren** [comment] 2017-05-10 07:53
@artemtarassov 
I have fixed it, could you please give it a test?

**Comment by artemtarassov** [comment] 2017-05-10 09:46
@zilongshanren , i see you changed some java files but i had this issue with the mac implementation. i'm about to update to 3.15 in few days and will check if the editbox error is still there.

**Comment by zilongshanren** [comment] 2017-05-11 01:53
@artemtarassov 
thanks.

**Comment by zilongshanren** [comment] 2017-05-11 01:54
@qiwucwb It's fixed now in the upstream, you could refer to the merged PR to resolve this issue by yourself.

**Closed as completed** 2017-09-20 06:27 UTC
