### ISSUE TITLE
Background music stopped when other sound play

### ISSUE THREAD

**Issue by yantian001** [cocos2d/cocos2d-x#10724] opened 2015-03-04 10:09 UTC
i use below code to loop play background music ,

``` c++
    AudioProfile profile;
    profile.name = "Background";
    profile.maxInstances = 20 ;
    m_CurrentMusicId = AudioEngine::play2d(musicpath,m_LoopMusic,m_Volume,&profile);
```

it's work perfectly on win32 , but when i test on iPhone 4 ,sometimes the backgroud music stopped when
sounds play , and the print the below logs in the console 

``` c++
cocos2d::experimental::AudioPlayer::play2d(...) : alsourceplay error code :a004
```

so what happened? i program with cocos2dx 3.3

**Comment by yantian001** [comment] 2015-03-05 01:49
git@github.com:yantian001/testaudio.git 
this demo could reproduce this issue

**Comment by walzer** [comment] 2015-04-24 09:22
1. What's your iOS version on iPhone4?
2. You said **sometimes**, that means it bug can not 100% reproduced from your git repository, right?

**Comment by yantian001** [comment] 2015-04-25 01:50
1.My ios version is 7.1.2
2. yes ,maybe when i played many sounds at the same time (less than maxinstance) or the same sound played many time at the same time , i'm not sure which reason lead to this error .. btw ,the sound i said above isn't the stopped backgroud music .

**Comment by kumsook** [comment] 2015-05-18 07:41
@walzer  ios version is 8.3 ipad mini

id = play2d("test1.mp3", true); 
AudioEngine.setLoop(id, false);
AudioEngine::play2d("other.mp3", false); <- Error occurs in this part
AudioEngine.stop(id);

bool cocos2d::experimental::AudioPlayer::play2d(cocos2d::experimental::AudioCache *):alSourcePlay error code:a004

i program with cocos2dx 3.5

**Comment by yantian001** [comment] 2015-05-18 07:46
@kumsook So you encounter this issue too ? did u have any idea ?

**Comment by kumsook** [comment] 2015-05-18 09:25
@yantian001 I think I can not read because the sound is not cached

**Comment by kumsook** [comment] 2015-05-19 01:27
@yantian001 https://github.com/cocos2d/cocos2d-x/issues/9008 Of the attempt to apply the issues

**Comment by yantian001** [comment] 2015-05-19 01:50
@kumsook it seems haven't apply to offical branch ,but maybe it's a solution ,thanks very much ..

**Comment by kumsook** [comment] 2015-05-22 07:40
@yantian001 

AudioPlayer.mm
bool AudioPlayer::play2d(AudioCache\* cache)
{
 alSourcePlay(_alSource);
}

AudioEngine-inl.mm
update()
{
 alGetSourcei(player._alSource, AL_SOURCE_STATE, &sourceState);
 if (player._ready && sourceState == AL_STOPPED) {
    remove();
 }
}

playsound Immediately update remove

auto scheduler = cocos2d::Director::getInstance()->getScheduler();
        scheduler->schedule(CC_SCHEDULE_SELECTOR(AudioEngineImpl::update), this, 0.05f, false);

-> 
scheduler->schedule(CC_SCHEDULE_SELECTOR(AudioEngineImpl::update), this, 0.5f, false);

Lower incidence
Is there a way to fix this?

**Comment by yantian001** [comment] 2015-07-23 07:56
@kumsook it's seems not work ...

**Comment by backviet** [comment] 2015-09-11 15:51
same this issue with ios 8.4 simulator (iphone 6). It will appear when has just begun game

**Comment by dumganhar** [comment] 2016-08-02 06:55
@yantian001, @kumsook, @backviet01, I fixed some issues of Audio recently.
I assumed this issue has been fixed, so I closed this issue.

Could you pull the latest code on v3 branch to test it again? If you still get this issue, feel free to re-open this issue. Thanks.

**Closed as completed by dumganhar** 2016-08-02 06:55 UTC

**Comment by formatCvt** [comment] 2016-11-30 14:41
Same problem here
Samsung Galaxy Grand (Baffin)
