### ISSUE TITLE
Need suport sprite or animation timeline from cocostudio 2.3.1 to cocos2dx3.4 not display blend src 

### ISSUE THREAD

**Issue by saganhim** [cocos2d/cocos2d-x#13016] opened 2015-07-25 07:15 UTC
I create animation using cocostudio v2.3 and load csb using cocos2dx v3.4, i have set blend src to change.
but after build. this animation not display blend src.
this is code load:

```
auto nodeAction = CSLoader::createNode("BigWin.csb");
nodeAction->setZOrder(11);
this->addChild(nodeAction);
nodeAction->setPosition(Director::getInstance()->getWinSize() / 2);
auto action = CSLoader::createTimeline("BigWin.csb");
action->gotoFrameAndPlay(0, false);
action->setLastFrameCallFunc([nodeAction]()
{
nodeAction->removeFromParent();
});
nodeAction->runAction(action);
```

I have same problem when using tween frame.
https://www.youtube.com/watch?v=HFVbqf-rDpE

please help me frown emoticon

**Comment by pandamicro** [comment] 2015-07-28 03:34
I believe it's because Cocos Studio parser in v3.4 doesn't parse the value of blend functions, can you upgrade your Cocos2d-x engine ? Otherwise you may need to manually migrate the latest parser

**Comment by saganhim** [comment] 2015-07-28 06:46
I tried with Cocos2d-x higher version (3.6 - 3.7) , but what I saw did not change

**Comment by pandamicro** [comment] 2015-07-28 07:07
Do you have a sample project to reproduce the issue ?

**Comment by minggo** [comment] 2016-07-01 06:34
Since cocos studio is canceled, so close this issue.

**Closed as completed by minggo** 2016-07-01 06:34 UTC
