### ISSUE TITLE
memset Undefined When Android MinSdkVersion is 21

### ISSUE THREAD

**Issue by mikehay** [cocos2d/cocos2d-x#18708] opened 2018-03-01 15:16 UTC
Description

We have been using cocos2d-x successfully in our Android build, with minSdkVersion set to 19 in our Gradle build files. cocos2d-x builds and runs well. When we change the minSdkVersion to 21 (we need to do this) cocos2d-x no longer builds.

Environment
- cocos2d-x version: cocos2d-x-3.15.1
- devices test on: Google Pixel
- developing environments
   - NDK version: 16.1.4479499
   - AndroidStudio version: 3.0.1
   - OS version: macOS 10.13.3

Steps to Reproduce:
1. In an Android project, set the minSdkVersion to 21.
2. Attempt to build.
3. When the build fails, note that you see the following errors: 

```
 FAILED: /Users/mike/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv5te-none-linux-androideabi --gcc-toolchain=/Users/mike/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/mike/Library/Android/sdk/ndk-bundle/sysroot  -DCC_ENABLE_BOX2D_INTEGRATION=0 -DCC_ENABLE_BULLET_INTEGRATION=0 -DCC_USE_3D_PHYSICS=0 -DCC_USE_NAVMESH=0 -DCC_USE_PHYSICS=0 -DCC_USE_WEBP=1 -DCOCOS2D_DEBUG=1 -DUSE_FILE32API -I/Users/mike/Projects/PROJECT/lib/client/core -I/Users/mike/Projects/PROJECT/lib/client/core/actions -I/Users/mike/Projects/PROJECT/lib/client/core/bridge -I/Users/mike/Projects/PROJECT/lib/client/core/bridge/features -I/Users/mike/Projects/PROJECT/lib/client/core/chat -I/Users/mike/Projects/PROJECT/lib/client/core/common -I/Users/mike/Projects/PROJECT/lib/client/core/data -I/Users/mike/Projects/PROJECT/lib/client/core/descriptor -I/Users/mike/Projects/PROJECT/lib/client/core/designMode -I/Users/mike/Projects/PROJECT/lib/client/core/directory -I/Users/mike/Projects/PROJECT/lib/client/core/entity -I/Users/mike/Projects/PROJECT/lib/client/core/entity/avatar -I/Users/mike/Projects/PROJECT/lib/client/core/geometry -I/Users/mike/Projects/PROJECT/lib/client/core/images -I/Users/mike/Projects/PROJECT/lib/client/core/inventory -I/Users/mike/Projects/PROJECT/lib/client/core/networking -I/Users/mike/Projects/PROJECT/lib/client/core/networking/messages -I/Users/mike/Projects/PROJECT/lib/client/core/notification -I/Users/mike/Projects/PROJECT/lib/client/core/pathfinding -I/Users/mike/Projects/PROJECT/lib/client/core/room -I/Users/mike/Projects/PROJECT/lib/client/core/user -I/Users/mike/Projects/PROJECT/lib/client/core/utilities -I/Users/mike/Projects/PROJECT/lib/client/external -I/Users/mike/Projects/PROJECT/lib/client/external/Gestures -I/Users/mike/Projects/PROJECT/lib/client/external/TwitterText -I/Users/mike/Projects/PROJECT/lib/client/external/cache -I/Users/mike/Projects/PROJECT/lib/client/external/flatbuffers -I/Users/mike/Projects/PROJECT/lib/client/external/flatbuffers-java -I/Users/mike/Projects/PROJECT/lib/client/external/flatbuffers-java/com -I/Users/mike/Projects/PROJECT/lib/client/external/flatbuffers-java/com/google -I/Users/mike/Projects/PROJECT/lib/client/external/flatbuffers-java/com/google/flatbuffers -I/Users/mike/Projects/PROJECT/lib/client/external/flatbuffers-objc -I/Users/mike/Projects/PROJECT/lib/client/external/libbson -I/Users/mike/Projects/PROJECT/lib/client/external/libbson/src -I/Users/mike/Projects/PROJECT/lib/client/external/libbson/src/bson -I/Users/mike/Projects/PROJECT/lib/client/external/libbson/src/jsonsl -I/Users/mike/Projects/PROJECT/lib/client/external/rapidjson -I/Users/mike/Projects/PROJECT/lib/client/external/rapidjson/error -I/Users/mike/Projects/PROJECT/lib/client/external/rapidjson/internal -I/Users/mike/Projects/PROJECT/lib/client/external/rectpack2D -I/Users/mike/Projects/PROJECT/lib/client/external/sqlite -I/Users/mike/Projects/PROJECT/lib/client/rendering -I/Users/mike/Projects/PROJECT/lib/client/rendering/cocos2dx -I/Users/mike/Projects/PROJECT/lib/client/rendering/cocos2dx/assets -I/Users/mike/Projects/PROJECT/lib/client/rendering/cocos2dx/assets/avatar -I/Users/mike/Projects/PROJECT/lib/client/rendering/cocos2dx/assets/avatar/spine -I/Users/mike/Projects/PROJECT/lib/client/rendering/cocos2dx/assets/furniture -I/Users/mike/Projects/PROJECT/lib/client/rendering/cocos2dx/assets/tiles -I/Users/mike/Projects/PROJECT/lib/client/rendering/cocos2dx/camera -I/Users/mike/Projects/PROJECT/lib/client/rendering/cocos2dx/data -I/Users/mike/Projects/PROJECT/lib/client/rendering/cocos2dx/descriptors -I/Users/mike/Projects/PROJECT/lib/client/rendering/cocos2dx/designMode -I/Users/mike/Projects/PROJECT/lib/client/rendering/cocos2dx/entity -I/Users/mike/Projects/PROJECT/lib/client/rendering/cocos2dx/images -I/Users/mike/Projects/PROJECT/lib/client/rendering/cocos2dx/networking -I/Users/mike/Projects/PROJECT/lib/client/rendering/cocos2dx/render -I/Users/mike/Projects/PROJECT/lib/client/rendering/cocos2dx/touch -I/Users/mike/Projects/PROJECT/lib/client/rendering/cocos2dx/utilities -I/Users/mike/Projects/PROJECT/lib/client/rendering/cocos2dx/vector -I/Users/mike/Projects/PROJECT/lib/client/../../lib/svg -I/Users/mike/Projects/PROJECT/lib/client/../../lib/svg/libagg/agg/include -I/Users/mike/Projects/PROJECT/lib/client/../../lib/svg/libagg/aggsvg -I/Users/mike/Projects/PROJECT/lib/client/../../lib/svg/libexpat -I/Users/mike/Projects/PROJECT/lib/client/../../lib/model/src/main/cpp -I/Users/mike/Projects/PROJECT/lib/client/../../lib/cocos2d-x -I/Users/mike/Projects/PROJECT/lib/client/../../lib/cocos2d-x/cocos -I/Users/mike/Projects/PROJECT/lib/client/../../lib/cocos2d-x/cocos/editor-support -I/Users/mike/Projects/PROJECT/lib/client/../../lib/cocos2d-x/external -I/Users/mike/Projects/PROJECT/lib/cocos2d-x -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/cocos -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/deprecated -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/cocos/platform -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/extensions -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/external -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/external/zlib/include -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/external/android-specific -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/external/android-specific/pvmp3dec/include -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/external/android-specific/pvmp3dec/src -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/cocos/../external/ConvertUTF -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/cocos/../external/poly2tri -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/cocos/../external/poly2tri/common -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/cocos/../external/poly2tri/sweep -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/cocos/../external -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/cocos/../external/edtaa3func -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/cocos/editor-support -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/cocos/../../extensions -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/cocos/../external/xxtea -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/cocos/../external/clipper -I/Users/mike/Library/Android/sdk/ndk-bundle/sources/android/cpufeatures -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/external/unzip -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/external/jpeg/include/android -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/external/png/include/android -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/external/tiff/include/android -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/external/tinyxml2 -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/external/freetype2/include/android/freetype2 -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/external/websockets/include/android -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/external/curl/include/android -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/external/openssl/include/android -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/external/xxhash -I/Users/mike/Projects/PROJECT/lib/cocos2d-x/external/webp/include/android -isystem /Users/mike/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /Users/mike/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include -isystem /Users/mike/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -isystem /Users/mike/Library/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -fno-integrated-as -marm -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++11 -frtti -fexceptions -std=c++11 -Wno-deprecated-declarations -Wno-reorder -Wno-invalid-offsetof -fPIC -stdlib=libc++ -fsigned-char  -g -O0 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wno-unused-private-field -Wno-unused-const-variable -Wno-reorder -fPIC   -std=gnu++11 -MD -MT /Users/mike/Projects/PROJECT/lib/cocos2d-x/outputs/cocos/CMakeFiles/cocos2dInternal.dir/base/allocator/CCAllocatorGlobalNewDelete.cpp.o -MF /Users/mike/Projects/PROJECT/lib/cocos2d-x/outputs/cocos/CMakeFiles/cocos2dInternal.dir/base/allocator/CCAllocatorGlobalNewDelete.cpp.o.d -o /Users/mike/Projects/PROJECT/lib/cocos2d-x/outputs/cocos/CMakeFiles/cocos2dInternal.dir/base/allocator/CCAllocatorGlobalNewDelete.cpp.o -c /Users/mike/Projects/PROJECT/lib/cocos2d-x/cocos/base/allocator/CCAllocatorGlobalNewDelete.cpp
  In file included from /Users/mike/Projects/PROJECT/lib/cocos2d-x/cocos/base/allocator/CCAllocatorGlobalNewDelete.cpp:27:
  /Users/mike/Projects/PROJECT/lib/client/../../lib/cocos2d-x/cocos/base/allocator/CCAllocatorStrategyGlobalSmallBlock.h:96:13: error: use of undeclared identifier 'memset'; did you mean 'wmemset'?
              memset(_smallBlockAllocators, 0, sizeof(_smallBlockAllocators));
              ^~~~~~
              wmemset
  /Users/mike/Library/Android/sdk/ndk-bundle/sysroot/usr/include/wchar.h:159:10: note: 'wmemset' declared here
  wchar_t* wmemset(wchar_t* __dst, wchar_t __wc, size_t __n);
           ^
  In file included from /Users/mike/Projects/PROJECT/lib/cocos2d-x/cocos/base/allocator/CCAllocatorGlobalNewDelete.cpp:27:
  /Users/mike/Projects/PROJECT/lib/client/../../lib/cocos2d-x/cocos/base/allocator/CCAllocatorStrategyGlobalSmallBlock.h:96:20: error: cannot initialize a parameter of type 'wchar_t *' with an lvalue of type 'cocos2d::allocator::AllocatorBase *[14]'
              memset(_smallBlockAllocators, 0, sizeof(_smallBlockAllocators));
                     ^~~~~~~~~~~~~~~~~~~~~
  /Users/mike/Library/Android/sdk/ndk-bundle/sysroot/usr/include/wchar.h:159:27: note: passing argument to parameter '__dst' here
  wchar_t* wmemset(wchar_t* __dst, wchar_t __wc, size_t __n);
                            ^
  In file included from /Users/mike/Projects/PROJECT/lib/cocos2d-x/cocos/base/allocator/CCAllocatorGlobalNewDelete.cpp:27:
  /Users/mike/Projects/PROJECT/lib/client/../../lib/cocos2d-x/cocos/base/allocator/CCAllocatorStrategyGlobalSmallBlock.h:128:27: warning: comparison of integers of different signs: 'int' and 'const size_t' (aka 'const unsigned int') [-Wsign-compare]
          for (int i = 0; i <= kMaxSmallBlockPower; ++i)
                          ~ ^  ~~~~~~~~~~~~~~~~~~~
  1 warning and 2 errors generated.
  ninja: build stopped: subcommand failed.
```

**Comment by drelaptop** [comment] 2018-03-02 01:38
This is a header file include issue, it caused by NDK version update. the latest code in Github have supported NDK r16, so I suggest you make changes refer to the Github corresponding resource code

**Comment by mikehay** [comment] 2018-03-02 15:36
Thanks for the suggestion. I will look at latest.

**Comment by mikehay** [comment] 2018-03-05 22:42
Issue is not resolved with latest cocos2d-x source, but ... Issue is resolved by updating Gradle settings to use 
```
android {
compileSdkVersion 27
buildToolsVersion '27.0.3'
 ...
    defaultConfig {
        targetSdkVersion 27
        minSdkVersion 21
         ...
        externalNativeBuild {
            cmake {
                cppFlags "-frtti -fexceptions"
                arguments "-DCMAKE_FIND_ROOT_PATH=", "-DANDROID_STL=c++_static", "-DANDROID_TOOLCHAIN=clang", "-DANDROID_ARM_NEON=TRUE"
                abiFilters armeabi-v7a
            }
        }
    }
}
``` 
instead of 
```
android {
compileSdkVersion 26
buildToolsVersion '26.0.2'
 ...
    defaultConfig {
        targetSdkVersion 26
        minSdkVersion 21
         ...
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++11 -frtti -fexceptions"
                arguments "-DANDROID_ARM_MODE=arm"
                abiFilters "armeabi"
            }
        }
    }
}
```

This issue may be closed.

**Comment by drelaptop** [comment] 2018-03-06 01:15
thanks please close this issue @mikehay

**Closed as completed** 2018-03-06 14:57 UTC
