### ISSUE TITLE
link error on Linux, Cocos2d-JS ver. 3.12, git

### ISSUE THREAD

**Issue by ad1862** [cocos2d/cocos2d-x#16156] opened 2016-07-19 16:49 UTC
All tests (cpp, lua, js) in cocos folder compiled and run. C++ and Lua versions run without problem, also. But JS on linux had error:
1. cocos new -l js ...
2. cocos run -p linux ...
3. [100%] Linking CXX executable bin/MyGame
     error: undefined reference to..
     error: undefined reference to..

`/frameworks/cocos2d-x/cocos/physics3d/CCPhysics3DConstraint.cpp:113: error: undefined reference to 'btPoint2PointConstraint::btPoint2PointConstraint(btRigidBody&, btVector3 const&)'
/frameworks/cocos2d-x/cocos/physics3d/CCPhysics3DConstraint.cpp:122: error: undefined reference to 'btPoint2PointConstraint::btPoint2PointConstraint(btRigidBody&, btRigidBody&, btVector3 const&, btVector3 const&)'
/frameworks/cocos2d-x/cocos/physics3d/CCPhysics3DConstraint.cpp:169: error: undefined reference to 'btHingeConstraint::btHingeConstraint(btRigidBody&, btTransform const&, bool)'
/frameworks/cocos2d-x/cocos/physics3d/CCPhysics3DConstraint.cpp:180: error: undefined reference to 'btHingeConstraint::btHingeConstraint(btRigidBody&, btVector3 const&, btVector3 const&, bool)'
/frameworks/cocos2d-x/cocos/physics3d/CCPhysics3DConstraint.cpp:191: error: undefined reference to 'btHingeConstraint::btHingeConstraint(btRigidBody&, btRigidBody&, btVector3 const&, btVector3 const&, btVector3 const&, btVector3 const&, bool)'
/frameworks/cocos2d-x/cocos/physics3d/CCPhysics3DConstraint.cpp:204: error: undefined reference to 'btHingeConstraint::btHingeConstraint(btRigidBody&, btRigidBody&, btTransform const&, btTransform const&, bool)'
/frameworks/cocos2d-x/cocos/physics3d/CCPhysics3DConstraint.cpp:230: error: undefined reference to 'btHingeConstraint::setFrames(btTransform const&, btTransform const&)'
/frameworks/cocos2d-x/cocos/physics3d/CCPhysics3DConstraint.cpp:253: error: undefined reference to 'btHingeConstraint::setMotorTarget(btQuaternion const&, float)'
/frameworks/cocos2d-x/cocos/physics3d/CCPhysics3DConstraint.cpp:257: error: undefined reference to 'btHingeConstraint::setMotorTarget(float, float)'
..............
`

**Comment by minggo** [comment] 2016-07-20 08:31
Yep, i can reproduce it.

**Comment by ztech** [comment] 2016-07-27 04:29
#15697 bug since 3.11

**Comment by minggo** [comment] 2016-07-27 05:49
@ztech i think it is a duplicated issue.

**Comment by minggo** [comment] 2016-07-28 07:57
fixed in #16247

**Closed as completed** 2016-07-28 07:58 UTC
Labels: type:bug, script:jsb, platform:linux
