### ISSUE TITLE
[cocos2d-x-js][3.10] mismatch between JS and bindings

### ISSUE THREAD

**Issue by murlock** [cocos2d/cocos2d-x#15275] opened 2016-03-17 11:25 UTC
At http://cocos2d-x.org/docs/api-ref/js/v3x/symbols/cc.MenuItemLabel.html, it show that class has getString() method to return the string of cc.MenuItemLabel

If you look at http://www.cocos2d-x.org/docs/api-ref/cplusplus/v3x/d5/dc4/classcocos2d_1_1_menu_item_label.html, this method doesn't exist.

When using JS bindings, application will crash due to missing getString binding:

<pre>
        onEnter: function() {
            item = new cc.MenuItemToggle(                               
                new cc.MenuItemFont(getTranslation("ENGLISH")),         
                new cc.MenuItemFont(getTranslation("FRENCH")),          
                this.switchLanguage,                                    
                this                                                    
            );                                                          
        },
        switchLanguage: function (evt) {                                  
            try {                                                         
                var cur = evt.getSelectedItem();                          
                cc.log("cur : " + cur);                                   
                cc.log("string: " + cur.getString());                       
            } catch (ex) {
                cc.log("=> " + ex.message);
            } 
</pre>

will output

<pre>
E/Cocos2DX(14417): cur : [object MenuItemFont]
E/Cocos2DX(14417): => cur.getString is not a function
</pre>

Please remove getString from cocos2d-x-js or implementit on cocos2d-x :)

Regards,
Michael

**Comment by ZeroHackeR** [comment] 2016-03-17 13:45
I am not sure 

MenuItemFont and MenuItemLabel 

are the same. Please check them first.

**Comment by ZeroHackeR** [comment] 2016-03-17 13:49
Confirmed they are two different classes.
You are using Font class which does not have getString().
http://www.cocos2d-x.org/reference/html5-js/V3.8/symbols/cc.MenuItemFont.html

**Comment by murlock** [comment] 2016-03-17 14:45
But it is cleary said in your link that

<pre>
Methods borrowed from cc.MenuItemLabel:
    getString    
</pre>

And it works in browser but crashed with JS bindings

**Comment by ZeroHackeR** [comment] 2016-03-18 06:25
You were right. But, the problem is we don't even have `getString` in core.

Check:
[CCMenuItem.cpp](https://github.com/cocos2d/cocos2d-x/blob/ca836aa5cba596a6d542ccda8aab6d4311bd6601/cocos/2d/CCMenuItem.cpp)

Add this at line 232:

```
std::string MenuItemLabel::getString() const
{
    LabelProtocol* label = dynamic_cast<LabelProtocol*>(_label);
    return label->getString();
}

```

**Comment by zilongshanren** [comment] 2016-03-18 06:49
@ZeroHackeR 
Do you mean in JS, the menuItemLabel class has the `getString` method and in JSB it doesn't?

**Comment by zilongshanren** [comment] 2016-03-18 06:49
@ZeroHackeR  I have confirmed your issue, I will fix it later, thanks.

**Comment by ZeroHackeR** [comment] 2016-03-18 06:52
@zilongshanren  My pleasure.. as always... :)

**Comment by murlock** [comment] 2016-03-18 09:29
Thanks guys :)

Do I have to close the issue or it will be done with 3.11 release ?

**Comment by zilongshanren** [comment] 2016-03-18 09:32
@murlock  I think you could close this issue now.

**Closed as completed** 2016-03-18 10:17 UTC
Labels: script:jsb
