### ISSUE TITLE
Memory leaks on ClippingNode - cocos metal version

### ISSUE THREAD

**Issue by kkafaseb** [cocos2d/cocos2d-x#19354] opened 2019-01-24 10:04 UTC
- cocos2d-x version: metal version
- devices test on: iphone xs max
- Xcode version: 10.1
- ios: 12

Steps to Reproduce:
1. Create an empty scene. 
2. Add the following code: 
    ClippingNode *_clipper = ClippingNode::create(Node::create());
    this->addChild(_clipper);

    LayerColor *red = LayerColor::create(Color4B::RED, 100, 100);
    _clipper->addChild(red);
3. Check on instruments.

With an empty scene, metal version has an initial 35 leaks and then nothing. 

![screen shot 2019-01-24 at 12 02 09 pm](https://user-images.githubusercontent.com/42576559/51670713-e7410480-1fcf-11e9-854c-035721dc5fc9.png)

If we add code on step 2, there are 2-3k leaks every few seconds. 

![screen shot 2019-01-24 at 12 03 59 pm](https://user-images.githubusercontent.com/42576559/51670825-31c28100-1fd0-11e9-816c-27e20cb91a59.png)

In our actual game, we face even more issues with other cocos class leaking but was not able yet to isolate which are.

**Comment by kkafaseb** [comment] 2019-01-24 12:34
@minggo pls add in metal-support milestone

**Comment by minggo** [comment] 2019-01-25 00:49
The leak is caused by two things:
* first engine caches builtin shader module(MTLLibrary in metal), it will be released at the end of game or memory warning happen, so it is not a memory leak, i don't know why the tool treat it as memory leak
* second is that `Device::getInstance()` is a singleton pattern, it is not a memory leak too

**Comment by minggo** [comment] 2019-01-25 01:19
I fixed a memory leak in https://github.com/cocos2d/cocos2d-x/pull/19358

**Comment by kkafaseb** [comment] 2019-01-25 08:34
Is it MTLStencilDescriptorInternal the leak you fixed? This one must be real as i could observer teh memory usage going up. And also this one seems to leak every frame. Leaks in my test could reach 30mb and growing bt the minute.

**Comment by minggo** [comment] 2019-01-25 08:49
No, i haven't fixed MTLStencilDescriptorInternal memory leak, what i fixed is Buffer. I will check it.

**Comment by kkafaseb** [comment] 2019-01-25 09:04
![screen shot 2019-01-25 at 11 03 12 am](https://user-images.githubusercontent.com/42576559/51735739-d73d2980-2090-11e9-9956-6a2fc98d3f03.png)

Here is image i put in cocos forum. As you can see here , the leak is more. 45k leaked objects vs 2k in the image above for every frame captured in instruments. I believe the more childs the clipper has, the more the leaks are. Here leak reached 17mb and growing with 390k leaked.

**Comment by minggo** [comment] 2019-01-25 09:05
@kkafaseb i can not reproduce it now. Could you please use the latest codes to have try? May be it is fixed.

**Comment by kkafaseb** [comment] 2019-01-25 09:08
ok i will check )

**Comment by minggo** [comment] 2019-01-30 04:01
@kkafaseb any update?

**Comment by kkafaseb** [comment] 2019-01-30 09:22
@minggo i was out of office, I will check this today!

**Comment by minggo** [comment] 2019-01-30 09:34
Got it, thanks.

**Comment by kkafaseb** [comment] 2019-01-30 11:33
Seems that it's fixed! Great work guys!

Does cocos2d-x internal qa team have test cases regarding memory leaks? Ideally we need isolated test cases because if we test on real game, since there is a lot of code being executed and many 3rd party frameworks etc involved, its hard to spot leaks if they are small. This one was easy to spot as it was leaking a lot.

**Comment by minggo** [comment] 2019-01-31 02:34
We just use cpp-tests for testing. The QA team will test it before releasing. Because it is in alpha version, so the QA team didn't join in.

**Closed as completed by minggo** 2019-01-31 02:34 UTC
