### ISSUE TITLE
void RenderQueue::sort() uses an unstable_sort algorithm

### ISSUE THREAD

**Issue by fusijie** [cocos2d/cocos2d-x#13482] opened 2015-08-20 07:00 UTC
relative pr: #13008.

`version:`3.8
`issue:` RenderQueue::sort use an unstable_sort algorithm will cause render re-order for Android.
`reproduce:`SpriteTest->Testing Sprite

``` cpp
void Sprite1::addNewSpriteWithCoords(Vec2 p)
{
    int idx = (int)(CCRANDOM_0_1() * 1400.0f / 100.0f);
    int x = (idx%5) * 85;
    int y = (idx/5) * 121;
    auto sprite = Sprite::create("Images/grossini_dance_atlas.png", Rect(x,y,85,121) );
    addChild( sprite );
    sprite->setGlobalZOrder(10);
    sprite->setPosition( Vec2( p.x, p.y) );
}
```

**Comment by fusijie** [comment] 2015-08-20 07:05
To fixed it just modify **std::sort** to **std::stable_sort**, but we need a performance test additionally.

**Comment by Dredok** [comment] 2015-11-09 13:20
hi, 
did someone evaluate the impact on performance? I had issues with globalzorder in android and would like to change to std::stable_sort

**Comment by ricardoquesada** [comment] 2016-06-22 16:10
yes, this seems like a bug. it could happen in any platform though. perhaps it happens right now on android because we are using the std from gcc while on iOS we are using the one from clang and the `std::sort` implementation might be different... but yes... we should use `std::stable_sort` here

**Comment by minggo** [comment] 2016-08-01 03:01
@ricardoquesada should we change it with `std::stable_sort`? Or we need to some optimization after changing to `std::stable_sort`? As i know, `std::stable_sort` is slower than `std::sort + lambda`.

**Comment by ricardoquesada** [comment] 2016-08-01 23:43
@minggo I kept thinking about this bug, we have to define what does `globalZOrder` mean.

Because when you use a `globalZOrder == 0`, the rendering order is clear:
- it is decided by the scene graph

But what does it mean when `globalZOrder !=0` ?  It won't use the scene graph. `globalZOrder != 0` creates a rendergraph order.

If two nodes have the same `globalZOrder == 10`... which one should be renderer first?
The two alternatives are:
**a)** the one that was inserted in the render queue first (we must use `stable_sort()` here)
**b)** undefined, since it is a global Z order, independent from the hierarchy, and if the user really wants to set a certain order he should use different values. (we can safely use `sort()` here)

For me, it is not obvious that **a)** is the answer here since "global" means that it is detached from the scene graph, but we can make it work that way. We can implement a solution similar to the one on the other PR where an extra "order of arrival" integer is being added.

does anyone know how does it work on other engines? thanks.

**Comment by minggo** [comment] 2016-08-02 07:30
@ricardoquesada make sense.

**Comment by ricardoquesada** [comment] 2016-08-02 17:36
From our documentation:

```
     Defines the order in which the nodes are renderer.
     Nodes that have a Global Z Order lower, are renderer first.

     In case two or more nodes have the same Global Z Order, the order is not guaranteed.
     The only exception if the Nodes have a Global Z Order == 0. In that case, the Scene Graph order is used.

     By default, all nodes have a Global Z Order = 0. That means that by default, the Scene Graph order is used to render the nodes.
```

closing but as won't fix since it was designed to be undefined when multiple nodes have the same global z order

**Closed as completed by ricardoquesada** 2016-08-02 17:36 UTC
