### ISSUE TITLE
cocos3.15 ccui.WebView can't visit https 【Android  JSB】

### ISSUE THREAD

**Issue by huangapple** [cocos2d/cocos2d-x#17798] opened 2017-05-09 09:50 UTC
JSB
-----------------------------------------
Android 
ccui.WebView, can't  visit https
eg: https://www.baidu.com  
-----------------------------------------
IOS 
ccui.WebView, can't  visit https、http
eg: https://www.baidu.com  http://www.baidu.com  
-----------------------------------------

**Comment by minggo** [comment] 2017-05-10 01:58
what's your engine version?

**Comment by huangapple** [comment] 2017-05-10 01:59
cocos3.15

**Comment by minggo** [comment] 2017-05-10 02:01
The content of the issue is different with the title. So what's the real issue?

**Comment by huangapple** [comment] 2017-05-10 02:06
是 cocos-js  3.15

使用 ccui.WebView 
安卓  不能访问  https://www.baidu.com
但可以 访问  http://www.baidu.com

ios， 也不能访问  https://www.baidu.com
连 http://www.baidu.com  
ios的http不能访问可能是因为苹果那边的限制及项目配置有关

**Comment by ibaranskyi** [comment] 2017-05-10 12:22
huangapple, I had same issue
Look please in this file
https://github.com/cocos2d/cocos2d-x/blob/cocos2d-x-3.15/cocos/scripting/js-bindings/script/ccui/jsb_cocos2d_ui.js
`>>

    ccui.WebView.prototype._loadURL = ccui.WebView.prototype.loadURL;
    ccui.WebView.prototype.loadURL = function (url) {
        if (url.indexOf("http://") >= 0)
        {
            this._loadURL(url);
        }
        else
        {
            this.loadFile(url);
        }
    };`
In you case loadFile function was called and tryed to find local file path from your url

**Comment by minggo** [comment] 2017-05-11 01:25
iOS UIWebView doesn't support SSL, we need to find a way to fix it. About Android, i haven't done research. 

@ibaranskyi yep, i think it is an issue, we should consider `https` too.

**Comment by huangapple** [comment] 2017-05-11 01:44
fix only consider http issue 
 android  UIWebView   is support ssl

@minggo

**Comment by huangapple** [comment] 2017-05-11 01:45
@minggo 
IOS UIWebView support SSL too;

**Comment by minggo** [comment] 2017-05-11 01:52
@huangapple you can refer to [this thread](http://stackoverflow.com/questions/12659264/loading-https-in-uiwebview). UIWebView doesn't support https.

**Comment by huangapple** [comment] 2017-05-11 01:58
but i test https is ok in ios

**Comment by huangapple** [comment] 2017-05-11 02:02
Because his certificate is self signed? So not?
I tested is ok on iOS, my certificate is Symantec wildcard DV

@minggo

**Comment by minggo** [comment] 2017-05-11 02:04
@huangapple please use english in future. You are right, that's why you can not access `https://www.baidu.com` on iOS.

**Comment by minggo** [comment] 2017-05-11 02:07
> fix only consider http issue
android UIWebView is support ssl

What did you mean? The title says the issue is about https.

**Comment by huangapple** [comment] 2017-05-11 02:10
fix 
 if (url.indexOf("http://") >= 0)      
to
 if (url.indexOf("http://") >= 0 || url.indexOf("https://") >= 0)

I  can access https://www.baidu.com on iOS、Android

**Comment by minggo** [comment] 2017-05-11 02:21
Got it.

**Comment by huangapple** [comment] 2017-05-11 02:23
@ibaranskyi 
@minggo 
thank you

**Comment by minggo** [comment] 2017-05-11 02:25
fixed in https://github.com/cocos2d/cocos2d-x/pull/17805
thanks @ibaranskyi

**Closed as completed** 2017-05-11 02:25 UTC
