### ISSUE TITLE
v3.8 ui::EditBox in Android is incorrectly rendered

### ISSUE THREAD

**Issue by felixjingga** [cocos2d/cocos2d-x#13581] opened 2015-08-26 14:43 UTC
after testing v3.8 branch which contains updates to EditBox Android by @zilongshanren When the editBox is not tap the string is display correctly.. but when we want to edit the text, the text shown is somewhat hidden.

**Comment by zilongshanren** [comment] 2015-08-26 14:53
@felixjingga
You should adjust the Editbox's content size.  You should create a EditBox with height large than 50 points.

The widget's behavior is controlled by Android system.

**Comment by zilongshanren** [comment] 2015-08-26 14:56
@felixjingga  And you'd better adjust the font size with a proper value.

Hope it helps you to resolve the issue.

**Comment by felixjingga** [comment] 2015-08-26 15:08
@zilongshanren I'll try it tomorrow, and see if it's working or not.

Thanks,

**Comment by felixjingga** [comment] 2015-08-28 07:04
Hi, Is there no way to turn off the scaling feature? When the editbox is empty I think it use the placeholder font size. after I tap the field, the font size enlarge (this is what I don't want), after "done" entering a string the font size become the size that we set using setFontSize (presumably). BUT, if we set the fontsize and placeholder font size to be the same value, after inserted the string, the string become smaller than what I saw when the placeholder was there. Is this a correct behavior?

Thanks,

**Comment by zilongshanren** [comment] 2015-08-28 07:21
@felixjingga 
The EditBox is designed with a OpenGL label and a native Android widget. When user doesn't input, only the OpenGL label is displayed.(What you mean placeholder here is actually a cocos2d::Label).

 The System control is hided. When you click on the EditBox and began to input, the OpenGL label will be hided and the system control will become visible.

It's hard for me to sync the size between OpenGL label and system control size. I tried many solutions but failed in the end. Any help would be appreciated.

You might wonder why it  is designed  like this. Because if we want to capture screen, only the OpenGL framebuffer could be captured.  We can't put a raw system control on top of OpenGL surface view.

And on Android platform the UI thread is separated with OpenGL thread. When you run a Action on a native control, there will be some delay.  That's another reason will design EditBox like this.

So I think it's the correct behavior..

Do you have any suggestions?

**Comment by felixjingga** [comment] 2015-08-28 14:13
@zilongshanren Is there in any way we can control all the 3 state font-size? currently there are only 2 available setter for the font size, placeholder font-size and font-size it self. I think what I will do after see so many implementation in other non-games app are like these:
1. I will set the placeholder text with a string i.e "enter your answer"
2. When I tap the field, "enter your answer" will completely disappear (like LINE Apps), and I start to write the answer. Assume the font-size edit box is X
3. After "done", what I assume from your answer is you will take the editbox value, and set the value to a Label, and make it visible, and editbox is hidden (is this correct?). So I need to have control this label to set its font size to match the editbox font-size.

In this way, I think we can make the "placeholder" label font-size, when editing font-size, and after edit font-size more or less the same. how about this?

Thanks,

**Comment by mazestoxic** [comment] 2015-08-29 15:40
Hi, i'm also facing this issue.. I'll try fix this issue,

**Comment by mazestoxic** [comment] 2015-08-29 16:37
I think we can modify Cocos2dxEditBox.java, I solved this issue temporary by adding 'setTextSize' method in setEditBoxViewRect method

**Comment by mazestoxic** [comment] 2015-08-31 00:54
I think this issue is very critical. Test application is designed 480x320, after I modified it to 1920x1080, EditBox on Android doesn't work.

**Comment by zilongshanren** [comment] 2015-08-31 00:59
@mazestoxic  Do you mean the cpp-tests not working when resolution changed to 1920*1080?
And what do you mean not working? The keyboard can't be pop up or the rendering is wrong?
Thanks.

**Comment by zilongshanren** [comment] 2015-08-31 01:36
@felixjingga 
I will add three new APIs to solve this problem.

```
setGLLabelEnabled  /  isGLLabelEnabled
getGLLabel
```

We could call `setGLLabelEnabled(false)` to disable GL label and only the native control is added on top of OpenGL view.

And the size sync problem is gone.

**Comment by zilongshanren** [comment] 2015-08-31 01:40
@felixjingga  
Could you give me some screenshot about your problem? thanks.

**Comment by mazestoxic** [comment] 2015-08-31 02:17
@zilongshanren First, given text and placeholder text is shown well, but after I touched the EditBox, Text and cursor are dissappear or size is too big. I tested 2 android phones. One is galaxy s6, one is nexus 7. On galaxy s6, text size is too big. and on nexus 7, cursor and fonts are now shown. If you want maybe I can attach screenshots. On iOS, no problem happen.

**Comment by zilongshanren** [comment] 2015-08-31 02:21
@mazestoxic   screenshot please...

**Comment by mazestoxic** [comment] 2015-08-31 03:28
I attached screenshots.
1. ss_first_giventext.png : Given text is shown well. No problem now.
2. ss_second_texttoobig.png : After I touched EditBox, Cursor is too big, so I can see only a part of the cursor.
3. ss_third_scrollup.png : I touched and scrolled up the editbox, as you can see, a part of text is shown because of too big font size.

On iOS, no problem happen.
And when designed resolution is 480x320, also no problem.
I hope this is helpful for you. Thank you.

![ss_first_giventext](https://cloud.githubusercontent.com/assets/12165820/9571629/73b270b6-4fdb-11e5-974c-ae668aa1c706.png)
![ss_second_texttoobig](https://cloud.githubusercontent.com/assets/12165820/9571631/73bc02ac-4fdb-11e5-8414-d9b8e925886e.png)
![ss_third_scrollup](https://cloud.githubusercontent.com/assets/12165820/9571630/73b83654-4fdb-11e5-9a22-76c4d429b050.png)

**Comment by zilongshanren** [comment] 2015-08-31 03:35
@mannewalis  
I will send a PR to resolve this issue later. And I hope you could help me to test it.

Thanks.

**Comment by felixjingga** [comment] 2015-08-31 06:14
@zilongshanren That screenshots @mazestoxic gave was the issue I faced. :) hope you can send immediate PR for this.

**Comment by zilongshanren** [comment] 2015-08-31 06:59
@felixjingga 
Sure, I will fix it before v3.8 final is released.

**Comment by zilongshanren** [comment] 2015-08-31 07:23
@mazestoxic   could you give me some code snippets to reproduce this issue?
Thanks.

**Comment by mazestoxic** [comment] 2015-08-31 07:30
@zilongshanren It's so simple. You can just modify the designed resolution. Location is 76 line at AppDelegate.cpp of cpp-tests project. from 480x320 to 1920x1080. And then run program on Android Device(in my case, fhd device).
![screen shot 2015-08-31 at 4 28 06 pm](https://cloud.githubusercontent.com/assets/12165820/9574008/59560abc-4ffd-11e5-8482-55760fb9e43e.png)

**Comment by zilongshanren** [comment] 2015-08-31 07:32
@mazestoxic  
Thanks, I will test it.

**Comment by zilongshanren** [comment] 2015-08-31 08:38
@felixjingga @mazestoxic  
How about modifying the content size of the EditBox?
I found that the Android system would always push the content of EditBox up.

**Comment by zilongshanren** [comment] 2015-08-31 10:42
@felixjingga @mazestoxic
After a whole day to struggle with this issue, I will can't find the work around solutions.

possible solutions could be:

When you find the text is pulled up when EditBox get focused, you should call `EditBox->setFontSize` with a smaller value.

And the content size of the EditBox should be greater than 50.

I will still investigate in this issue.. 

Any suggestions would be welcome.

**Comment by mazestoxic** [comment] 2015-09-01 07:20
@zilongshanren I think to render editbox correctly on Android, all values related to size is necessary.
1. Designed Resolution of cocos2d-x
2. Current Viewport size of cocos2d-x
3. EditBox Contentsize of cocos2d-x
4. FontSize of cocos2d-x
5. Screen size of current Android device.
Where can I find the API's to get such values on Java Layer? Is there any JNI functions related to it?

**Comment by zilongshanren** [comment] 2015-09-01 07:39
@mazestoxic 
Yeah, you are right.

The Design Resolution size and viewport size could be got from C++ layer.
The content size and font size of EditBox are passed from C++ layer too.

What we need now is calculating the proper font size according to the content size of EditBox.

**Comment by zilongshanren** [comment] 2015-09-01 15:07
@mazestoxic  @felixjingga 
finally... I have got a solution. I will do more test on it and send a PR tomorrow.

I hope you guys could help me to test it.

Thanks.

**Comment by felixjingga** [comment] 2015-09-01 17:27
@zilongshanren thanks! I'll test it.. :+1:

**Comment by zilongshanren** [comment] 2015-09-02 07:05
@felixjingga  @mazestoxic  
please help me to test the PR.
Thanks.

**Comment by zilongshanren** [comment] 2015-09-02 07:07
@felixjingga  @mazestoxic 
There are some tips when using EditBox on Android platform.
The content size of the EditBox should be `Director::getInstance()->getVisibleSize() * factor`.

Otherwise it won't keep the same size across different Android devices.

**Comment by felixjingga** [comment] 2015-09-03 14:22
@zilongshanren I tested it, and it was okay.. Still think about the content size of the editbox though because I doesn't use the editbox directly, but enclose it with a sprite.. But it's a small matter.. :+1: I think it's safe to merge :)

**Comment by mazestoxic** [comment] 2015-09-05 13:04
@felixjingga @zilongshanren I think a bug is remained. When I touch edit box at first, cursor and text don't appear. It means, EditBox shows nothing. Placeholder text also disappeared. But when touch edit box again after touch other area, cursor and text are OK. After that, always OK. It happens only at first. Does it happen only for me? This is my test code

```
    float height = Director::getInstance()->getVisibleSize().height * (590.0f / 1920.0f);

    m_roomEditBox = ui::EditBox::create(Size(590, height), ui::Scale9Sprite::create("images/button_normal.png"));
    m_roomEditBox->setAnchorPoint(Vec2(0.5, 0.5));
    m_roomEditBox->setPosition(Vec2(800 / 2, 500 / 2 + 96));
    m_roomEditBox->setInputMode(ui::EditBox::InputMode::NUMERIC);
    m_roomEditBox->setFontSize(height * 0.8f);
    m_roomEditBox->setPlaceholderFontSize(height * 0.8f);
    m_roomEditBox->setText("");
    m_roomEditBox->setFontColor(Color3B::WHITE);
    m_roomEditBox->setPlaceHolder(STRKEY("inputroomnumber").c_str());
    m_roomEditBox->setPlaceholderFontColor(Color3B::GRAY);
    m_roomEditBox->setMaxLength(6);
    m_roomEditBox->setReturnType(ui::EditBox::KeyboardReturnType::DEFAULT);
    m_roomEditBox->setDelegate(this);
    this->addChild(m_roomEditBox);
```

**Comment by zilongshanren** [comment] 2015-09-06 00:23
@mazestoxic 
What's your testing environment?  Android? 
I will double check this issue.

**Comment by zilongshanren** [comment] 2015-09-06 01:53
@mazestoxic 
I can't reproduce your issue ...  I used your code but failed to reproduce it.
Can it be reproduced every time or does it happen randomly?
Thanks.

**Comment by felixjingga** [comment] 2015-09-06 13:07
@mazestoxic I can't reproduce this too..

**Comment by mazestoxic** [comment] 2015-09-07 07:27
@felixjingga @zilongshanren Yes.. I think it only happens to me. Maybe I did something wrong. I'll check more.

**Comment by zilongshanren** [comment] 2015-09-15 01:48
@mazestoxic  I close the issue here.
If you still have something wrong, feel free to reopen it.

**Closed as completed by zilongshanren** 2015-09-15 01:48 UTC
Labels: critical

**Comment by chenhaobright** [comment] 2015-12-31 09:55
samsung s6 edge , android5.1 , can reproduce this issue.

**Comment by jhyoon77** [comment] 2016-09-02 07:57
@mazestoxic It is reproduced on my case. (v3.12)

I don't know why, but I added this code and it was fixed.

```
public Cocos2dxEditBox(Context context) {
    super(context);
    this.dispatchSystemUiVisibilityChanged(1); // try add this code
}
```

**Comment by jhyoon77** [comment] 2016-09-02 08:24
In my case, SystemUiVisibility is 5894, before editbox first touch,
It changed to 5888 after touched. (0x6 is SYSTEM_UI_FLAG_FULLSCREEN, SYSTEM_UI_FLAG_HIDE_NAVIGATION)

**Comment by jhyoon77** [comment] 2016-09-02 09:44
I think it is related 'immersive full-screen mode'.
And this is my code. I fixed my source, not cocos2dx code.

```
public class AppAcitivity extends Cocos2dxActivity {
...
...

public void onWindowFocuesChagned(boolean hasFocus)
{
   ...
   if (hasFocus) {
       View decorView = AppActivity.mActivity.getWindow().getDecorView();
        int systemUiOption = decorView.getSystemUiVisibility();
        if ((systemUiOption & View.SYSTEM_UI_FLAG_FULLSCREEN) != 0) {
            systemUiOption ^= View.SYSTEM_UI_FLAG_FULLSCREEN;
        }
        if ((systemUiOption & View.SYSTEM_UI_FLAG_HIDE_NAVIGATION) != 0) {
            systemUiOption ^= View.SYSTEM_UI_FLAG_HIDE_NAVIGATION;
        }
        decorView.setSystemUiVisibility(systemUiOption);
    }
}
```
