### ISSUE TITLE
AudioEngine on Android 7.0 locks up UI and causes severe time delay before playback starts

### ISSUE THREAD

**Issue by dhuang11** [cocos2d/cocos2d-x#16590] opened 2016-09-17 13:14 UTC
- cocos2d-x version: 3.13.1
- devices test on: Nexus 5X, Nexus 9, Nexus 6P
- developing environments
  - NDK version: r10e

Steps to Reproduce:
1. Play an MP3 audio file using AudioEngine::play2d("file.mp3") on Android 6.0, 5.0, 4.4, 4.0 and notice how there is very little lag without preloading the audio file.
2. Update phone to Android 7.0 (Nexus 5X, Nexus 9, Pixel C, and Nexus 6P have supported images at the time)
3. Play an MP3 audio file using AudioEngine::play2d("file.mp3") also without preloading
4. Notice the long delay in starting playback of the audio file and how the entire UI is locked up. We've seen cases where calling "AudioEngine::play2d("file.mp3")" on a 500k MP3 file causes a 2-3 second lock up of the UI. The exact same device running Android 6.0 or below and playing the exact same audio file using the same AudioEngine code has no noticeable playback lag and does not appear to lock up the UI for a noticeable amount of time.

We've been able to reproduce this behavior on Nexus 5X, Nexus 9 (wifi), and Nexus 6P running a before and after test with Cocos2D-X 3.13.1, Android 6.0 (plays fine) and on Android 7.0.

**Comment by dumganhar** [comment] 2016-09-21 02:39
Thanks for your feedback.
How about playing audio after `preload`? Did it also cause a big lag in `AudioEngine::play2d`?

**Comment by dhuang11** [comment] 2016-09-21 03:17
No the lag is gone after preloading all sound files. However, audio playback on Android 7.0 also has skips and pops if the audio is preloaded but no noticeable latency in playback.

**Comment by dumganhar** [comment] 2016-09-21 08:14
> However, audio playback on Android 7.0 also has skips and pops

I don't understand what `skips and pops` means, could you please explain more about that?

**Comment by dhuang11** [comment] 2016-09-21 09:01
Sure - so the sound cuts out for a few milliseconds during playback and then continues playing. It is not too bad, but noticeable.

**Comment by dumganhar** [comment] 2016-09-21 09:32
@dhuang11, how could you hear audio clips that misses a few milliseconds?
Is there a test audio file for easily reproducing this issue?

**Comment by dhuang11** [comment] 2016-09-22 02:38
Not sure if it was milliseconds. There are just intermittent places in the sound where there is no playback suddenly and then it continues playing back. I've uploaded to dropbox one of the sound files we are using where we can hear this. However, we're able to reproduce with all MP3 files at 128kbps

https://www.dropbox.com/s/283u4ihvlfadf9z/winmeter11s_0.mp3?dl=0

**Comment by dhuang11** [comment] 2016-09-22 02:42
Note also we downgraded a Nexus 6P back to 6.0.1 - Audio playback is back to normal with no noticeable delay in playback with and without preload.

So to summarize:
1. Nexus 6P or 5X or 9 on Android 6.0.1 - Audio playback is smooth (with our without preload) and doesn't appear to lock up the UI thread
2. Nexus 6P or 5X or 9 on Android 7.0 - Audio playback without preload causes very severe delay in playback. Also it causes a pretty severe hang up in the UI where the UI stops responding until audio playback is started. Audio playback with preload is smoother, but the audio has areas where it just stops playing and then continues all of a sudden

**Comment by dumganhar** [comment] 2016-09-22 02:47
@dhuang11 , thank you. I will try to test it on my Nexus 9 Android 7.0.
If I get anything, I will add a comment here.

**Comment by dumganhar** [comment] 2016-09-22 06:20
@dhuang11 , I used `winmeter11s_0.mp3` to test and found that AudioEngine used `UrlAudioPlayer` to play this audio. `UrlAudioPlayer` is really simple which just invoke OpenSLES api to play audio. But sorry for that I still couldn't reproduce or find out the issue what you said.

Could you please modify some values in `cocos/audio/android/AudioPlayerProvider.cpp`?

``` c++
static AudioFileIndicator __audioFileIndicator[] = {
        {"default", 128000}, // If we could not handle the audio format, return default value, the position should be first.
        {".wav",    1024000},
        {".ogg",    128000},
        {".mp3",    160000}
};
```

Make the value of `.mp3` key bigger. For example, `160000 * 10`, 
And search line 166, change

``` c++
_preloadWaitCond.wait_for(lk, std::chrono::seconds(2));
```

to 

``` c++
_preloadWaitCond.wait_for(lk, std::chrono::seconds(5));
```

this will make sure using `PcmAudioPlayer` to play audio and mixing audio clips at engine side. 

Please give us feedback after your test.

**Comment by dhuang11** [comment] 2016-09-23 03:09
Ok will give this a try - let you know soon

**Comment by dhuang11** [comment] 2016-09-23 03:59
Ok just made those changes 1600000 \* 10 and setting the wait_for to 5. 

The lag/delay is actually considerably worse than before - from 1-3 seconds to 5-10 seconds for audio that hasn't been preloaded.

However, the random skipping out of sound being played no longer happens.

**Comment by dumganhar** [comment] 2016-09-23 04:40
Good to know `skipping audio clips` didn't happen by applying this.
About the preloading ,basically, we need to support `buffering playing strategy` .

**Comment by ijm700** [comment] 2016-12-14 00:19
@dhuang11 @dumganhar will this occur on all android 7.0 phones ? or was the problem fixed

**Comment by dhuang11** [comment] 2016-12-14 04:12
Yes this still occurs on all Android 7.0 phones for us.

**Comment by ijm700** [comment] 2016-12-14 04:23
@dhuang11 I would test it and see what I could do but I don't have an android 7.0 phone available , I wonder if cocos team figured it out yet

**Comment by dhuang11** [comment] 2016-12-14 04:25
Of the Android 7.0 phones we have, we've been able to reproduce on:
Nexus 5X
Nexus 6P
LG-V20
Nexus 6
Nexus 9

**Comment by dhuang11** [comment] 2017-01-23 12:11
Note that this is no longer an issue on Android 7.1.1 on both Nexus 5X and Nexus 6P as long as all audio is preloaded/cached before first use. On Android 7.0.x, preloading helps the problem a lot but it still hangs a bit when playing audio for the first time. 

However, what we've noticed is that building an NDK DEBUG build, preloading a lot of audio crashes very easily on Android 7.1.1. However, an NDK RELEASE build, preloading doesn't crash. I believe there is already another bug about crashing on large #'s of audio preloaded audio on Android.

**Comment by pabitrapadhy** [comment] 2017-01-24 13:26
Any update on this issue @dhuang11 
whether you were able to find a fix ?

**Comment by dumganhar** [comment] 2017-02-15 02:32
@dhuang11, did you try this PR: https://github.com/cocos2d/cocos2d-x/pull/17233
I guess it will fix lots of Audio preload issues.

**Comment by dumganhar** [comment] 2017-02-16 08:29
PR (https://github.com/cocos2d/cocos2d-x/pull/17233) was merged. I closed this issue.
Please have a test and feel free to re-open this issue if the issue still exists.

**Closed as completed by dumganhar** 2017-02-16 08:29 UTC
