### ISSUE TITLE
lua-tests crash when LuaStack::init() function invoked lua_open()

### ISSUE THREAD

**Issue by liqt** [cocos2d/cocos2d-x#17043] opened 2016-12-20 02:08 UTC
- cocos2d-x version: v3.13.1
- devices test on: ios simulator 5s
- developing environments
   - NDK version:
   - Xcode version: 8.2
   - VS version:
   - browser type and version:

Steps to Reproduce:

1.  compile and run lua-tests
2. lua-tests crash when LuaStack::init() function invoked lua_open()

**Comment by minggo** [comment] 2016-12-20 03:40
Yep, i reproduced it. We are working on it.

**Comment by minggo** [comment] 2016-12-20 09:07
Also crashed in Xcode 8.2.1. And the invoking stack is
```
lua_open -> lua_newstate -> lj_newstate -> lj_vm_cpcall(L, NULL, NULL, cpluaopen)
```
`lj_vm_cpcall` is generated in fly using [DynASM](https://luajit.org/dynasm.html) to compile vm_x86.dasc(may use other architecture corresponding files).  And i found `cpluaopen` is invoked correctly, so the error happened inside `lj_vm_cpcall`.

What i found is that, `lj_vm.S`(the assembly codes that generated by DynASM) on Mac and iOS simulator are the same. And there is not issue on Mac OS X. So i think the issue is caused by iOS simulator SDK. I will download iOS 10.1 simulator to have a try.

**Comment by minggo** [comment] 2016-12-20 10:57
It will crash on iOS 10.0 SDK too. Some developer said there is not issue on Xcode 8.1, i will install it to have a try.

**Comment by zgc0911** [comment] 2016-12-21 01:04
On the Xcode8.1 can work well.

**Comment by minggo** [comment] 2016-12-21 07:06
So it may be a bug of Xcode 8.2. I have not idea how to fix it.

**Comment by zgc0911** [comment] 2016-12-23 01:20
I find a new version of Xcode, i will download Xode 8.2.1 to have a try.

**Comment by minggo** [comment] 2016-12-23 01:56
It crashed in Xcode 8.2.1 too as i mentioned above.

**Comment by zgc0911** [comment] 2016-12-23 03:27
Sorry，I didn't see clear，I think you may be using Xcode 8.2. Because, this version was released in two days ago.

**Comment by liqt** [comment] 2016-12-24 01:33
I had try xcode 8.2 and ios simulator 5  to test， it runs ok， simulator 5s
or above simulator all crash

2016-12-23 11:27 GMT+08:00 zgc0911 <notifications@github.com>:

**Comment by minggo** [comment] 2016-12-26 01:34
@liqt it is because you use old cocos2d-x version. In latest cocos2d-x codes, it uses luajit for all platforms.

**Comment by fatfatson** [comment] 2017-01-02 09:29
严重关注。。。现在模拟器跑不起，真机似乎无问题。

**Comment by liqt** [comment] 2017-01-03 01:57
@minggo i used the latest cocos2d-x version, ios simulator 5 is ok, 5s or +
is crashed, it seems the luajit lib not

compatibility with xcode 8.2 and ios simulator 5s or 5s+

2017-01-02 17:29 GMT+08:00 fatfatson <notifications@github.com>:

**Comment by minggo** [comment] 2017-01-03 02:01
@liqt what i mean latest cocos2d-x is v3.14 which will be released in these days. Yep, luajit is not compatible with Xcode8.2, and i am not sure if it is a problem of luajit or Xcode8.2.

**Comment by silly0128** [comment] 2017-01-03 07:31
我也碰到这个问题，可能跟32位和64位有关，iphone5是32位cpu，iphone5s及之后都是64位cpu

**Comment by bingle123** [comment] 2017-01-05 02:03
严重关注

**Comment by iyexiao** [comment] 2017-01-06 14:18
destop TARGETS 中修改Build Setting 里的Other Linker Flags  
添加-pagezero_size 在3.10版本下Xcode8.2.1能够编译通过

**Comment by lishaizhe** [comment] 2017-02-04 03:16
官方现在有解决方案了吗？现在很多机器都自动升级到8.2了，严重影响啊

**Comment by pbs0512** [comment] 2017-02-06 10:20
the same problem with xcode 8.3 beta

**Comment by minggo** [comment] 2017-02-06 10:24
It is sad to hear that. I tried @iyexiao 's method, but can not fix it.

**Comment by wulei** [comment] 2017-02-16 09:25
现在严重影响开发啊，这个基础问题能优先解决吗？谢了

**Comment by YuweiXiao** [comment] 2017-02-16 09:28
unity + tolua + luajit 在 xcode8.2 下也有这个问题。感觉是 xcode 的问题。

**Comment by rhzchina** [comment] 2017-03-10 07:33
这个问题这么久了，没人去解决啦？

**Comment by dumganhar** [comment] 2017-03-10 07:44
@rhzchina，xcode的问题，我们如何解决？等新版本xcode看看了，或者只能切换回旧版本。

**Comment by sunweiliang** [comment] 2017-03-15 11:14
@dumganhar 谢谢，真机就可以了。十分感谢

**Comment by zgc0911** [comment] 2017-03-29 08:23
有人试过Xcode8.3了吗~~~不知道Xcode8.3有没有问题

**Comment by dumganhar** [comment] 2017-03-29 08:55
@zgc0911, it wasn't fixed in xcode 8.3.

**Comment by 253056965** [comment] 2017-03-29 09:41
我更新了 8.3 的XCODE 依然会编译不通过  请cocos 官方重视一下

**Comment by a85265656** [comment] 2017-03-30 02:48
xcode 8.3  问题依然存在   感觉cocos这边的问题概率比较大

**Comment by bsergean** [comment] 2017-04-18 05:09
Should we create an issue on the Apple radar website, or on the luajit github page ?

**Comment by bsergean** [comment] 2017-04-18 18:47
I confirm that this problem is going away with the latest 2.1 branch.

**Comment by minggo** [comment] 2017-04-19 01:19
@bsergean thanks for the information.
@dumganhar i think we should apply the patch in next version.

**Comment by 253056965** [comment] 2017-04-22 06:33
希望官方提供一个修复方案，要不我们老版本的用户怎么办。

**Comment by iyexiao** [comment] 2017-04-23 11:38
@minggo  -pagezero_size 10000 我这个的时候是没问题的，xcode是自动升级的，而且在3台机器上试过都没问题

**Comment by lovesharyn** [comment] 2017-04-24 17:20
@minggo can we have a compiled version of LuaJit that fixes this issue? So that we can just drop and replace what we have and we do not need to wait till the next release for this to be fixed?

**Comment by minggo** [comment] 2017-04-25 02:43
@lovesharyn sorry, we have other high level tasks. You can build it using https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src.

**Comment by minggo** [comment] 2017-05-05 06:12
@bsergean yep, the patch resolve the crash. Thanks.
I updated luajit for iOS in https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/293. And i updated 3rd party library version of cocos2d-x in https://github.com/cocos2d/cocos2d-x/pull/17783.

**Closed as completed** 2017-05-05 07:20 UTC
Labels: script:lua, critical
