### ISSUE TITLE
Setting opacity on an ui::Button doesn't work anymore ?

### ISSUE THREAD

**Issue by danut007ro** [cocos2d/cocos2d-x#17116] opened 2017-01-05 08:41 UTC
- cocos2d-x version: 3.14
- devices test on: linux, android
- developing environments
   - NDK version: r10e
   - Xcode version:
   - VS version:
   - browser type and version:

A new project on 3.13.1 is ok, but a new project on 3.14 doesn't set opacity. The code I used in HelloWorldScene.cpp on both projects is this :

```
SpriteFrameCache::getInstance()->addSpriteFramesWithFile("buttons.plist");
auto button = ui::Button::create();
button->loadTextureNormal("buttons/play-big", ui::Widget::TextureResType::PLIST);
button->setPosition(Vec2(visibleSize.width/2 + origin.x, visibleSize.height/2 + origin.y));
button->setOpacity(100);
addChild(button);
```

Steps to Reproduce:

1. Create a new project
2. Add a spritesheet
3. Create button and set opacity

Screenshot for 3.13.1:
![mygame3131](https://cloud.githubusercontent.com/assets/1083134/21673798/5bd69f62-d333-11e6-93b2-10d895ee5909.png)

Screenshot for 3.14:
![mygame314](https://cloud.githubusercontent.com/assets/1083134/21673809/65b7f29c-d333-11e6-965e-8215098da3ba.png)

**Comment by minggo** [comment] 2017-01-06 02:23
I tested with v3.14 on Android device, can not find the issue. Could you please provide a test case?

**Comment by minggo** [comment] 2017-01-06 02:25
I don't create from plist, so it is something about plist?

**Comment by minggo** [comment] 2017-01-06 02:36
I tried with plist, can not reproduce too.

**Comment by danut007ro** [comment] 2017-01-06 06:30
I tried from a brand new 3.14 project and with the code above.

**Comment by minggo** [comment] 2017-01-06 06:33
It is strange, will you please share your branch?

**Comment by danut007ro** [comment] 2017-01-06 06:50
I'm sorry I don't understand. I'm attaching the  plist and texture file used.
[buttons.zip](https://github.com/cocos2d/cocos2d-x/files/689120/buttons.zip)

**Comment by minggo** [comment] 2017-01-06 07:06
I though you use git, then it is easy to share your testing branch.

**Comment by minggo** [comment] 2017-01-06 07:36
Yep, i can reproduce it with your resources. But if you use the resources(`tests/cpp-tests/Resources/animations/crystals.plist` and `tests/cpp-tests/Resources/animations/crystals.png`) in cpp-tests, then there is not problem. It is strange.

Edit: update the plist and png path

**Comment by minggo** [comment] 2017-01-06 08:06
Sorry, it is `tests/cpp-tests/Resources/animations/crystals.plist` and `tests/cpp-tests/Resources/animations/crystals.png`.

**Comment by danut007ro** [comment] 2017-01-06 09:42
Also strange is the fact that if running the following animation, the button changes opacity. Any ideas?

```
button->runAction(Sequence::create(
    DelayTime::create(1.0f),
    FadeIn::create(3.0f),
    nullptr
));
```

**Comment by minggo** [comment] 2017-01-09 03:06
@danut007ro
Ok, i found the reason. _quad's color will be modified in `Sprite::updatePoly()`
```c++
_polyInfo.setQuad(&_quad);
```
But _quad's color is 255 by default.

Why the resources in cpp-tests can work? It is because _polyInfo and _quad will be the same if a sprite frame doesn't include polygon information. And your resources includes polygon information, so Sprite's _polyInfo will be modified by `Sprite::setSpriteFrame()`
```c++
if (spriteFrame->hasPolygonInfo())
{
    _polyInfo = spriteFrame->getPolygonInfo();
}
```

@ricardoquesada i think there is a problem in `Sprite::updatePoly()`.  _quad's color is not updated in `Sprite::updatePoly()`.

**Comment by minggo** [comment] 2017-01-09 03:11
@ricardoquesada Sprite::updateColor() will modify _polyInfo's color, but it will be replaced by _quad's color in `Sprite::updatePoly()`.

**Comment by ricardoquesada** [comment] 2017-01-09 03:17
@minggo I think I fixed it in my latest patch (the one that reduces the polygons), but I'll try it tomorrow (Monday).

**Comment by minggo** [comment] 2017-01-09 03:20
I merged your PR about  reducing polygons. So did you mean i can try it with v3 latest codes?

**Comment by minggo** [comment] 2017-01-09 03:39
The issue exists in v3 latest codes.

**Comment by ricardoquesada** [comment] 2017-01-10 03:24
PR here: https://github.com/cocos2d/cocos2d-x/pull/17135

**Closed as completed** 2017-01-10 07:37 UTC
