### ISSUE TITLE
ccConfig.h CC_CONSTRUCTOR_ACCESS is public

### ISSUE THREAD

**Issue by Almax27** [cocos2d/cocos2d-x#13678] opened 2015-09-03 16:15 UTC
CC_CONSTRUCTOR_ACCESS comment says default is 'protected', as it should be given the create() paradigm. However the default value is 'public', and was changed to aid binding Sprite3D. Perhaps if Sprite3D is an edge case it should not use the macro?

https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/base/ccConfig.h

Last related change: f4b57511b080591ea39bd04d620f157b970676d6

**Comment by pandamicro** [comment] 2015-09-09 03:07
In fact, it helps with all the classes for JS bindings, if you don't write your game in JS, you can turn it into protected, it won't affect anything. But in JSB, the value must be public.

As we merged Cocos2d-JS into Cocos2d-x in v3.7, this is obligated.

**Comment by Almax27** [comment] 2015-09-09 08:32
@pandamicro if that's the case should we not only define public if bindings are in use? Having protected constructors and init methods when working in c++ enforces the create() paradigm correctly.

```
#ifndef CC_CONSTRUCTOR_ACCESS
  #ifdef CC_ENABLE_SCRIPT_BINDING
    #define CC_CONSTRUCTOR_ACCESS public
  #else
    #define CC_CONSTRUCTOR_ACCESS protected
  #endif
#endif
```

**Comment by pandamicro** [comment] 2015-09-09 09:51
That's a good idea, we can do that

**Comment by pandamicro** [comment] 2015-11-14 15:40
It's done

**Closed as completed by pandamicro** 2015-11-14 15:40 UTC

**Comment by mr746866** [comment] 2018-05-14 18:48
Currently changing the value of `CC_ENABLE_SCRIPT_BINDING` has no effect on the value of `CC_CONSTRUCTOR_ACCESS`. As long as there is a value assigned to `CC_ENABLE_SCRIPT_BINDING`, `CC_CONSTRUCTOR_ACCESS` is always `public`.
```
#ifndef CC_ENABLE_SCRIPT_BINDING
#define CC_ENABLE_SCRIPT_BINDING 0 // CC_CONSTRUCTOR_ACCESS is still public
#endif
```
The problem is the marked line shown below.
```
#ifndef CC_CONSTRUCTOR_ACCESS
  #ifdef CC_ENABLE_SCRIPT_BINDING // #ifdef should be #if
    #define CC_CONSTRUCTOR_ACCESS public
  #else
    #define CC_CONSTRUCTOR_ACCESS protected
  #endif
#endif
```
But changing `#ifdef` to `#if` and changing `CC_ENABLE_SCRIPT_BINDING` to 0 causes a few issues to appear.
1. Calling protected destructor of cocos2d::experimental::FrameBuffer in CCDirector.cpp
2. Calling protected init of cocos2d::Sprite in UISlider.cpp
3. Calling protected destructor of cocos2d::TextureCube in CCCameraBackgroundBrush.cpp

How should these issues be handled?
