### ISSUE TITLE
Crash in GLViewImpl::create

### ISSUE THREAD

**Issue by CodeAndWeb** [cocos2d/cocos2d-x#11889] opened 2015-05-18 11:37 UTC
Cocos2d: 3.6
System: MacOS-X 10.10.3, Retina Imac, AMD Radeon R9 M295X

Callstack:
     0   libsystem_c.dylib              0x00007fff98344152 strlen + 18
     1   libsystem_c.dylib              0x00007fff98388f02 __vfprintf + 4887
     2   libsystem_c.dylib              0x00007fff983b19af __v2printf + 679
     3   libsystem_c.dylib              0x00007fff98396155 _vsnprintf + 596
     4   libsystem_c.dylib              0x00007fff9839620a vsnprintf + 80
     5   org.cocos2dx.LightingDemo      0x000000010647e672 _glfwInputError + 434
     6   org.cocos2dx.LightingDemo      0x00000001064844ab _glfwPlatformGetMonitors + 795
     7   org.cocos2dx.LightingDemo      0x000000010647e875 glfwInit + 117
     8   org.cocos2dx.LightingDemo      0x000000010641461f cocos2d::GLViewImpl::GLViewImpl() + 351
     9   org.cocos2dx.LightingDemo      0x0000000106414655 cocos2d::GLViewImpl::GLViewImpl() + 21
     10  org.cocos2dx.LightingDemo      0x0000000106414786 cocos2d::GLViewImpl::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 86
     11  org.cocos2dx.LightingDemo      0x00000001060f161d AppDelegate::applicationDidFinishLaunching() + 173
     12  org.cocos2dx.LightingDemo      0x0000000106456929 cocos2d::Application::run() + 57
     13  org.cocos2dx.LightingDemo      0x00000001060f1806 main + 54
     14  org.cocos2dx.LightingDemo      0x00000001060ee754 start + 52

It only crashes on the Retina iMac, my other iMac is fine.

Workaround for the issue: Using GLFW lib 3.1.1

**Comment by walzer** [comment] 2015-05-18 12:39
It looks like a crash or an incompatibility between GLFW and your iMac. Thanks for your feedback.
I'm not confidence if we could reproduce this crash here. The whole company have no iMac, but only macbook, mbp 13-inch, mbpr 15-inch and mbpa.

**Comment by praubic** [comment] 2016-02-27 15:04
I had similar crash. It was caused by the fact that I connected a monitor to my mac book (mirrored display). It doesn't occur when the monitor is disconnected or when the mac book is folded/closed while the monitor is connected. Do you have two monitors connected to your mac ?

**Comment by CodeAndWeb** [comment] 2016-02-27 19:10
The problem is indeed related to 2 monitors. I have a Retina iMac with a standard non retina monitor. After removing the external monitor the problems stopped.

**Comment by ricardoquesada** [comment] 2016-06-30 00:30
fixed in https://github.com/cocos2d/cocos2d-x/issues/11748
upgraded to GLFW v3.2

**Closed as completed by ricardoquesada** 2016-06-30 00:30 UTC
Labels: type:bug
