### ISSUE TITLE
ClippingNode does not work correctly on Android

### ISSUE THREAD

**Issue by jooddang** [cocos2d/cocos2d-x#10319] opened 2015-02-01 08:44 UTC
What I've found are that:
- If I add multiple ClippingNode's as a child of a scene, only the last ClippingNode is shown. -> I suspect drawing buffer is overwritten.
- Stencil of the ClippingNode does not work. It means that it does not draw node as I intended.

I tested it on Android 4.4.2 Nexus 7 emulator. On Xcode and iOS simulator, it works well.

**Comment by minggo** [comment] 2015-02-02 08:26
What's your engine version?
Have you enabled stencil buffer?

**Comment by jooddang** [comment] 2015-02-02 20:16
I think it's cocos2d-x-3.4beta0. And, yeah, stencil buffer is not enabled.
D/cocos2d-x debug info(1174): create rendererRecreatedListener for GLProgramState
D/cocos2d-x debug info(1174): Stencil buffer is not enabled.
D/cocos2d-x debug info(1174): create rendererRecreatedListener for GLProgramState
D/cocos2d-x debug info(1174): create rendererRecreatedListener for GLProgramState

I think this log is from ClippingNode::init(Node *stencil) because my code called ClippingNode::create(Node *stencil)..

Still, I don't know why stencil buffer is not enabled on Android while it is on iOS.

**Comment by sulewicz** [comment] 2015-05-06 19:45
I have the same issue on iOS 8.3 and Cocos2DX 3.4.

**Comment by angelvet** [comment] 2015-08-22 10:28
Are there any working workaround to enable stencil buffer on the android emulator?

**Comment by jminht** [comment] 2015-10-20 03:49
i got the same problem.
how is this bug going ?
@jooddang @minggo @sulewicz @angelvet @walzer

**Comment by jooddang** [comment] 2015-10-27 08:11
I couldn't solve the problem on cocos2d-x-3.4beta0. Hope it's resolved on the latest version but I didn't catch up yet.

**Comment by zilongshanren** [comment] 2016-04-05 15:59
@jooddang  Since it a very old issue, I need to bump up it.  could you reproduce this issue on the latest version of cocos2d-x? 

thanks.

**Comment by jooddang** [comment] 2016-04-11 03:22
Hi,
Thanks for your interest. But I'm not working on the project anymore.

On Tuesday, April 5, 2016, 子龙山人 notifications@github.com wrote:

> @jooddang https://github.com/jooddang Since it a very old issue, I need
> to bump up it. could you reproduce this issue on the latest version of
> cocos2d-x?
> 
> thanks.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/cocos2d/cocos2d-x/issues/10319#issuecomment-205869686

## 

Best,
EunKwang

**Comment by zilongshanren** [comment] 2016-04-11 03:26
@jooddang Ok, I will close this issue, feel free to reopen if you have problem again.

**Closed as completed by zilongshanren** 2016-04-11 03:26 UTC
Labels: type:bug
