### ISSUE TITLE
CCFloat ERROR

### ISSUE THREAD

**Issue by colamax** [cocos2d/cocos2d-x#1169] opened 2012-08-10 08:56 UTC
Access to cocos2d-x code from github(gles20)
The new lua template run-time error

LuaCocos2d.cpp
CCFloat not found??

**Comment by minggo** [comment] 2012-08-10 12:18
The pull request https://github.com/cocos2d/cocos2d-x/pull/1170 fixed it.
Thank you for your feedback.

**Comment by colamax** [comment] 2012-08-10 13:14
You the most updated code does not seem to update on LuaCocos2d.cpp

Updated with the latest code project is not running

the same error on LuaCocos2d.cpp CCFloat not found.

**Comment by minggo** [comment] 2012-08-11 08:06
I am sorry about that.
It seems LuaCocos2d.cpp is missing updated.
I have asked the developer to commit the codes.

**Comment by minggo** [comment] 2012-08-11 08:12
The developer has committed the codes, and i have tested the codes.
It works ok on iOS.

Thank you for your feedback.
Sorry again for my careless.

**Comment by walzer** [comment] 2012-08-11 14:31
Hi colamax, I removed CCFloat in the last week, coz it's nothing but just "float". Sorry that I forgot to update the .pkg files.
Please all "CCFloat" with "float" will make it work. I saw this merged pull request https://github.com/cocos2d/cocos2d-x/pull/1170/files has fixed this bug.

**Comment by colamax** [comment] 2012-08-13 02:19
hi all.
   I create a new Lua projects can be compiled .. but after the welcome screen, probably because the empty needle or how reason, the program is run not.I do not know why but you can try, you will understand.

**Comment by minggo** [comment] 2012-08-13 02:41
What platform did you create a Lua project for?

**Comment by colamax** [comment] 2012-08-13 02:45
IOS

**Comment by donaldalanmorrison** [comment] 2012-09-24 06:54
@colamax What specific error messages do you get?  Can you take a screenshot if the problem is difficult to describe?

**Closed as completed** 2013-01-13 19:07 UTC
