### ISSUE TITLE
3.6 cpp-test ios ogg play2d error

### ISSUE THREAD

**Issue by wulei** [cocos2d/cocos2d-x#12527] opened 2015-06-25 04:57 UTC
Error log:
void cocos2d::experimental::AudioCache::readDataTask(): ExtAudioFileOpenURL FAILED, Error = 1954115647

**Comment by volzhs** [comment] 2015-07-11 17:53
I had same problem.
Any update for this?

**Comment by WenhaiLin** [comment] 2015-07-13 06:03
@volzhs Could you provide an audio file for reproduced this issue?

**Comment by volzhs** [comment] 2015-07-13 06:20
![menu ogg](https://cloud.githubusercontent.com/assets/8281454/8643751/de0f9748-2972-11e5-8f3b-15056fe5e971.jpg)

I uploaded ogg file with jpg file extension. just rename it.

**Comment by stkach** [comment] 2016-01-11 16:49
@pandamicro , @WenhaiLin 
Hi guys. Are there any updates regarding OGG support for AudioEngine for iOS.
It currently is using OpenAL behind the back that doesn't support OGG, so I can't see OGG iOS support in the latest cocos2dx revision.
Is there any free/non-commercial file format that is supported for all the platforms with experimental::AudioEngine, besides wav (it's too big for acceptable quality)? (mp3 and AAC seem to require licenses for distribution since recent times) or we should maintain separate audio formats for each platforms: Android/WP8.1 - ogg, iOS - ima4?

Best Wishes,
Serhii

**Comment by ricardoquesada** [comment] 2016-07-06 20:50
you should try to use the native formats... they use, when available, the hardware decoder. faster to decode it, and consumes less battery.

ideally you should have all your music files in a certain format, and then have a script that convert those files to native formats.

Adding .ogg support for iOS is possible. you should only compile libvorbis and you have it, but it won't be a native format and it will have all the above mentioned problems.

closing it as won't fix. If someone has any other reason to add them, please let us know. thanks.

**Closed as completed by ricardoquesada** 2016-07-06 20:50 UTC
Labels: type:bug, platform:ios
