### ISSUE TITLE
FontAtlas ReferenceCount problem ?? 

### ISSUE THREAD

**Issue by WhiteLionGame** [cocos2d/cocos2d-x#14390] opened 2015-11-16 00:34 UTC
I do not know why the increase ReferenceCount.

code :  

``` c++
void TextBMFontReader::setPropsWithFlatBuffers(cocos2d::Node *node, const flatbuffers::Table *textBMFontOptions)
    {
...
...
        switch (cmfType)
        {
            case 0:
            {
                if (FileUtils::getInstance()->isFileExist(path))
                {
                    FontAtlas* newAtlas = FontAtlasCache::getFontAtlasFNT(path); // --> FontAtlas ReferenceCount ++1
                    if (newAtlas)
                    {
                        fileExist = true;
                    }
                    else
                    {
                        errorContent = "has problem";
                        fileExist = false;
                    }
                }
                //else
                //{
                //    errorContent = "missed";
                //    fileExist = false;
                //}
                break;
            }

            default:
                break;
        }
        if (fileExist)
            labelBMFont->setFntFile(path); --> FontAtlas ReferenceCount ++1

...
...
```

why ReferenceCount ++2 ?
I think ReferenceCount ++1..

**Comment by ricardoquesada** [comment] 2016-06-21 22:10
Please add the code the reproduce this bug. it is not clear what should be the expected behavior.
Just remember that `FontAtlasCache::getFontAtlasFNT` is a cache.

**Comment by minggo** [comment] 2016-08-04 03:36
close this issue since cocos studio is canceled

**Closed as completed by minggo** 2016-08-04 03:36 UTC
