### ISSUE TITLE
Bug: Audio Engine Freezes game on Android 5.1.1

### ISSUE THREAD

**Issue by tapblaze** [cocos2d/cocos2d-x#15206] opened 2016-03-07 21:32 UTC
Running on Cocos2d-x Version 3.8.1 and sometimes game will freeze on Android 5.1.1 device with following logcat:

`03-08 00:15:28.213: E/libOpenSLES(2618): frameworks/wilhelm/src/android/AudioPlayer_to_android.cpp:410: pthread_mutex_lock_timeout_np returned 110`

**Comment by minggo** [comment] 2016-04-26 07:05
How to reproduce it?

**Comment by BlackStar0313** [comment] 2016-05-13 11:58
i get this all the time ,and have been searching this problem a few days .
i try to replace audio engine at version v3.10, but also timeout.
play my game a few min , maybe 10min?  and play many sounds at the same time. maybe that's the reason? 
Nexus6   , Android 6.0   and  kindle fire os 5.1.2
http://www.cocoachina.com/bbs/read.php?tid-1679095.html

**Comment by fuyifan** [comment] 2016-05-13 17:02
you can try it on any mi box小米盒子. play the same audio frequently the process will be locked. very easy to repriduce.@minggo

**Comment by minggo** [comment] 2016-06-23 08:05
@dumganhar please take a look as you are fixing audio engine issue.

**Comment by dumganhar** [comment] 2016-06-23 08:11
OK, I will investigate this issue.

**Comment by dumganhar** [comment] 2017-03-21 08:47
I think this issue was fixed in v3.14. Please have a test.
Therefore, I closed this issue. If you still met this issue, feel free to open it again. Thanks.

**Closed as completed by dumganhar** 2017-03-21 08:47 UTC
