### ISSUE TITLE
Can you provide pixel data access to Texture2D [read only]

### ISSUE THREAD

**Issue by pandamicro** [cocos2d/cocos2d-x#11349] opened 2015-04-09 03:33 UTC
The Texture2D contains all the pixel data, there is some developer needs to access them to implement some feature.

For example: 
User need to detect touch based on real outline of a sprite which contains transparent pixels. So the current solution can only be render the texture onto a render context and then retrieve the CCImage from it. At last the pixel data can be read. But it's a very consuming solution.

In fact, Texture2D hold all the pixel data itself, so I think a read only access function should be provided. What do you think ?

**Comment by WenhaiLin** [comment] 2015-04-09 03:45
Texture2D not contains all the pixel data.

**Comment by pandamicro** [comment] 2015-04-09 16:30
Why not ?

**Comment by perminovVS** [comment] 2015-04-11 13:16
You can use VolatileTextureMgr( need enable CC_ENABLE_CACHE_TEXTURE_DATA), and add the desired data in it. Or directly use Texture2D::getName() and glGetTexImage

**Comment by kawaiSky** [comment] 2015-04-13 08:09
is glGetTexImage supported in OpenGL/ES?

**Comment by perminovVS** [comment] 2015-04-13 09:04
@kawaiSky no. But issue not mobile only. Someone enough and this

**Comment by walzer** [comment] 2015-04-24 03:11
I would close this issue.

@pandamicro, for the requirement you mentioned, we're adding `SpritePolygon`. Open GLES has no API to read the texture data back, while maintaining the image data in CCImage will consume double size of memory, this is unacceptable.

**Comment by walzer** [comment] 2015-04-24 05:57
# #11584

**Comment by 0xJimmyBeh** [comment] 2015-04-24 13:28
Does this can help on the glGetTexImage issue on OpenGLES?
https://github.com/apitrace/apitrace/issues/70

**Comment by 0xJimmyBeh** [comment] 2015-04-26 07:02
@walzer 

> while maintaining the image data in CCImage will consume double size of memory

How about declare a global cache variable to enable/disable the image data caching in CCImage?

The cache implementation can apply to all CCImage or by specific when creating CCImage.
- For who need all CCImage to be cached and accessing the image data, they can enable the global cache variable.
- For who need certain CCImage to be cached, they just pass true to the cache variable when creating the CCImage.

The CCImage global cache variable is disable by default.
So this won't affect the performance of engine.
But for who needed to use it, just remind them about the double size of memory consumption.

Thanks.

**Comment by perminovVS** [comment] 2015-04-26 07:20
@Zinitter can use VolatileTextureMgr( need enable CC_ENABLE_CACHE_TEXTURE_DATA), and add the desired data in it.

**Comment by 0xJimmyBeh** [comment] 2015-04-26 07:28
@perminovVS 
Thanks for your reply.

I have no idea how to use this VolatileTextureMgr, can you give some guide or example of the usage?

**Comment by perminovVS** [comment] 2015-04-26 07:37
@Zinitter need VolatileTextureMgr::addImage for store it, and VolatileTextureMgr::findVolotileTexture for get VolatileTexture data.  VolatileTexture data have Image*. You need change permissions VolatileTextureMgr and VolatileTexture.

**Comment by 0xJimmyBeh** [comment] 2015-04-26 07:44
Does the Image\* is a CCImage?
The problem is CCImage.getData() = null as CCImage is not caching image data.

Unless VolatileTextureMgr data hold the image array bytes.

**Comment by perminovVS** [comment] 2015-04-26 07:49
@Zinitter you add CCImage by key Texture2D*. VolatileTextureMgr save you CCImage.
CCImage.getData() not null

**Comment by 0xJimmyBeh** [comment] 2015-04-26 08:31
@perminovVS 

I'm not very understand how to do that.

Can you have a look on this ImagePicker?
https://github.com/qiankanglai/ImagePicker

I'm using this to pick an image from device photo gallery.
By default, it return a texture2d which can create a CCSprite.
But the return texture don't have image array bytes.

So I have tried modify it to return CCImage, but the CCImage.getData() is null too.

In this case, i can return Texture2d or CCImage.
How can i get Texture2d key from the return Texture2d?

Should i do VolatileTextureMgr::addImage(returnCCImage)?
Then what to pass in VolatileTextureMgr::findVolotileTexture() to get the data?

I can't find documents on how to use VolatileTextureMgr.

Thanks.

**Comment by perminovVS** [comment] 2015-04-26 08:40
@Zinitter Need correct Image, getData() not null
Change ImagePicker to return Image, and create texture from it Image, and call VolatileTextureMgr::addImage(texture, image)

**Closed as completed** 2017-02-17 08:33 UTC
