### ISSUE TITLE
Call jumpToTop immediately after create a ScrollView, there is no effect

### ISSUE THREAD

**Issue by folgerhu** [cocos2d/cocos2d-x#13668] opened 2015-09-02 07:18 UTC
`Cocos 2d-x v3.8rc0`

Call jumpToTop immediately after create a ScrollView, there is no effect.
I test in cpp-tests UIListVIewTest.cpp

``` cpp
bool UIListViewTest_Vertical::init()
{
    if (UIScene::init())
    {
        ...

        // set items margin
        listView->setItemsMargin(2.0f);

        listView->jumpToTop();

        return true;
    }

    return false;
}
```

**Comment by pandamicro** [comment] 2015-09-09 03:20
@zilongshanren @neokim

**Comment by neokim** [comment] 2015-09-10 02:31
I got the same problem. The cause is that the inner container's position is getting reset twice after it created even though the position was already changed. Resetting places are `onEnter()` and its first `visit()`.

Regarding `onEnter()`, the content size is forced to reset by `Widget::onEnter()` and it leads to reset the inner container's position. It is related to layout component that I don't know well.
Anyway this can be avoided if the list view's `jumpToSomewhere()` is called in `onEnter()` in the parent node of the list view.

Regarding `visit()`, it is because list view refreshes its view lazily. Before its first `visit()`, the list view doesn't know exact size of its inner container. In `doLayout()` by its first `visit()`, it calculates the inner container's size and resets its position.
I'll change list view to refresh every time its item array changes.

**Comment by neokim** [comment] 2015-09-13 13:40
I took an easy solution for this. The list view's lazy refresh is kept. Instead, every `jumpToSomewhere()` function of list view now calls `refreshView()` if it is not up-to-date.

And the problem regarding position reset in `onEnter()` is resolved by adding a guard statement in `ScrollView::setContentSize()` which stops to reset content size with same size.

@zilongshanren I think the guard statement should be in `Widget::setContentSize()`, not in `ScrollView::setContentSize()`. But if I do that, UIButton starts not to work well. Probably, some initialization logics for button are triggered by `setContentSize()`, which should not. I think you need to notice this.

**Comment by zilongshanren** [comment] 2015-09-15 02:47
@neokim 
Yes, the guard statement should be in `Widget::setContentSize()`, I will fix it based on your PR.

**Closed as completed** 2015-09-15 10:28 UTC
