### ISSUE TITLE
TileMaps are broken in master

### ISSUE THREAD

**Issue by ciaranj** [cocos2d/cocos2d-x#518] opened 2011-09-20 07:07 UTC
Hiyah, as reported: http://www.cocos2d-x.org/boards/11/topics/2753?r=3936#message-3936  Tilemaps do not currently work (for me) in master.  Just letting you know in the issue tracker, in case the forum post is missed.  Thanks.

**Comment by donaldalanmorrison** [comment] 2012-09-26 01:20
@dumganhar @walzer @minggo @ciaranj 
The last release tag where master differs from gles20 is cocos2d-1.0.1-x-0.13.0-beta .
If master isn't being maintained (as GLES 1.1 hardware is quickly becoming obsolete), why not close this issue as "end-of-life"?  You could alternatively copy it into a gles11 branch, then delete everything in master, and put a readme.txt in master. :-)

**Comment by godyZ** [comment] 2013-08-22 08:16
@ciaranj The issue is migrated to http://www.cocos2d-x.org/issues/2695

**Closed as completed** 2013-08-22 08:36 UTC
