### ISSUE TITLE
Cocos can't compile Android with APP_STL := c++_static

### ISSUE THREAD

**Issue by dzarowny** [cocos2d/cocos2d-x#13644] opened 2015-08-31 22:24 UTC
Using the Cocos app and prebuilt libraries,  it fails to compile for Android if using `APP_STL := c++_static` in /proj.android/jni/Application.mk

But if we don't use prebuilt libraries it compiles fine.

**Comment by zilongshanren** [comment] 2015-09-01 01:36
@dzarowny  
Currently the `c++_static` is not supported.

**Comment by dzarowny** [comment] 2015-09-01 15:13
Are there plans to support it?  It works fine if using cocos2d-x source,   it is only broken when using Cocos and prebuilt libcocos2d.

**Comment by zeyangl** [comment] 2015-10-12 05:19
Is there a good reason not supporting c++_static? This seems like the foundation while gnustl the feature, since c++_static is a lot better with C++11 compatibility.

**Comment by zilongshanren** [comment] 2015-10-12 05:50
I think @minggo   know better about why we don't support c++_static.

**Comment by minggo** [comment] 2015-10-12 06:14
@dzarowny 
@zeyangl 
A prebuilt version can only support one type of c++ lib. Did you mean we should provide two kinds of prebuilt libcocos2d that using two different c++ libs?

I don't know if cocos2d can compile with c++_static or not. I don't remember if there is a good reason to choose one instead of other one. But cocos2d-x uses gnustl_static from very early version, so we know it works well. You can replace it with c++_static if you like, but it is not fully tested.

**Comment by zeyangl** [comment] 2015-10-12 08:25
I think 2 versions of prebuilt is fair. 3.7 is already working with c++_static when compiled by src. It's the prebuilt sdkbox that's causing linker issues with source-compiled cocos2d-x.

This post also discusses this issue     http://discuss.cocos2d-x.org/t/why-gnustl-static/23780/11

**Comment by zeyangl** [comment] 2015-10-12 08:31
c++_static is more comprehensive than gnustl, for example std::to_string family of methods are nonexistent in gnustl. I think better C++11 support counts as one good reason. Another is because of gnu's strict GPL license. Especially when compiled statically, everything linking against it counts as derivatives. Not to mention the llvm+clang is generally better than gcc mentality. I do remember testing the compiled binary size clang+libstdc++ vs gnu+gnustl in an early cocos version and the former produces slightly smaller binary. So yes, two versions are fair, and it's not an issue for cocos2d-x right now since I can compile from source, but sdkbox breaks when linked against c++_static version of cocos2d-x.

**Comment by ryukbk** [comment] 2016-03-23 09:23
Is there any roadmap for the migration to c++_static on Android? If it's nearer than C++14 support there's this issue for using c++_static with C++14
https://github.com/cocos2d/cocos2d-x/issues/15310

**Comment by minggo** [comment] 2016-03-24 01:55
@ryukbk There is not plan to change it. Do you meet any problem? I think you can change it in your project if you need it.

**Comment by ryukbk** [comment] 2016-03-24 07:15
@minggo With APP_STL := gnustl_static some standard functions such as std::to_string are not available.

**Comment by minggo** [comment] 2016-03-25 02:39
@ryukbk But now cocos2d-x tests use `gnustl_static`, and not meet problem. The reason not using `c++_static` is that it will cause .so bigger. And i am not sure if it is a good time to use c++14, does all compilers support it well?

**Comment by ryukbk** [comment] 2016-03-25 06:57
@minggo I do use Android and iOS, they seem to be fine (gnustl_static for Android and libc++ for iOS) with C++14 and I can build Cocos2d-x without errors.

As for Visual Studio, most C++14 features are available in VS2005 and I think most unsupported features are trivial.
https://msdn.microsoft.com/en-us/library/hh567368.aspx#cpp14table

Some parts of C++14 is stricter than C++11, but it looks it doesn't affect Cocos2d-x itself, so Cocos2d-x libs don't have to use C++14 features, whie I think app code can benefit from C++14 a lot.

**Comment by minggo** [comment] 2016-07-04 07:05
Since the issue is something about SDKBOX, so close it. You can create a new issue about changing to c++_static if needed.

**Closed as completed by minggo** 2016-07-04 07:05 UTC
