### ISSUE TITLE
Cocos2D-X 3.14 breaks some Polygon spritesheets

### ISSUE THREAD

**Issue by dhuang11** [cocos2d/cocos2d-x#17131] opened 2017-01-09 12:00 UTC
- cocos2d-x version: 3.14
- devices test on: Android and iOS both have this issue
- developing environments
   - NDK version: r10e
   - Xcode version: 8.2.1

Steps to Reproduce:

1. Using Cocos2D-X 3.14, some Sprites taken from existing polygon spritesheets show artifacts of other images in the same sheet. This doesn't happen for all images in the polygon spritesheet.
2. Rolling back to Cocos2D-X 3.13.1, the artifacts disappear.

Took a quick look at CCAutoPolygon and CCSprite. It looks like a lot has changed with how the polygon area is determined in a polygon sprite sheet.

**Comment by ricardoquesada** [comment] 2017-01-10 21:08
duplicate of #17119

**Closed as completed by ricardoquesada** 2017-01-10 21:08 UTC
