### ISSUE TITLE
Win32 cpp-tests only show 3/4 black screen and 1/4 white screen

### ISSUE THREAD

**Issue by Rubonnek** [cocos2d/cocos2d-x#16760] opened 2016-10-27 22:02 UTC
- cocos2d-x version: latest code from the git repository, v3 branch
- devices test on: Windows 10
- developing environments
  - VS version: CE 2015

Steps to Reproduce:
1. Build cpp-tests with the latest code from git as of today October 27, 2016

This is what I get:

![win32-latest](https://cloud.githubusercontent.com/assets/8337880/19786897/303cbab8-9c6e-11e6-9802-9b6e1a7b6067.png)

**Comment by Rubonnek** [comment] 2016-10-28 02:37
Compiling a new project with the latest code also reproduces this issue.

**Comment by dumganhar** [comment] 2016-11-02 02:51
@Rubonnek , is this issue caused by shader string? How did you find this?

**Comment by Rubonnek** [comment] 2016-11-02 03:14
@dumganhar Yeah. The removal of the newline characters `\n` triggered this issue in Windows. I also tested the Linux and Android builds and I could not find any problem in those.

What I did to find this issue was to go back in the commit history, i.e. `git log --name-only`, and checking out the commits to see which one triggered the problem. You can test that this issue was introduced in commit `58acca108badfa513860aaff7127f4b13c11c44a`  by doing the following:

``` shell
cd %COCOS2D_X_GIT%/tests/cpp-tests
git checkout 58acca108badfa513860aaff7127f4b13c11c44a
cocos run -p win32
```

Once it compiles the issue will still show up. Now if you checkout the commit right before that one:

``` shell
git checkout 0a31c7de3a9f1c3dba928cb1b09b11dee809e6aa
cocos run -p win32
```

The issue disappears.

**Comment by dumganhar** [comment] 2016-11-02 03:43
@Rubonnek , Thanks.
@minggo ,  I also tested @Rubonnek 's Pull Request on Windows (vs2013, vs2015), Android, iOS, macOS. And they both work fine.

And @Rubonnek  has tested it on Linux platform, I think it's safe to merge @Rubonnek 's patch.

**Comment by minggo** [comment] 2016-11-02 09:43
close this issue since the PR is merged

**Closed as completed by minggo** 2016-11-02 09:43 UTC
