### ISSUE TITLE
touch stops responding on android devices

### ISSUE THREAD

**Issue by deguilardi** [cocos2d/cocos2d-x#17989] opened 2017-06-26 19:12 UTC
- cocos2d-x version: 3.15.1
- devices test on: Galaxy S7, alcatel, galaxy J, moto G 2nd gen, emulator, armeabi, x86 or armeabi-v7a
- developing environments
   - NDK version: 15.0.4075724 (bundle)
   - Xcode version: 8.3.3 (8E3004b)

Steps to Reproduce:

1. Open the app;
2. Do any Director::getInstance()->replaceScene();
3. Touch the screen;

After android discontinued some build commands, we were forced to update cocos2dx to the newest version, because we had to update some libraries too. After that, we started getting a ton of complaints about the screen being unresponsive. At this point 5% (1/20) sessions becomes unresponsive after the first replaceScene call. 

It doesn't matter what device, when the app is closed and reopened 20 times, we'll get at least 1 unresponsive state. 

How we proved this bug:
. We did EventListenerTouchAllAtOnce::create() with a simple CCLOG in the first and second scene.
It works perfectly 100% times in the first scene. After the first replaceScene is called, it works only 80% of all cases in the second scene.
. After downgrading cocos library to 3.14.1 it works 100% again.

**Comment by mandolor** [comment] 2017-07-18 11:19
Encountered same issue yesterday on several devices. Any ideas how to fix?

**Comment by deguilardi** [comment] 2017-07-23 04:48
Wait for the cocos team to see how urgent this is...

**Comment by dumganhar** [comment] 2017-07-27 01:58
Is it relevant to https://github.com/cocos2d/cocos2d-x/issues/18104?

**Comment by deguilardi** [comment] 2017-07-27 02:13
In fact, this #18104 is a totally different thing.
To reproduce this issue, you just need to create two scenes, open the app and navigate from one to another in an android device or android emulator. 1 in every 5 tests the touch will stop working on the second scene no matter what.

**Comment by dumganhar** [comment] 2017-07-27 02:17
@deguilardi , thanks for your feedback. Could you please upload a demo for reproducing this issue?
That will help me save lots of time to check this problem. Thanks.

**Comment by deguilardi** [comment] 2017-07-27 02:24
Just to make it clear, happens with new projects, old projects, devices, emulators, android 4, 5, 6 and 7.

I tried keeping the entire project, replacing the cocos2d folder only. Downgrading to 3.14.1 (keeping ALL config/project files) and this issue specifically is gone now.

@dumganhar I will try to make you a video ASAP.  Does this work?

**Comment by dumganhar** [comment] 2017-07-27 02:36
Yep, please upload the video.
And it's better you could provide the demo which bases on cpp template.

**Comment by mori1234** [comment] 2017-08-01 08:08
cocos2d-x version:  github latest
i have a same issue 
touch is odd

when touch bug
_toAddedListeners not empty()

maby be not work updateListeners(Event* event)
_inDispatch ======= ? not to confirm

===> monday to confirm

**Comment by Y-way** [comment] 2017-08-07 08:13
Encountered same issue when i use new AudionEngin. But i use SimpleAudioEngine everything is OK.
cocos2d-x lua version: 3.15.1

**Comment by mori1234** [comment] 2017-08-09 11:28
I think this issue is related to threads.

I read a file using a thread
****

_inDispatch : 3  skip updateListeners

_toAddedListeners remains EventListener

touch stops responding on android devices



FileUtils::Status FileUtilsAndroid::getContents(const std::string& filename, ResizableBuffer* buffer)
{
    //Director::getInstance()->getEventDispatcher()->dispatchCustomEvent(EVENT_BEFORE_READ_FILE);
  // ---> this thread issue

`Director::getInstance()->getScheduler()->performFunctionInCocosThread([]() {`
		Director::getInstance()->getEventDispatcher()->dispatchCustomEvent(EVENT_BEFORE_READ_FILE);
	});

**Comment by dumganhar** [comment] 2017-08-10 01:22
@mori1234 , did you invoke `getContents` in a sub thread?

**Comment by mori1234** [comment] 2017-08-10 06:18
i use some image thread
Director::getInstance()->getTextureCache()->addImageAsync
and
SimpleAudioEngine preloadEffect used thread

**Comment by dumganhar** [comment] 2017-08-10 06:31
@mori1234 , did it work after applying your patch?
```c++
FileUtils::Status FileUtilsAndroid::getContents(const std::string& filename, ResizableBuffer* buffer)
{
//Director::getInstance()->getEventDispatcher()->dispatchCustomEvent(EVENT_BEFORE_READ_FILE);
// ---> this thread issue

Director::getInstance()->getScheduler()->performFunctionInCocosThread([]() {
Director::getInstance()->getEventDispatcher()->dispatchCustomEvent(EVENT_BEFORE_READ_FILE);
});
```

**Comment by mori1234** [comment] 2017-08-10 09:53
it works fine.
but It is inefficient to read a lot of files use dispatchCustomEvent(EVENT_BEFORE_READ_FILE);
so
i removed all EVENT_BEFORE_READ_FILE;

Java_org_cocos2dx_lib_Cocos2dxEngineDataManager.h
// change
public:
static void onBeforeReadFile(EventCustom* event);


CCFileUtils-android.cpp
// add
#include "platform/android/jni/Java_org_cocos2dx_lib_Cocos2dxEngineDataManager.h"

FileUtils::Status FileUtilsAndroid::getContents(const std::string& filename, ResizableBuffer* buffer)
{
//Director::getInstance()->getEventDispatcher()->dispatchCustomEvent(EVENT_BEFORE_READ_FILE);
// ---> this thread issue
// change
EngineDataManager::onBeforeReadFile(NULL);

**Comment by dumganhar** [comment] 2017-08-11 02:37
@mori1234 , thanks for providing so useful information.
Could you help me to insert a line in `FileUtilsAndroid::getContents`?
```c++
cocos2d::log("thread id: %p", pthread_self());
```

I wanna know whether there is another thread to visit `getContents`. 
After you have tested, please attach logcat output here. Thanks.

**Comment by mori1234** [comment] 2017-08-11 08:13
08-11 17:13:16.052 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.052 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.052 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.057 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.057 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.057 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.057 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.062 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.062 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.377 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.377 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.577 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.582 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.582 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.642 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.647 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.647 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.672 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.672 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.672 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.677 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.697 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.697 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.702 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:16.702 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:17.767 26317-26620/? D/cocos2d-x debug info: thread id: 0x65b19a78
08-11 17:13:17.927 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:17.932 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:17.932 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:18.542 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:18.727 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:18.782 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:18.787 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:18.932 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:18.932 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:18.932 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:21.822 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:21.822 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.442 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.452 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.452 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.487 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.492 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.497 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.502 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.507 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.507 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.512 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.512 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.517 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.577 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.582 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.582 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.637 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.642 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.697 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.732 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.762 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.787 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.817 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.842 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.907 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.942 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:22.997 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.032 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.067 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.127 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.207 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.237 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.262 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.292 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.337 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.417 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.472 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.477 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.487 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.492 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.497 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.502 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.507 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.517 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.517 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.522 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.527 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.527 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.537 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.542 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.542 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.542 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.542 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.547 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.552 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.552 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.557 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.562 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.562 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.567 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.572 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.572 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.572 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.577 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.577 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.582 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.582 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.587 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.592 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.592 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.592 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.592 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.592 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.597 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.597 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.602 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.602 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.602 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.602 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.607 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.607 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.612 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.612 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.617 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.617 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.622 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.627 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.627 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.632 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.632 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.637 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.637 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.647 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.647 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.652 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.657 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.657 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.662 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.667 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.667 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.672 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.677 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.677 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.682 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.682 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.687 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.697 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.697 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.702 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.702 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.702 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.707 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.707 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.707 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.707 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.712 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.712 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.712 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.717 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.717 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.717 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.722 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.722 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.727 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.727 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.732 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.732 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.732 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.732 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.737 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.742 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.742 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.747 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.752 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.752 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.752 26317-26910/? D/cocos2d-x debug info: thread id: 0x6eef6798
08-11 17:13:23.762 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.867 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.872 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.872 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.872 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.872 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:23.877 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:29.952 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:30.032 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:30.032 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:30.037 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:30.037 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:30.047 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:30.052 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:30.057 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:30.057 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:30.062 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:30.062 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:30.072 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:30.077 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:30.077 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30
08-11 17:13:30.077 26317-26510/? D/cocos2d-x debug info: thread id: 0x6201ec30

**Comment by dumganhar** [comment] 2017-08-14 01:37
@mori1234, I looked at the log and found that there were at least 3 threads (0x6201ec30, 0x65b19a78, 0x6eef6798) visiting `FileUtilsAndroid::getContents`.
That's the problem because `EventDispatcher` isn't thread safe.

> i use some image thread
Director::getInstance()->getTextureCache()->addImageAsync
and
SimpleAudioEngine preloadEffect used thread

As you said, you only use `addImageAsync` and `SimpleAudioEngine::preloadEffect`, I have no idea why there were 3 threads visit `getContents`.

Yes, if it's possible that `FileUtilsAndroid::getContents` could be invoked in different threads, this issue should be fixed by `Scheduler::performScheduleInCocosThread` and should check whether it's it is in `cocos` thread.

Could you help to figure out where did `FileUtilsAndroid::getContents` be invoked in 3 threads?
Thanks.

**Comment by dumganhar** [comment] 2017-08-15 03:25
Pull Request: https://github.com/cocos2d/cocos2d-x/pull/18165

**Closed as completed** 2017-08-21 15:29 UTC
