### ISSUE TITLE
[WP8] The project created by Cocos2dx-3.x cannot be launched on Windows Phone 8.1 devices

### ISSUE THREAD

**Issue by tealcwu** [cocos2d/cocos2d-x#8933] opened 2014-10-25 18:59 UTC
Test Environment: 
Windows 8.1 Enterprise English, Visual Studio 2012 Update 4, Windows Phone 8.0 SDK
Test Device: 
HuaWei W1, Windows Phone 8.1, build 8.10.14176.243, English

Repro Steps:
1. Download Cocos2d-x v3.x (we use v3.3rc0 here) from http://cn.cocos2d-x.org/download/.
2. Unzip it when the download is completed, e.g. unzip it to folder D:\cocos2d-x-3.3rc0.
3. In Command Promote, run "D:\cocos2d-x-3.3rc0\tools\cocos2d-console\bin\cocos new -l cpp TestGame" to create a new Cocos2d-x project.
4. Open ..\TestGame\proj.wp8-xaml\TestGame.sln with Visual Studio 2012, select "Device" as target platform and build the solution.
5. When build is finished, deploy it to Windows Phone 8.1 device, run TestGame on test phone.

Expected Result: TestGame can be launched successfully.
Actual Result: Failed to launch TestGame - the app launches but closes immediately. After testing many times, I found TestGame can be launched successfully once in five to ten times. 

More Information:
1. This issue repros to test app cpp-test in ..\cocos2d-x-3.3rc0\build\cocos2d-wp8.sln.
2. This issue repros on all Cocos2d-x 3.x versions.
3. This issue doesn't repro on Cocos2d-x 2.2.5.
4. This issue doesn't repro on Windows Phone Emulators 8.0 and 8.1.
5. This issue is not tested on Windows Phone 8.0 device, because I don't have Windows Phone 8.0 device on hand.

**Comment by edudemy** [comment] 2014-10-26 08:15
+1

**Comment by minggo** [comment] 2014-10-27 02:02
@stammen
Did you know the issue?

**Comment by stammen** [comment] 2014-10-27 02:11
I will investigate

**Comment by minggo** [comment] 2014-10-27 02:29
Thanks.

**Comment by stammen** [comment] 2014-10-27 02:56
It seems there are two shaders that can crash some models of Windows phones

kShaderType_LabelDistanceFieldNormal
kShaderType_LabelDistanceFieldGlow

Please comment out lines 375 to 383 in cocos/renderer/ccglprogramcache.cpp and let me know if it solves your problem.

Also, can you check with the debugger if it is crashing on these lines?

**Comment by stammen** [comment] 2014-10-27 16:33
Did the change I suggested solve the problem?

**Comment by tealcwu** [comment] 2014-10-27 17:07
Crash issue is fixed, but none content is displayed (the cocos2dx picture and label cannot be appeared) on Windows Phone device and emulator. Please refer to the attached screenshot.
![cocos2dx_issue_8933_fix1](https://cloud.githubusercontent.com/assets/359581/4795329/a8513f50-5dfb-11e4-9d2f-36d1a8df5a78.png)

**Comment by stammen** [comment] 2014-10-27 17:23
Thanks for the feedback. Please just comment out lines 383-385 and report if it now works. I have ordered a HuaWei W1 phone so I can repro. Until it arrives,  I appreciate your help.

**Comment by tealcwu** [comment] 2014-10-27 17:45
Just comment line 383-385 works for emulator, but it crashes the device. Does these fixes work on any Windows Phone devices on your hand?

**Comment by stammen** [comment] 2014-10-27 18:15
All of the shader code works uncommented on all of my devices. I have 4 different phones. I ordered a HuaWei W1 to see if I can reproduce the problem. I will have the phone tomorrow.

**Comment by tealcwu** [comment] 2014-10-27 18:27
Cool, so it should be a specified device issue. I think I should order a Lumia phone for testing purpose:)

**Comment by stammen** [comment] 2014-10-27 18:40
Just checking but did you do the following from the cocos2d-x root directory?

downloaddeps.py
git submodule update --init
setup.py (then restart the console)

**Comment by tealcwu** [comment] 2014-10-27 19:07
No, I didn't run these commands. I download cocos2d-x-3.3rc0 from http://cn.cocos2d-x.org/download/ but not from github. I just extract zip file to D:\GitHub\cocos2d-x-3.3rc0.
Do these commands make sense to this issue?

The results after I executed the commands are as below.

*****_command line content begins**_***
D:\GitHub\cocos2d-x-3.3rc0>download-deps.py
*=======================================================
==> Prepare to download external libraries!
==> Not need to update!
*=======================================================
==> Prepare to download lua runtime binaries
==> Not need to update!

D:\GitHub\cocos2d-x-3.3rc0>git submodule update --init
fatal: Not a git repository (or any of the parent directories): .git

D:\GitHub\cocos2d-x-3.3rc0>setup.py

Setting up cocos2d-x...
->Check environment variable COCOS_CONSOLE_ROOT
  ->Search for environment variable COCOS_CONSOLE_ROOT...
    ->COCOS_CONSOLE_ROOT is found : D:\GitHub\cocos2d-x\tools\cocos2d-console\bin

  ->Remove directory "D:\GitHub\cocos2d-x\tools\cocos2d-console\bin" from PATH!

  ->Add directory "D:\GitHub\cocos2d-x-3.3rc0\tools\cocos2d-console\bin" into PATH succeed!

  ->Force update environment variable COCOS_CONSOLE_ROOT
    ->Succeed : COCOS_CONSOLE_ROOT=D:\GitHub\cocos2d-x-3.3rc0\tools\cocos2d-console\bin
->Configuration for Android platform only, you can also skip and manually edit your environment vari
ables

->Check environment variable NDK_ROOT
  ->Search for environment variable NDK_ROOT...
    ->NDK_ROOT is found : D:\Android\sdk\ndk

->Check environment variable ANDROID_SDK_ROOT
  ->Search for environment variable ANDROID_SDK_ROOT...
    ->ANDROID_SDK_ROOT is found : D:\Android\sdk

->Check environment variable ANT_ROOT
  ->Search for environment variable ANT_ROOT...
    ->ANT_ROOT is found : D:\Android\sdk\ant

Please restart the terminal or restart computer to make added system variables take effect
*****_command line content ends**_***

**Comment by minggo** [comment] 2014-10-28 14:17
@tealcwu 
You don't need to do these commands because you are downloading a released zip file.
These commands are needed only if you use github to get cocos2d-x source code.

**Comment by stammen** [comment] 2014-10-28 22:40
My order of the Huawei W1 windows phone just arrived and I am able to reproduce your crash. I will investigate.

**Comment by stammen** [comment] 2014-10-29 05:01
It appears that the ccShader_Label_df.frag and ccShader_Label_df_glow.frag shaders will crash older Windows Phones such as the Huawei W1, I disabled these shaders (and the use of these shaders) and now apps run fine on the phone.

**Comment by stammen** [comment] 2014-10-29 05:07
If you would like to test the work before I make a pull request please do the following from the command console.

git clone https://github.com/MSOpenTech/cocos2d-x.git
cd cocos2d-x
git checkout wp8-shader-fix
git submodule update --init
downloaddeps.py
setup.py (then restart command console)

Please verify that the new code runs on your phone.

Thank you for your detailed bug reports and your help.

**Comment by tealcwu** [comment] 2014-10-29 05:42
Tested with wp8-shader-fix branch, this issue is fixed. Thanks for your quick fix!

**Comment by minggo** [comment] 2014-10-29 08:15
@stammen 
I will close this issue when the commit is merged.
Is it ok?

**Comment by stammen** [comment] 2014-10-31 15:13
Please close this issue as the commit is merged.

**Closed as completed** 2014-10-31 15:25 UTC
