### ISSUE TITLE
drawBatchedTriangles crash on ios 10 and 11

### ISSUE THREAD

**Issue by deguilardi** [cocos2d/cocos2d-x#18509] opened 2017-11-27 05:37 UTC
- cocos2d-x version: 3.14.1
- devices test on: none / live errors only
- developing environments
   - NDK version: N/A
   - Xcode version: 0.1
   - VS version: N/A
   - browser type and version: N/A

How to reproduce:
It's super random, but sometimes the app just freezes in the fist scene.
ItunesConnect / xCode aren't getting this.

The error details are in the following crashalytics link:
http://crashes.to/s/2e19d71defc

**Comment by minggo** [comment] 2018-01-17 05:59
I will close this issue since don't know how to reproduce it and i haven't met it.

**Closed as completed by minggo** 2018-01-17 05:59 UTC

**Comment by rizwangaminations** [comment] 2018-07-18 10:12
Hi, @minggo 

I was also getting this Crash.
But when I disable Admob, crash rate is drastically reduced.
I am currently using cosos2dx 3.16 and AdMob SDK version 7.31.0

Crash logs:
http://crashes.to/s/b93ffc43bb4
http://crashes.to/s/43e4e94cda0
