### ISSUE TITLE
Label not increasing capacity beyond 30 on old Android device

### ISSUE THREAD

**Issue by pyrosphere** [cocos2d/cocos2d-x#8990] opened 2014-11-01 18:11 UTC
While testing a cocos2dx project on an old Android device I noticed long labels were missing letters.

This doesn't happen on my other Android devices, just on this one, a Huawei U8510 IDEOS X3 running Android 2.3.3 - not sure if it's caused by the OS version or something specific on the hardware.

I reproduced the bug on a clean new project with the latest repository version of cocos2dx by replacing the "Hello World" label with:

```
auto label = Label::createWithTTF("ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890", "fonts/Marker Felt.ttf", 24);
```

![missingletters](https://cloud.githubusercontent.com/assets/779064/4872746/2f43d83a-61f1-11e4-8210-b722141d3da4.png)

Everything after the first 30 letters is missing. It seems 30 is the initial capacity of the SpriteBatchNode for labels and, for some reason, on this device the SpriteBatchNode capacity doesn't increase.

Unfortunately I wasn't able to pinpoint the reason of this problem or fix it. As a temporary workaround for a game release I had to increase the initial capacity of the labels, but it's not a solution I would recommend.

**Comment by minggo** [comment] 2014-11-03 01:46
What's your engine version?

**Comment by pyrosphere** [comment] 2014-11-03 10:27
3.3rc0 from github

**Comment by WenhaiLin** [comment] 2014-12-11 05:55
@pyrosphere Are there any other devices can reproduce this issue? We don't have Huawei U8510 IDEOS X3

**Comment by pyrosphere** [comment] 2014-12-11 08:33
I don't know on what other devices this happens - I only have 3 different android devices. I'm not even sure if this is caused by the device or by the Android version since this is the only one I have running 2.x. Sorry I couldn't be of more help.

**Comment by stnguyen** [comment] 2015-03-05 14:13
I'm having the same issue. It's happening on "Samsung Galaxy Gio" and "Nexus S" devices running 2.3.
Please help. I'm using cocos2d-x 3.2 btw

**Comment by WenhaiLin** [comment] 2015-03-09 03:16
I can't reproduce this issue on the devices here:
1.samsung GT-I9100, Android 2.3.6
2.MEIZU MX3,Android 4.4
3.XIAOMI MI 3,Android 4.4.4
4.HTC Nexus 9, Android 5.0.2

I will try to test this issue on more devices.

**Comment by zilongshanren** [comment] 2015-08-18 04:04
can't reproduce, so I just close it here. If anyone have this issue again, feel free to reopen it .

**Closed as completed** 2015-08-18 04:03 UTC
