### ISSUE TITLE
Spine: issue with extending since 3.8

### ISSUE THREAD

**Issue by IgorMats** [cocos2d/cocos2d-x#13973] opened 2015-09-21 08:30 UTC
Hi guys! I notice that Spine extending don't work since 3.8 in JSB. What happens?

**Comment by IgorMats** [comment] 2015-09-22 12:31
Hi @pandamicro and @jianglong0156! Any news? Just asking you coz this issue very important for me coz we can't build old version for iOS 9 (xCode 7). I can't find where is the problem by myself.

**Comment by jianglong0156** [comment] 2015-09-23 07:01
@IgorMats  yes, I show the problem as you said. There is a error in the console "invalid native object", it's may be the c++ object is autoRelease without  index， are you the same problem with me.

**Comment by IgorMats** [comment] 2015-09-23 07:11
@jianglong0156 yes, this is a problem. I can't find where is mistake. Help me please.

**Comment by jianglong0156** [comment] 2015-09-23 09:08
i'm finding the error. it's very strange. which version are you use before.

**Comment by IgorMats** [comment] 2015-09-23 14:00
@jianglong0156 with 3.7 it's works perfect!

**Comment by IgorMats** [comment] 2015-09-23 14:35
@jianglong0156 I noticed that in **v. 3.7** JSB is called empty constructor of `SkeletonAnimation` but in **v. 3.8** all constructors of `SkeletonAnimation` is binded (because it's `public`).

In `sp.SkeletonAnimation.prototype._ctor` function (called after **this._super(json, atlas, scale)**) it looks all working fine but in `ctor` function **NOT**. I can't explain this behavior :(

**Comment by IgorMats** [comment] 2015-09-23 14:39
The same issue at **cocos2d-js** repo: https://github.com/cocos2d/cocos2d-js/issues/1800

**Comment by IgorMats** [comment] 2015-09-24 07:09
@pandamicro sorry, can you take your look on it? It's hard to find a mistake :(

**Comment by jianglong0156** [comment] 2015-09-24 09:19
@IgorMats  sorry for reply latter. i have already found the error. it's a binding bug in spine ctor function. I will fix it, and send the pr soon.

**Comment by jianglong0156** [comment] 2015-09-24 14:58
@IgorMats it's the fix pr. you can run the generate.py in tools/tojs , generate the spine cpp,
or you can replace the code in jsb_cocos2dx_spine_auto.cpp first

```
bool js_cocos2dx_spine_SkeletonAnimation_ctor(JSContext *cx, uint32_t argc, jsval *vp)
{
    JS::CallArgs args = JS::CallArgsFromVp(argc, vp);
    JS::RootedObject obj(cx, args.thisv().toObjectOrNull());
    bool ok = true;
    spine::SkeletonAnimation* cobj = NULL;

    do {
        if (argc == 1) {
            spSkeletonData* arg0 = nullptr;
            #pragma warning NO CONVERSION TO NATIVE FOR spSkeletonData*
            ok = false;
            if (!ok) { ok = true; break; }
            cobj = new (std::nothrow) spine::SkeletonAnimation(arg0);
            cocos2d::Ref *_ccobj = dynamic_cast<cocos2d::Ref *>(cobj);
            if (_ccobj) {
                _ccobj->autorelease();
            }


            js_proxy_t* p = jsb_new_proxy(cobj, obj);
            AddNamedObjectRoot(cx, &p->obj, "spine::SkeletonAnimation");
        }
    } while(0);

    do {
        if (argc == 2) {
            spSkeletonData* arg0 = nullptr;
            #pragma warning NO CONVERSION TO NATIVE FOR spSkeletonData*
            ok = false;
            if (!ok) { ok = true; break; }
            bool arg1;
            arg1 = JS::ToBoolean(args.get(1));
            cobj = new (std::nothrow) spine::SkeletonAnimation(arg0, arg1);
            cocos2d::Ref *_ccobj = dynamic_cast<cocos2d::Ref *>(cobj);
            if (_ccobj) {
                _ccobj->autorelease();
            }


            js_proxy_t* p = jsb_new_proxy(cobj, obj);
            AddNamedObjectRoot(cx, &p->obj, "spine::SkeletonAnimation");
        }
    } while(0);

    do {
        if (argc == 0) {
            cobj = new (std::nothrow) spine::SkeletonAnimation();
            cocos2d::Ref *_ccobj = dynamic_cast<cocos2d::Ref *>(cobj);
            if (_ccobj) {
                _ccobj->autorelease();
            }


            js_proxy_t* p = jsb_new_proxy(cobj, obj);
            AddNamedObjectRoot(cx, &p->obj, "spine::SkeletonAnimation");
        }
    } while(0);

    do {
        if (argc == 2) {
            std::string arg0;
            ok &= jsval_to_std_string(cx, args.get(0), &arg0);
            if (!ok) { ok = true; break; }
            spAtlas* arg1 = nullptr;
            #pragma warning NO CONVERSION TO NATIVE FOR spAtlas*
            ok = false;
            if (!ok) { ok = true; break; }
            cobj = new (std::nothrow) spine::SkeletonAnimation(arg0, arg1);
            cocos2d::Ref *_ccobj = dynamic_cast<cocos2d::Ref *>(cobj);
            if (_ccobj) {
                _ccobj->autorelease();
            }


            js_proxy_t* p = jsb_new_proxy(cobj, obj);
            AddNamedObjectRoot(cx, &p->obj, "spine::SkeletonAnimation");
        }
    } while(0);

    do {
        if (argc == 3) {
            std::string arg0;
            ok &= jsval_to_std_string(cx, args.get(0), &arg0);
            if (!ok) { ok = true; break; }
            spAtlas* arg1 = nullptr;
            #pragma warning NO CONVERSION TO NATIVE FOR spAtlas*
            ok = false;
            if (!ok) { ok = true; break; }
            double arg2 = 0;
            ok &= JS::ToNumber( cx, args.get(2), &arg2) && !isnan(arg2);
            if (!ok) { ok = true; break; }
            cobj = new (std::nothrow) spine::SkeletonAnimation(arg0, arg1, arg2);
            cocos2d::Ref *_ccobj = dynamic_cast<cocos2d::Ref *>(cobj);
            if (_ccobj) {
                _ccobj->autorelease();
            }


            js_proxy_t* p = jsb_new_proxy(cobj, obj);
            AddNamedObjectRoot(cx, &p->obj, "spine::SkeletonAnimation");
        }
    } while(0);

    do {
        if (argc == 2) {
            std::string arg0;
            ok &= jsval_to_std_string(cx, args.get(0), &arg0);
            if (!ok) { ok = true; break; }
            std::string arg1;
            ok &= jsval_to_std_string(cx, args.get(1), &arg1);
            if (!ok) { ok = true; break; }
            cobj = new (std::nothrow) spine::SkeletonAnimation(arg0, arg1);
            cocos2d::Ref *_ccobj = dynamic_cast<cocos2d::Ref *>(cobj);
            if (_ccobj) {
                _ccobj->autorelease();
            }


            js_proxy_t* p = jsb_new_proxy(cobj, obj);
            AddNamedObjectRoot(cx, &p->obj, "spine::SkeletonAnimation");
        }
    } while(0);

    do {
        if (argc == 3) {
            std::string arg0;
            ok &= jsval_to_std_string(cx, args.get(0), &arg0);
            if (!ok) { ok = true; break; }
            std::string arg1;
            ok &= jsval_to_std_string(cx, args.get(1), &arg1);
            if (!ok) { ok = true; break; }
            double arg2 = 0;
            ok &= JS::ToNumber( cx, args.get(2), &arg2) && !isnan(arg2);
            if (!ok) { ok = true; break; }
            cobj = new (std::nothrow) spine::SkeletonAnimation(arg0, arg1, arg2);
            cocos2d::Ref *_ccobj = dynamic_cast<cocos2d::Ref *>(cobj);
            if (_ccobj) {
                _ccobj->autorelease();
            }


            js_proxy_t* p = jsb_new_proxy(cobj, obj);
            AddNamedObjectRoot(cx, &p->obj, "spine::SkeletonAnimation");
        }
    } while(0);

    if (cobj) {
        if (JS_HasProperty(cx, obj, "_ctor", &ok) && ok)
                ScriptingCore::getInstance()->executeFunctionWithOwner(OBJECT_TO_JSVAL(obj), "_ctor", args);

        args.rval().set(OBJECT_TO_JSVAL(obj));
        return true;
    }
    JS_ReportError(cx, "js_cocos2dx_spine_SkeletonAnimation_ctor : wrong number of arguments");
    return false;
}
```

**Comment by IgorMats** [comment] 2015-09-24 18:37
@jianglong0156 it's great! You are awesome!

@jianglong0156  and @pandamicro, please, take your look at the file: `cocos/scripting/js-bindings/script/jsb_spine.js`. This file should be refactored according to the latest changes.

@pandamicro, you also promise me to fix this issue: https://github.com/cocos2d/cocos2d-x/issues/12925
I guess that code:

```
#if CC_ENABLE_SCRIPT_BINDING
    if (_scriptType == kScriptTypeJavascript && ScriptEngineManager::sendNodeEventToJSExtended(this, kNodeOnEnter)) return;
#endif
```

is fixed my issue, **BUT NOT**. This bug is os annoying and moves from version to version :((
Can you @pandamicro do something with it?

Thank you, guys!

**Comment by pandamicro** [comment] 2015-09-25 03:50
@IgorMats Sorry for the bug caused by our changes, I have talked with @jianglong0156 , a unnoticed bug in bindings-generator had been triggered, now his fix have been merged, he will add a test case for it.

I will take a look at #12925 too.

**Closed as completed** 2015-11-10 16:13 UTC
Labels: type:bug, script:jsb
