### ISSUE TITLE
cocos console support wp template

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8932] opened 2014-10-25 07:52 UTC
Please refer to #8926 for detail information.

**Comment by minggo** [comment] 2014-10-28 15:30
@natural-law 
When can you finish it?
I think it will not take too much time.

**Comment by natural-law** [comment] 2014-10-29 01:25
@minggo, Do you mean only the cpp template? What about the lua templates?

**Comment by minggo** [comment] 2014-10-29 02:20
Now, lua doesn't support WP platform.
We will add them after lua is supported.

**Comment by natural-law** [comment] 2014-10-29 02:23
OK. I will finish this issue in one or two days.

**Comment by minggo** [comment] 2014-10-29 02:37
Ok.

**Comment by stammen** [comment] 2014-10-29 04:58
Please fix the win-8.1-universal template, The WP8 template works fine.

**Comment by takaaptech** [comment] 2014-10-30 17:18
@minggo can you please estimate when will we support wp8 with LUA? Thank so much!

**Comment by stammen** [comment] 2014-10-30 17:20
The cocos2d-x community added lua support for WP8 in 2.x. Which developer did the work?

**Comment by minggo** [comment] 2014-10-31 01:36
@takaaptech 
We can add support in v3.4.

**Comment by natural-law** [comment] 2014-11-10 02:48
@stammen
I'm the developer of cocos2d-console. I have supported building the wp8 project in template with console. But I have encountered a problem when I building the `cpp-empty-test` with `cocos` command.

The implementation of cocos2d-console is : using `devenv` to compile the wp8 project.
The problem is :
1. I created a new project from template. Then compile the wp8 project with command:
`"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.com" "z:\MyWork\cocos2d-x\tools\cocos2d-console\bin\MyCppGame\proj.wp8-xaml\MyCppGame.sln" /Build "Debug|x86" /Project "MyCppGame"`
It works OK.
2. When I compiling the `cpp-empty-test` project with the command:
`"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.com" "z:\MyWork\cocos2d-x\tests\cpp-empty-test\..\..\build\cocos2d-wp8.sln" /Build "Debug|x86" /Project "cpp-empty-test"`
It's failed with error:
`Visual Studio has encountered an unexpected error.`

@stammen
Could you please help me to check the problem? I've no idea why it's encounter the error. Thank you very much!

**Comment by natural-law** [comment] 2014-11-17 08:23
@stammen,
The issue has been fixed in this PR: https://github.com/cocos2d/cocos2d-x/pull/9137 .

But there are two problems I encountered have not been solved:
1. The one I mentioned before: I can't compile the wp8-xaml project of `cpp-empty-test` & `cpp-tests`.
2. I've no idea how to deploy & run the win8.1-universal project with command line. 

I will spend more time to solve them. If you have any suggestions for the problems, please tell me. Thank you!

**Comment by stammen** [comment] 2014-11-17 17:02
I will be making a pull request that fixes cocos2d-wp8.sln.

This now works

"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.com" ".\build\cocos2d-wp8.sln" /Build "Debug|Win32" /Project "cpp-empty-test"

"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.com" ".\build\cocos2d-wp8.sln" /Build "Debug|Win32" /Project "cpp-tests"

You can build universal app version from devenv using:

"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.com" ".\build\cocos2d-win8.1-universal.sln" /Build "Debug|Win32" /Project "cpp-tests.WindowsPhone"

"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.com" ".\build\cocos2d-win8.1-universal.sln" /Build "Debug|Win32" /Project "cpp-tests.Windows"

**Comment by natural-law** [comment] 2014-11-18 03:08
@stammen
Thanks for your excellent work. I've tried your PR, it's worked.

On the other hand, I think you misunderstood the 2nd problem.
I can compile the win8.1-universal projects (Both Windows & WindowsPhone can be compiled by command line).

 The problem is :  I don't know how to deploy & run the application by command line.

**Closed as completed** 2014-11-18 03:09 UTC

**Comment by stammen** [comment] 2014-11-18 03:50
Take a look at 

http://msdn.microsoft.com/en-us/library/dn632395.aspx
