### ISSUE TITLE
use luajit 2.1.0-beta2

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#16365] opened 2016-08-15 01:31 UTC
now we use 2.1.0-alpha on iOS and use lua for Android 64-bit, we should upgrade to use luajit 2.1.0-beta2.

Edit: and some platforms use lua, should change to use luajit too.

**Comment by minggo** [comment] 2016-08-16 01:46
@dumganhar [added luajit 2.10-beta2 for Android arm64](https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/246) to fixed the bug caused by `ByteCodeEncryptTest` in `lua-tests`. So the things left are:
- update luajit to 2.1.0-beta2 for iOS, Mac and win32
- use luajit 2.1.0-beta2 instead of lua for other platforms

**Comment by ricardoquesada** [comment] 2016-08-17 23:04
@minggo I've just updated the makefile to use LuaJIT instead of Lua for Android64.

I tested it, and now lua-tests works Ok.

**Comment by minggo** [comment] 2016-08-18 01:00
Yep, it is fixed in v3.13 branch. And @dumganhar thought it is better to fix the issue in 3.13 and he is working on it. So i assign it to @dumganhar ?

**Comment by ricardoquesada** [comment] 2016-08-18 01:18
some updates:

I recompiled myself luajit-2.1-beta for:
- android (all version, using ndk12b)
- ios (all versions)
- mac (all versions)

and it only works on ios.
but it doesn't work on android (both 32-bit and 64-bit versions) and mac.

Not sure if we need to re-generate the bytecodes or not.
I traced the problem until this file:
https://github.com/cocos2d/cocos2d-x/blob/v3/tests/lua-tests/src/ByteCodeEncryptTest/ByteCodeEncryptTest.lua

and it has an special case for ios. perhaps we need to do the same for android and mac.

@dumganhar @minggo any idea?
@dumganhar how did you compile luajit 2.1-beta2 for android? because it doesn't work for me now. thanks!

**Comment by ricardoquesada** [comment] 2016-08-18 01:31
@minggo yes, if you want to assign it to him, Ok for me.
@dumganhar I added my some code here:
https://github.com/cocos2d/cocos2d-x/pull/16384

**Comment by dumganhar** [comment] 2016-08-18 02:54
I have updated it to 2.1.0-beta2, and updated cocos2d-console, 3rd-party-libs-bin, 3rd-party-libs-src. cocos2d-console could generate 64bit luajit bytecode either.

I didn't notice that this issue was assigned to @ricardoquesada .
Please check my work:

cocos2d-console: https://github.com/cocos2d/cocos2d-console/pull/368
3rd-party-libs-bin: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/247
3rd-party-libs-src: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/pull/124

I have tested them on Win32, Mac, iOS, Android platforms.
 But, currently, my `libs-bin` PR couldn't be merged.

TBD:
cocos2d-console command `cocos compile` should support to generate both 32bit & 64bit luajit bytecode if arm & arm64 are both valid. Sorry for that I could not continue these two days, I gotta do other work. :(

**Comment by ricardoquesada** [comment] 2016-08-18 06:13
@dumganhar how did you compile for android?
because the version that I compiled doesn't work ( https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/commit/6aa7b0fbe6a267292315581d331a6550556b0d92 ) with encrypted bytecodes. But the one that was commited by you, worked ok.
thanks.

**Comment by dumganhar** [comment] 2016-08-18 06:16
@ricardoquesada , please refer to this PR: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/pull/124/files

And the make file: https://github.com/dumganhar/cocos2d-x-3rd-party-libs-src/blob/9ee955114e6e94e2c615986d60ef73b88b542630/contrib/src/luajit/rules.mak

**Comment by ricardoquesada** [comment] 2016-08-18 06:24
@dumganhar yes, yes. I was using those changes.
which NDK did you use? I used ndk12b. thanks.

**Comment by minggo** [comment] 2016-08-18 06:28
@ricardoquesada thanks
@dumganhar please fix the conflicts

**Comment by dumganhar** [comment] 2016-08-18 06:29
@ricardoquesada 
I used `ndk 12b` too.  I don't know what `encrypted bytecodes` means. Could you explain how to generate encrypted bytecode?
I used 

```
cocos luacompile -s src -d out_dir --bytecode-64bit
```

 to generate bytecode and tested.

**Comment by dumganhar** [comment] 2016-08-18 06:43
@ricardoquesada , I assumed that you used the following command to generate `encrypted bytecode`:

```
cocos luacompile -s src -d out_dir --encrypt -k=xxx -b=yyy
```

If you meant this, I didn't test it since I think encrypt logic is independent of luajit version.

**Comment by ricardoquesada** [comment] 2016-08-18 07:20
I'll try that command. thanks.

**Comment by halx99** [comment] 2016-08-18 10:03
@minggo I relalized that recently, you are updgrade luajit to 2.1.0 beta2
I just tried it at win32 & android a short time, and there have a problem of the luajit-2.1.0 beta2:

When our game use the bytecode of luajit-2.1.0, It will gone to deadblock frequently on both win32 & android platform.

**Comment by halx99** [comment] 2016-08-18 10:04
And I rollback to luajit 2.0.4, the problem has been solved.

**Comment by minggo** [comment] 2016-08-18 10:44
@halx99 are you should it is a problem of luajit, could you please give some test case to reproduce it?

**Comment by minggo** [comment] 2016-08-18 10:46
@halx99 and we use 2.1.0 alpha for a long time on iOS.

**Comment by halx99** [comment] 2016-08-18 10:59
I use it in our game, It's not easy to provide test case directly, I will provide the libs I use on win32 & android later.

**Comment by halx99** [comment] 2016-08-18 11:14
I realized that, when use luajit2.1.0 beta2, It will cause some win32 exception from KernelObject.dll, I'll test again and provide detail exception logs later.

**Comment by ricardoquesada** [comment] 2016-08-18 23:49
@dumganhar 
Actually I couldn't make it work :(
The thing is that in our repo there are some already compiled files here: https://github.com/cocos2d/cocos2d-x/tree/v3/tests/lua-tests/src/ByteCodeEncryptTest
- ByteCodeAndEncryptTest-arm64.luac
- ByteCodeAndEncryptTest.luac
- ByteCodeTest-arm64.luac
- ByteCodeTest.luac

But I don't know what are the original source files. So, when I try "lua-tests" it fails because it can't run the "ByteCodeTest" test.

It gives me this error on Mac (and a similar error on Android):

```
[LUA ERROR] load "ByteCodeEncryptTest/ByteCodeTest.luac", error: syntax error during pre-compilation.
[LUA ERROR] [string "ByteCodeEncryptTest/ByteCodeEncryptTest.lua"]:5: module 'ByteCodeEncryptTest/ByteCodeTest' not found:
    no field package.preload['ByteCodeEncryptTest/ByteCodeTest']ByteCodeEncryptTest/ByteCodeTest.luac: cannot load incompatible bytecode
    no file './ByteCodeEncryptTest/ByteCodeTest.lua'
    no file '/usr/local/share/luajit-2.1.0-beta2/ByteCodeEncryptTest/ByteCodeTest.lua'
    no file '/usr/local/share/lua/5.1/ByteCodeEncryptTest/ByteCodeTest.lua'
    no file '/usr/local/share/lua/5.1/ByteCodeEncryptTest/ByteCodeTest/init.lua'
    no file './ByteCodeEncryptTest/ByteCodeTest.so'
    no file '/usr/local/lib/lua/5.1/ByteCodeEncryptTest/ByteCodeTest.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
```

What I need to do is to recompile `BytecodeTest.lua` but I don't know where that file is.
Anyway, since you are already working on this, probably it is better if you continue with it. I almost have it working... except that I don't where the `ByteCodeTest.lua` and `ByteCodeAndEncryptTest.lua` are.

**Comment by halx99** [comment] 2016-08-19 00:10
As I known, the bytecode must be match luajit-2.1.0beta2, It's not compatible with old version bytecode(such generated by luajit-2.04)

**Comment by ricardoquesada** [comment] 2016-08-19 01:12
@halx99 Ah ha... that explains it. Probably the .luac files that we have in the repo were compiled for luajig-2.0.4, and that's why it is not working for me. But why does it work for iOS? 
Apparently those .luac files were created more than 1 year ago, so I guess they were created for 2.0.4.

**Comment by minggo** [comment] 2016-08-19 01:33
@ricardo yep, we have to update the bytecode, and i haven't updated 3rd-party-library-bin which contains luajit-2.1.0beta2 for all platforms(android arm64 is already updated), and the console haven't be updated to work with 2.1.0beta2. 

I planned to update luajit-2.1.0beta2 in v3.13 but it seems we should do it in next to do more testing.

**Comment by ricardoquesada** [comment] 2016-08-19 01:36
@minggo I already updated all the binaries (except windows). They are in v110:
https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/releases/tag/v3-deps-110

but I need to update those .luac files to make it work. If you have an idea how to re-generate them, it would be great.

**Comment by minggo** [comment] 2016-08-19 01:43
@ricardoquesada yep, you can use latest console:
- and use `cocos luacompile` to generate 32-bit bytecode
- use `cocos luacompile ----bytecode-64bit` to generate 64bit bytecode

**Comment by dumganhar** [comment] 2016-08-19 01:44
@ricardoquesada ,

> [LUA ERROR] load "ByteCodeEncryptTest/ByteCodeTest.luac", error: syntax error during pre-compilation.
> [LUA ERROR] [string "ByteCodeEncryptTest/ByteCodeEncryptTest.lua"]:5: module 'ByteCodeEncryptTest/ByteCodeTest' not found:
>     no field package.preload['ByteCodeEncryptTest/ByteCodeTest']ByteCodeEncryptTest/ByteCodeTest.luac: cannot load incompatible bytecode
>     no file './ByteCodeEncryptTest/ByteCodeTest.lua'
>     no file '/usr/local/share/luajit-2.1.0-beta2/ByteCodeEncryptTest/ByteCodeTest.lua'
>     no file '/usr/local/share/lua/5.1/ByteCodeEncryptTest/ByteCodeTest.lua'
>     no file '/usr/local/share/lua/5.1/ByteCodeEncryptTest/ByteCodeTest/init.lua'
>     no file './ByteCodeEncryptTest/ByteCodeTest.so'
>     no file '/usr/local/lib/lua/5.1/ByteCodeEncryptTest/ByteCodeTest.so'
>     no file '/usr/local/lib/lua/5.1/loadall.so'

Please check this change on v3.13 branch: https://github.com/cocos2d/cocos2d-x/commit/86b8a633f3c5e1bd18f3b2726907aaa0965342a0

Basically, you were not use the correct bytecode for device.
If your executable file(.so) is built with 64bit (arm64-v8a), In ByteCodeTest, you should choose the correct one.

About where are these files from, sorry for that I don't know either.

```
ByteCodeAndEncryptTest-arm64.luac
ByteCodeAndEncryptTest.luac
ByteCodeTest-arm64.luac
ByteCodeTest.luac
```

**Comment by minggo** [comment] 2016-08-19 01:49
@ricardoquesada but i will revert https://github.com/cocos2d/cocos2d-console/pull/368 to release v3.13, and we will make it work after releasing v3.13.

**Comment by ricardoquesada** [comment] 2016-08-19 01:54
@minggo yes, do whatever you think is better for the release.
probably it is better if @dumganhar continues with this, since he is very advanced (he did the windows binaries and I didn't).

what we should try to figure out, is how to regenerate those .luac files... and if we can't we just need to create them from scratch (unless I'm missing something).

**Comment by minggo** [comment] 2016-08-19 02:00
@ricardoquesada yep, indeed everything is ready. I revert it just because we don't do enough testing. So i will do it in next version, and ask @halx99 to do a test with our new luajit lib.

**Comment by ricardoquesada** [comment] 2016-08-19 02:02
@minggo ok.

**Comment by halx99** [comment] 2016-08-19 02:03
@minggo ok

**Comment by halx99** [comment] 2016-08-22 09:43
@minggo Hi, sorry, I just test on win32 again, and the exception gone, I could not confirm why? 
maybe before, I made a 2.1.0beta2 dll with not matched header.
I will continue test on other platform with our project

**Comment by halx99** [comment] 2016-08-22 10:01
@minggo  @ricardoquesada 
Wait...
It still has problem for 2.1.0-beta2, even through, I use luajit2.10-beta2 matched .dll and header:
![e9iq81kb3q 9 l d bvk k](https://cloud.githubusercontent.com/assets/6977319/17850971/49652cba-6892-11e6-8661-765df974f428.png)

**Comment by halx99** [comment] 2016-08-22 10:05
And when I first time call `cocos2d::LuaEngine::getInstance()->executeScriptFile("scripts/src/deploy.lua");`
The exception also occured: `0x769596C2 (KernelBase.dll) (thisapp.exe 中)处的第一机会异常:  0xE24C4A02。`

**Comment by halx99** [comment] 2016-08-22 10:29
I download the the luajit2.1.0-beta2.zip from luajit official website, and compare with my luajit2.1.0-beta2, there are many different source code. And I think the root cause is because I use the developing git version, wen I execute 'git pull' again, There are many source updated. And it seems there is no problem for the lib which provided by yours.

**Comment by minggo** [comment] 2016-08-22 10:39
@halx99 thanks for your information.

**Comment by minggo** [comment] 2016-09-28 03:52
cocos2d console is updated in https://github.com/cocos2d/cocos2d-console/commit/81beb4a2dd41e6b132c09017abd4123b20e02486 and https://github.com/cocos2d/cocos2d-console/commit/8a2e1855721a64e078e96c4937c9c44c1a722a30
tests and template are updated in #16620

**Closed as completed** 2016-09-28 08:46 UTC
Labels: script:lua, platform:android, platform:ios
