### ISSUE TITLE
PreloadEffect on android devices with new version of android

### ISSUE THREAD

**Issue by piotrros** [cocos2d/cocos2d-x#17186] opened 2017-01-13 12:10 UTC
- cocos2d-x version: 3.14
- devices test on: Nexus 6P Android 7.1.1 [Samsung Galaxy A3 (2016) Android 5.1.1 - WORKS FINE]
- developing environments
   - NDK version: r12b

Steps to Reproduce:

1. Add several .ogg to a project and call preloadEffect on them.
2. Watch in logcat how slowly they load (92 small .ogg files took 25 seconds on Nexus 6P).

I've described more details in this post: http://discuss.cocos2d-x.org/t/preloadeffect-very-slow-loading/33946

This is a critical issue. I'm forced to use .wav for now, because of loading time.

**Comment by minggo** [comment] 2017-01-17 01:56
Did you use AudioEngine or SimpleAudioEngine?

**Comment by piotrros** [comment] 2017-01-17 07:20
SimpleAudioEngine

**Comment by minggo** [comment] 2017-01-18 06:28
Why not try to use new audio engine? And could you please provide a test case to reproduce the issue?

**Comment by piotrros** [comment] 2017-01-18 14:15
As I wrote here: http://discuss.cocos2d-x.org/t/preloadeffect-very-slow-loading/33946/8?u=piotrros
audio engine is experimental and it's even more problematic.
Here's simple test project, it uses android studio only (you have to configure path to cocos in build.gradle file):

[PreloadBug.zip](https://github.com/cocos2d/cocos2d-x/files/714090/PreloadBug.zip)

Testing on Nexus 6P:
10 waves: 0.4s
10 oggs: 9s

On very old and slow lenovo tablet (IdeaTab A1000L-F):
10 waves: 2s
10 oggs: 3.5s

These 2 are extremely new fast device vs old and slow
Also add this:  System.out.println("onLoadComplete: " + sampleId);
in onLoadComplete (OnLoadCompletedListener) in Cocos2dxSound.java.
You can click cocos logo on play last sound (if it's not loaded yet it'll say sample not ready).

**Comment by dumganhar** [comment] 2017-01-19 07:11
@piotrros,

We are trying to decoding audio files by ourself rather than OpenSLES API.
Since on android, using OpenSLES API to decode ogg, mp3 to pcm buffer will cause bundle of system issues that we can't fix.

I have submitted a pull request for this (https://github.com/cocos2d/cocos2d-x/pull/17233)
Could you have a try and give me feedback.

SimpleAudioEngine is really slow on some devices, and because it also uses system public SoundPool API, so we couldn't fix it too.

**Comment by rnnbl** [comment] 2017-01-24 09:07
@minggo Converting to the new audio engine is not really an option if you are using the pan parameter which hasn't been build in yet as far as I know.

**Comment by piotrros** [comment] 2017-02-02 14:54
New AudioEngine from @dumganhar is fine, but it's one problem with it: you can only play 16 sounds at one time. It seems to be enough, but not in every case.

I have a music game, which main feature is the piano. Piano has several keys and each note have 2-3 seconds length. It's very easy to play these keys more than 16 times in these 2-3 seconds. When limit is exceeded new sounds won't play at all. You have to wait until some older ones will stop playing, then you can use their place instead.

That's not the case with SimpleAudioEngine (SoundPool), it doesn't have this issue. That's way I cannot switch to new AudioEngine.

**Comment by dumganhar** [comment] 2017-02-03 03:17
> New AudioEngine from @dumganhar is fine, but it's one problem with it: you can only play 16 sounds at one time. It seems to be enough, but not in every case.

@piotrros , you could play 32 instances of sound at the same time by setting `AudioEngine::setMaxAudioInstance(32);`

**Comment by piotrros** [comment] 2017-02-03 08:22
Thanks, it's better now, but it's still pretty easy to bypass limit. Damn, that stupid SoundPool bugs.

**Comment by songtm** [comment] 2017-02-14 12:38
@dumganhar  I upgrade Audio part to 3.14.1, use AudioEngine to play mp3 sound effect also very slow(on Huawei p9 android 7.x),it stuck a while before play the sound, sometimes it may have preload error. I test on other devices I have, it worked perfectly.

> 02-14 18:06:10.203 31547 31571 E AudioPlayerProvider: FileInfo (0xe557eec8), preloadEffect (assets/res/sound/VOICE10002.mp3) failed
02-14 18:06:12.047 31547 31647 I AudioDecoder: Original audio info: numChannels: 1, sampleRate: 44100, bitPerSample: 16, containerSize: 16, 
02-14 18:06:16.572 31547 31571 E AudioPlayerProvider: FileInfo (0xe557e628), preloadEffect (assets/res/sound/VOICE10003.mp3) failed

**Comment by dumganhar** [comment] 2017-02-16 08:38
@songtm, PR (https://github.com/cocos2d/cocos2d-x/pull/17233) was merged.
I think it will resolve the `preload error`  issues.
Please have a try in the latest v3 branch.
BTW, could you please upload `assets/res/sound/VOICE10003.mp3` which is decoded without success?

I closed this issue since i think the bad performance of loading `ogg`, `mp3` files has been fixed in the latest v3 branch. If you still get any `preload` problems, feel free to open it again or create a new issue. :)

**Closed as completed by dumganhar** 2017-02-16 08:38 UTC
Labels: platform:android
