### ISSUE TITLE
zlib include files are now in cocos2d-x/external and cocos2d-x-3rd-party-libs-bin

### ISSUE THREAD

**Issue by stammen** [cocos2d/cocos2d-x#11342] opened 2015-04-08 14:26 UTC
A newer version of zlib include files are in cocos2d-x/external/zlib/include. They also are part of download-deps. When the user uses download-deps the zlib include files in the cocos2d-x/external repo are overwritten. This causes git to think the files have been changed.

The zlib include files should only be in one repo not both.

See issue: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/issues/120

**Comment by minggo** [comment] 2015-04-08 14:44
Yep, we should remove it from cocos2d-x. It is added by mistake.

**Comment by minggo** [comment] 2015-04-08 14:47
@WenhaiLin 
Please fix it.
Thanks.

**Comment by stammen** [comment] 2015-04-08 15:17
@WenhaiLin  Fixed in pr https://github.com/cocos2d/cocos2d-x/pull/11343

**Comment by zilongshanren** [comment] 2015-04-08 23:44
@minggo 
I know the issue now. 
Zlib was commited by CocosRobot. i think we should add zlib to .gitignore such that the CocosRobot won't commit the zlib again. I think I don't commit these files and I have removed it before.

So next time when merging PR of CocosRobot, I think we should pay a eye to it.

**Comment by zilongshanren** [comment] 2015-04-08 23:47
@minggo 
https://github.com/cocos2d/cocos2d-x/pull/11332  This PR shouldn be revert.
@stammen I think your PR shouldn't contain the commit to remove these drity files.

One more thing, the CocosRobot does have some bugs here when the files are not ignored by git and contained in Cocos-3rd-libs.

**Comment by minggo** [comment] 2015-04-09 01:24
@andyque 
I know it is caused by CocosRobot, if i don't merge it, then it will generate new one after merging a PR. The correct way is to fix CocosRobot and remove these files.

**Comment by minggo** [comment] 2015-04-09 02:09
It is fixed in #11347.
Then we will send another PR to remove zlib libs in cocos2d-x.

**Closed as completed** 2015-04-09 05:50 UTC
