### ISSUE TITLE
App was stuck in black all the time when running on android studio emulator

### ISSUE THREAD

**Issue by guoyingtao** [cocos2d/cocos2d-x#17962] opened 2017-06-21 15:01 UTC
- cocos2d-x version:
- devices test on:
- developing environments
   -NDK version: 14.1
   -Android Studio 2.3.3

Steps to Reproduce:

1. Create a new project and run it on Simulator

After the app started, it was stuck in black all the time. I noticed this topic [#17850](https://github.com/cocos2d/cocos2d-x/issues/17850) also met the similar thing, but my logcat gave different information like below.

06-21 03:25:04.710 16078-16078/com.MyCompany.MyGame W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=x86 --instruction-set-features=smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=x86 --instruction-set-features=default --dex-file=/data/app/com.MyCompany.MyGame-2/split_lib_dependencies_apk.apk --oat-file=/data/dalvik-cache/x86/data@app@com.MyCompany.MyGame-2@split_lib_dependencies_apk.apk@classes.dex) because non-0 exit status

**Comment by guoyingtao** [comment] 2017-06-22 16:20
**Debug info**

06-22 12:02:40.725 3050-3097/com.MyCompany.MyGame D/cocos2d-x debug info: {
                                                                          	gl.supports_OES_packed_depth_stencil: true
                                                                          	gl.supports_vertex_array_object: false
                                                                          	gl.supports_BGRA8888: false
                                                                          	gl.supports_ATITC: false
                                                                          	gl.supports_S3TC: false
                                                                          	cocos2d.x.version: cocos2d-x-3.15.1
                                                                          	gl.supports_discard_framebuffer: false
                                                                          	cocos2d.x.compiled_with_profiler: false
                                                                          	gl.supports_PVRTC: false
                                                                          	cocos2d.x.build_type: DEBUG
                                                                          	gl.renderer: Android Emulator OpenGL ES Translator (AMD Radeon R9 M370X OpenGL Engine)
                                                                          	gl.supports_OES_depth24: true
                                                                          	gl.supports_ETC1: true
                                                                          	gl.supports_OES_map_buffer: false
                                                                          	cocos2d.x.compiled_with_gl_state_cache: true
                                                                          	gl.version: OpenGL ES 2.0 (2.1 ATI-1.51.8)
                                                                          	gl.supports_NPOT: true
                                                                          	gl.max_texture_units: 16
                                                                          	gl.vendor: Google (ATI Technologies Inc.)
                                                                          	gl.max_texture_size: 16384
                                                                          }


**I found it kept looping this information.**

06-22 12:02:57.097 3050-3097/com.MyCompany.MyGame D/cocos*2d-x debug info: cocos2d: warning: Uniform not found: depth
06-22 12:02:57.115 3050-3097/com.MyCompany.MyGame D/cocos2d-x debug info: cocos2d: warning: Uniform not found: depth
06-22 12:02:57.134 3050-3097/com.MyCompany.MyGame D/cocos2d-x debug info: cocos2d: warning: Uniform not found: depth
06-22 12:02:57.151 3050-3097/com.MyCompany.MyGame D/cocos2d-x debug info: cocos2d: warning: Uniform not found: depth
06-22 12:02:57.168 3050-3097/com.MyCompany.MyGame D/cocos2d-x debug info: cocos2d: warning: Uniform not found: depth

**Comment by gamehelphere** [comment] 2017-07-14 19:40
Hi guoyingtao,

I also have this problem in Android Studio. I am still using Cocos2D-X 3.15. I noticed that the problem started after a new update on Android Studio's emulator. Things became like this after the update. I tried to add the missing shader variable '**depth**' in all the vertex shader files, but the problem is still there.

I hope a fix would be made soon for us Android fans. :)

**Comment by gamehelphere** [comment] 2017-07-17 23:14
Hi guoyingtao and everyone in the Cocos2d-x community,

I solved the black screen problem! :D I did some tinkering with a running emulator and changed a little setting that was applied from the recent Android Studio Emulator update. Here are the steps:

1. Do not run your project yet. Open an emulator using the command line or by clicking the AVD Manager button. Wait until the emulator shows its main screen.
2. There is a menu on the right side of the running emulator to control the other parts of the device. Find the **ellipsis** or the **three dots (...)** option at the bottom of the right side. That is the **More** button. Click that button to open the **Extended Controls** window.
3. In that window, find the option called **OpenGL ES renderer (requires restart)**. Click the dropdown box and you will see some items. Find the **SwiftShader** option and select it. This is the renderer that works with our Cocos2d-x projects.
4. Find the option called **OpenGL ES API Level (requires restart)**. Make sure it has the item _OpenGL ES 2.0 (default)_ selected for the best performance.
5. Close that emulator. If you have multiple emulators open, close them all.
6. Start an emulator with the new settings.
7. Run your Cocos2d-x project with the new emulator and it will work! =D

I read some articles about the SwiftShader Renderer and that may be the default renderer for current and upcoming Android devices. I observed that my Cocos2d-x projects render slower than before with SwiftShader, and I do not know why. Maybe things are still evolving with SwiftShader and Android. The important thing is that our projects will now work with the Android emulator if this kind of problem shows up in our setup.

=D

**Comment by Anywhere-Music-Player** [comment] 2017-07-24 11:20
Same here and thank you so much. It helps. @minggo I believe this should be considered as bug\problem...

**Comment by gamehelphere** [comment] 2017-07-25 01:18
You're welcome KAMIKAZEUA. I'm glad it helped. ;D

**Comment by minggo** [comment] 2017-07-26 01:18
> execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg --debuggable --instruction-set=x86

I think the problem is because the simulator uses x86 instructions, but the apps are not build with x86.

**Comment by Anywhere-Music-Player** [comment] 2017-07-26 08:27
I'm compiling currently only for x86 and using x86 emulator images, because I don't have any devices

**Comment by Dimon4eg** [comment] 2017-11-05 07:55
I have the same problem on emulators except one.

This configuration works for me:
![image](https://user-images.githubusercontent.com/1271541/32412977-4f4879a2-c20f-11e7-95fd-e3bf3eb71c3a.png)

![image](https://user-images.githubusercontent.com/1271541/32412984-68bf8b5a-c20f-11e7-91bf-ce711ac44340.png)

**Comment by gamehelphere** [comment] 2017-12-31 03:46
Hi Dimon4eg,

It is great that your setup works with the Desktop native OpenGL. I tried the same in my computer but it did not work. It worked when I went back to SwiftShader, and I think the OpenGL drivers on your computer works well with that emulator.

All was well when I was using SwiftShader, but things went back to this problem after some emulator updates on my Android Studio. I tried to run some basic OpenGL code and those worked on the updated emulator and not on my Cocos2d-X 3.16 game project.

It took some time and I managed to make a code fix in the renderer. I only tested my fix on my setup which is my only available computer. I wrote the whole procedure in a document that you can download and read here.

https://goo.gl/C6VTxo

This fix targets the **OpenGL error 0x501 and 0x502** with the blank Android Emulator screen.

**Comment by Dimon4eg** [comment] 2017-12-31 18:01
hi @gamehelphere!
Cool, your fix works on my windows PC!
And it works on my phone with Android 4.4.2
Your fix affects android platform.
Do you think this fix related to simulation only or to the whole android platform?

**Comment by Anywhere-Music-Player** [comment] 2017-12-31 18:48
@minggo it’s really should get attention. 
Because not using SwiftShader - emulator works very slow, impossible to play. With this fix it should work with SwiftShader which is needed.

**Comment by gamehelphere** [comment] 2018-01-01 04:23
Hi Dimon4eg and KAMIKAZEUA,

Thank you both for checking and trying my code fix in your setups.

Thank you also Dimon4eg for testing my code and confirming it works in your Windows PC and Android phone.

I think this code fix can affect both Android emulators and actual Android devices because of your tests, Dimon4eg and KAMIKAZEUA. The code fix will enable SwiftShader rendering instead of showing a blank screen if the Desktop native OpenGL renderer cannot be used by the Android emulator. In actual Android devices, the output will be accelerated. These results are based on our tests of the code fix.

**Comment by Dimon4eg** [comment] 2018-01-01 07:57
Many thanks to you @gamehelphere 
You spent a lot of time to fix this issue.
I also spend some time but without success.

More details how it works in my case.
Android Studio 3.0.1
Cocos2d-X 3.16
NDK-R14b
![image](https://user-images.githubusercontent.com/1271541/34466366-3b80e836-eed9-11e7-8c76-9690c21299b8.png)

**Comment by gamehelphere** [comment] 2018-01-02 15:13
Hi @Dimon4eg ,

Thank you for sharing the details of your emulator configuration. With your setup, the bugfix also works on Cocos2d-X apps running with Android emulators and devices using OpenGL 3.

You are welcome! ;D This is my way of helping the Cocos2d-X community. We help each other to advance what we can for the library.

It would be great if this bugfix could be applied to the current and upcoming releases of Cocos2d-X, after a little more testing by the maintainers.

**Comment by Dimon4eg** [comment] 2018-01-02 15:19
@gamehelphere maybe create pull request so @minggo will just merge it

**Comment by gamehelphere** [comment] 2018-01-02 15:29
Hi @Dimon4eg ,

Ok, I will try. This is my first time doing a pull request on the current Cocos2d-X 3 sources.

XD

**Comment by Dimon4eg** [comment] 2018-01-02 15:32
Go forward, you can do it ;)

**Comment by gamehelphere** [comment] 2018-01-02 17:46
Hi @Dimon4eg ,

I followed the directions in the **Contributing to cocos2d-x** document under the section **Submitting patches.** I did most of the steps and got stuck with this item.

**Send a “pull request” to user “cocos2d”**

I already have the **my_fix_branch** in my public repository and tried to make a pull request to the cocos2d repository, but that repository is not listed in my dropdown boxes. I also read some articles on doing pull requests and have not found how to send a pull request using the github web version to another user.

Could you give some advice on how to do that? Or if I did something wrong with the steps on the procedures, and how to correct them.

Thanks!

**Comment by gamehelphere** [comment] 2018-01-02 19:58
Hi @Dimon4eg ,

I figured out how to make the contribution procedures work. There was a **fork** button on top of the main cocos2d-x project page and I clicked it. The button made a clone of the project in my account and I was able to continue the steps in the command line. New readers of the **Submitting patches** section can think of the fork button as step 0. :)

Thanks for the encouragement, @Dimon4eg !

**Comment by Dimon4eg** [comment] 2018-01-03 12:45
Well done!
Sorry for not responding in time

**Comment by gamehelphere** [comment] 2018-01-04 03:26
Hi @Dimon4eg ,

No worries. Thank you!

:D

**Comment by Dimon4eg** [comment] 2018-01-04 09:22
@minggo please close this issue

**Comment by minggo** [comment] 2018-01-05 01:04
thanks

**Closed as completed by minggo** 2018-01-05 01:04 UTC

**Comment by daniaDlbani** [comment] 2019-02-08 16:13
I have the same issue with cocos 2.2.6. Is there any update for CCGLProgram.cpp code?

**Comment by gamehelphere** [comment] 2019-02-12 13:12
Hi @daniaDlbani,

I recommend updating your setup from 2.2.6 to 3.17.1. The CCGLProgram.cpp sources are also updated in the latest version.

Cheers.

**Comment by daniaDlbani** [comment] 2019-02-12 13:22
Upgrading of cocos is not doable. the project is old and framework contains many changes.
