### ISSUE TITLE
JniHelper no long thread safe.

### ISSUE THREAD

**Issue by superrad** [cocos2d/cocos2d-x#16581] opened 2016-09-14 15:46 UTC
In Cocos 3.11 JniHelper was modified to clean up local references to converted strings automatically, this however has made JniHelper no longer threadsafe. I know that most of Cocos2dx isn't thread safe, but as JniHelper is a platform interop class it would be more useful if it itself was.

The static localRefs variable which is a member of JniHelper (https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/platform/android/jni/JniHelper.h#L244) can be accessed and modified by multiple threads calling into JniHelper code at the same time.

Access to the localRefs variable should be guarded by a mutex and the vectors for jobjects should probably be segmented by the current thread's id so as to prevent simultaneous accessing of jobject vectors.

**Comment by ricardoquesada** [comment] 2016-09-14 18:10
thanks. yes, cocos2d-x is not threadsafe.
are you using JniHelper is a way that you need it to be thread safe? you you attach an example that triggers the bug? thanks.

**Comment by umair6** [comment] 2017-08-18 14:19
@superrad @ricardoquesada 
I am facing one crash in JniHelper class which, I think, is related to above discussion.
[Crash.txt](https://github.com/cocos2d/cocos2d-x/files/1234651/Crash.txt)

`#0. Crashed: ohs.egypt.slots|
0  libcocos2dcpp.so               0xa0117a84 std::__ndk1::__hash_table<std::__ndk1::__hash_value_type<_JNIEnv*, std::__ndk1::vector<_jobject*, std::__ndk1::allocator<_jobject*> > >, std::__ndk1::__unordered_map_hasher<_JNIEnv*, std::__ndk1::__hash_value_type<_JNIEnv*, std::__ndk1::vector<_jobject*, std::__ndk1::allocator<_jobject*> > >, std::__ndk1::hash<_JNIEnv*>, true>, std::__ndk1::__unordered_map_equal<_JNIEnv*, std::__ndk1::__hash_value_type<_JNIEnv*, std::__ndk1::vector<_jobject*, std::__ndk1::allocator<_jobject*> > >, std::__ndk1::equal_to<_JNIEnv*>, true>, std::__ndk1::allocator<std::__ndk1::__hash_value_type<_JNIEnv*, std::__ndk1::vector<_jobject*, std::__ndk1::allocator<_jobject*> > > > >::__rehash(unsigned int) (__hash_table:2005)
1  libcocos2dcpp.so               0xa0117bdd std::__ndk1::__hash_table<std::__ndk1::__hash_value_type<_JNIEnv*, std::__ndk1::vector<_jobject*, std::__ndk1::allocator<_jobject*> > >, std::__ndk1::__unordered_map_hasher<_JNIEnv*, std::__ndk1::__hash_value_type<_JNIEnv*, std::__ndk1::vector<_jobject*, std::__ndk1::allocator<_jobject*> > >, std::__ndk1::hash<_JNIEnv*>, true>, std::__ndk1::__unordered_map_equal<_JNIEnv*, std::__ndk1::__hash_value_type<_JNIEnv*, std::__ndk1::vector<_jobject*, std::__ndk1::allocator<_jobject*> > >, std::__ndk1::equal_to<_JNIEnv*>, true>, std::__ndk1::allocator<std::__ndk1::__hash_value_type<_JNIEnv*, std::__ndk1::vector<_jobject*, std::__ndk1::allocator<_jobject*> > > > >::__node_insert_unique(std::__ndk1::__hash_node<std::__ndk1::__hash_value_type<_JNIEnv*, std::__ndk1::vector<_jobject*, std::__ndk1::allocator<_jobject*> > >, void*>*) (__hash_table:1957)
2  libcocos2dcpp.so               0xa0117d4b std::__ndk1::unordered_map<_JNIEnv*, std::__ndk1::vector<_jobject*, std::__ndk1::allocator<_jobject*> >, std::__ndk1::hash<_JNIEnv*>, std::__ndk1::equal_to<_JNIEnv*>, std::__ndk1::allocator<std::__ndk1::pair<_JNIEnv* const, std::__ndk1::vector<_jobject*, std::__ndk1::allocator<_jobject*> > > > >::operator[](_JNIEnv* const&) (unordered_map:1364)
3  libcocos2dcpp.so               0xa0117e27 cocos2d::JniHelper::deleteLocalRefs(_JNIEnv*) (JniHelper.cpp:308)
4  libcocos2dcpp.so               0xa0113143 std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > cocos2d::JniHelper::callStaticStringMethod<>(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&) (JniHelper.h:216)
5  libcocos2dcpp.so               0xa0114893 cocos2d::FileUtilsAndroid::getWritablePath() const (CCFileUtils-android.cpp:317)
6  libcocos2dcpp.so               0xa03b9e5c cocos2d::network::HttpClient::processResponse(cocos2d::network::HttpResponse*, char*) (HttpClient-android.cpp:254)
7  libcocos2dcpp.so               0xa03ba154 cocos2d::network::HttpClient::networkThreadAlone(cocos2d::network::HttpRequest*, cocos2d::network::HttpResponse*) (HttpClient-android.cpp:786)
8  libcocos2dcpp.so               0xa03b5ea4 void* std::__ndk1::__thread_proxy<std::__ndk1::tuple<void (cocos2d::network::HttpClient::*)(cocos2d::network::HttpRequest*, cocos2d::network::HttpResponse*), cocos2d::network::HttpClient*, cocos2d::network::HttpRequest*, cocos2d::network::HttpResponse*> >(void*) (__functional_base:380)`

I am performing several parallel http requests using HttpClient's sendImmediate function.
These logs are from crashlytics. I dont know the exact steps to reproduce it yet but there are several occurances on crashlyitcs.
Currently, I am using cocos2d-x 3.15.1. Also faced same issue in 3.13.1 too.

cocos2d-x: 3.15.1
ndk: r13b

**Comment by umair6** [comment] 2017-08-22 07:55
@minggo Please have a look. We have several occurrences of above issue in our games.

**Comment by minggo** [comment] 2017-08-22 08:21
sure, i will take a look tomorrow

**Comment by minggo** [comment] 2017-08-23 03:02
@umair6 does the log you pasted from Fabric's crashlyitcs? Can release mode also generate such a crash call stack?

**Comment by umair6** [comment] 2017-08-23 06:07
@minggo  yes this is from Fabri'c crashlyitcs.  This log is from release mode build. Check attached crash.txt for complete log.

**Comment by minggo** [comment] 2017-08-24 07:06
fixed in https://github.com/cocos2d/cocos2d-x/pull/18189. Avoid using mutex for performance reason, because gl thread may be blocked if using mutex.

**Comment by umair6** [comment] 2017-08-24 07:23
@minggo 
Thanks. 
I will merge these changes and will let you know in case of issue.

**Comment by minggo** [comment] 2017-09-06 07:08
@umair6 any update? If it can not fix the issue, then i will re-open it.

**Closed as completed** 2017-09-06 07:07 UTC
Labels: platform:android

**Comment by umair6** [comment] 2017-09-06 08:36
@minggo  issue is fixed. Thanks.
