### ISSUE TITLE
[ios] ccui.EditBox, bug when hide keyboard without enter.

### ISSUE THREAD

**Issue by xpol** [cocos2d/cocos2d-x#12650] opened 2015-07-02 09:19 UTC
I have a ccui.EditBox used as username input:
1. Remove old app
2. reinstall my app using Xcode run
3. run app, tap the ccui.EditBox, switch IME to **English (US)**
4. When input `li` and the `Ali` will have focus, see attached image.
5. Click outside of keyboard, the keyboard hides, and the ccui.EditBox will have `li` filled.
6. ccui.EditBox:getText() will returns `Ali`.

![1_pic](https://cloud.githubusercontent.com/assets/20248/8473509/c58e596e-20dc-11e5-8af4-0a4c45114c5a.jpg)

I tested under **iOS 8.4** (iPhone 6 Plus) and **iOS 8.3** (iPad Air 2).

_PS: my boss Mr. Li ask that this bug shall name after him._

**Comment by pandamicro** [comment] 2015-07-02 09:44
Thanks for reporting, if we have names for the bugs, we will name it after Li, :-)

**Comment by zilongshanren** [comment] 2015-07-02 09:47
@xpol  How could I reproduce this issue? Which device is needed for reproducing this issue?

**Comment by zilongshanren** [comment] 2015-07-02 09:48
@xpol  Which input method do you use?

**Comment by xpol** [comment] 2015-07-02 09:51
@andyque 

IME: English (US)

I tested under iOS 8.4 (iPhone 6 Plus) and iOS 8.3 (iPad Air 2).

**Comment by zilongshanren** [comment] 2015-07-02 09:56
@xpol  I still can't reproduce this issue. Have you try a different device?

**Comment by zilongshanren** [comment] 2015-11-23 04:05
@xpol  Any updates?

**Comment by xpol** [comment] 2015-11-23 04:29
@zilongshanren  Sorry I'm not woking on that project any more.
And it is iOS 9.1 here now.

**Comment by zilongshanren** [comment] 2015-11-23 08:03
So, I just close it here. 
If you meet this issue again, feel free to reopen it.

**Closed as completed by zilongshanren** 2015-11-23 08:03 UTC
Labels: type:bug, platform:ios
