### ISSUE TITLE
v3.4 on windows render abnormal

### ISSUE THREAD

**Issue by panxh** [cocos2d/cocos2d-x#10372] opened 2015-02-04 12:33 UTC
We upgrade our project fro v3.3 to v3.4, and upgrade  cocoStudio to v2.1, then export all the csb files used by the project. The upgrade process was successful, but after that,when  running the project,we found the render system seems running abnormal on windows,  however it runs on on mac and android, we thought maybe the opengl issue. Follows figure is the screenshots on windows.
![1](https://cloud.githubusercontent.com/assets/8553669/6040426/b23f48ea-acac-11e4-9533-174d5e4d3563.png)

the following screenshots is the result running on mac,which is ok
![2015-02-04 8 34 32](https://cloud.githubusercontent.com/assets/8553669/6040479/415075f4-acad-11e4-96f8-311037ae36dd.png)

**Comment by xiaofeng11** [comment] 2015-08-20 02:12
@panxh
Hi, Does your project in a folder name contain Chinese or other Unicode characters? From the screen shot your provider, it is obviously windows version missing some resource file. Because cocos2dx won't support unicode folder name, If put the project under a folder that name contain Chinese characters, will cause this problem. Under MacOS, the system default code page is unicode, so the Chinese folder name won't cause problem

**Comment by pandamicro** [comment] 2015-08-31 02:28
@panxh please check wether your issue is caused by what @xiaofeng11 said. If there is no further informations, I will close this issue for now. You can comment to add more informations, and I will reopen it

**Closed as completed by pandamicro** 2015-08-31 02:28 UTC
Labels: type:bug
